export type { Span, SpanDetail, SpanKind, SpanStatusCode } from "./entities/span.ts"
export type { Trace, TraceDetail, TraceStatus } from "./entities/trace.ts"
export type { SpanListOptions, SpanRepositoryShape } from "./ports/span-repository.ts"
export { SpanRepository } from "./ports/span-repository.ts"
export type { TraceListOptions, TraceRepositoryShape } from "./ports/trace-repository.ts"
export { TraceRepository } from "./ports/trace-repository.ts"
