version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: arn:aws:ecs:eu-central-1:442420265876:task-definition/LatitudeLLMAppTaskFamily:1
        LoadBalancerInfo:
          ContainerName: 'LatitudeLLMAppContainer'
          ContainerPort: 8080
