import { createContext, type ReactNode, type RefObject, useCallback, useMemo, useRef, useState } from "react"
import type { GenAIMessage } from "rosetta-ai"
import { useMountEffect } from "../../hooks/use-mount-effect.ts"

// --- Public types ---

export interface TextSelectionAnchor {
  messageIndex: number
  partIndex: number
  startOffset: number
  endOffset: number
  selectedText: string
}

export interface HighlightRange {
  messageIndex: number
  partIndex: number
  startOffset: number
  endOffset: number
  type: "annotation" | "selection"
  passed?: boolean
  id?: string
  onClick?: (position: { x: number; y: number }) => void
}

interface TextSelectionContextValue {
  selection: TextSelectionAnchor | null
  getHighlightsForBlock: (messageIndex: number, partIndex: number) => HighlightRange[]
}

const TextSelectionContext = createContext<TextSelectionContextValue | null>(null)

export { TextSelectionContext }

function getPartText(
  messages: readonly (GenAIMessage | null)[],
  messageIndex: number,
  partIndex: number,
): string | null {
  const msg = messages[messageIndex]
  if (!msg) return null

  let parts = msg.parts
  if (!parts || parts.length === 0) {
    const content = (msg as { content?: string }).content
    if (typeof content === "string") {
      parts = [{ type: "text" as const, content }]
    } else {
      return null
    }
  }

  const part = parts[partIndex]
  if (!part) return null

  if (part.type === "text" || part.type === "reasoning") {
    return (part as { content: string }).content ?? null
  }
  return null
}

function findIndices(node: Node) {
  let el: HTMLElement | null = node.nodeType === Node.TEXT_NODE ? node.parentElement : (node as HTMLElement)

  let messageIndex: number | null = null
  let partIndex: number | null = null
  let contentType: string | null = null

  while (el) {
    if (messageIndex === null) {
      const v = el.getAttribute("data-message-index")
      if (v !== null) messageIndex = parseInt(v, 10)
    }
    if (partIndex === null) {
      const v = el.getAttribute("data-part-index")
      if (v !== null) partIndex = parseInt(v, 10)
    }
    if (contentType === null) {
      const v = el.getAttribute("data-content-type")
      if (v) contentType = v
    }
    if (messageIndex !== null && partIndex !== null) break
    el = el.parentElement
  }

  if (messageIndex !== null && partIndex !== null) {
    return { messageIndex, partIndex, contentType: contentType ?? "text" }
  }
  return null
}

function findPartRoot(node: Node): HTMLElement | null {
  let el: HTMLElement | null = node.nodeType === Node.TEXT_NODE ? node.parentElement : (node as HTMLElement)
  while (el) {
    if (el.getAttribute("data-part-index") !== null) return el
    el = el.parentElement
  }
  return null
}

function collectTextNodes(root: HTMLElement): Text[] {
  const nodes: Text[] = []
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, null)
  let n = walker.nextNode()
  while (n) {
    if (n.textContent) nodes.push(n as Text)
    n = walker.nextNode()
  }
  return nodes
}

function getSourceOffsetsFromNode(node: Node): { start: number; end: number } | null {
  let el: HTMLElement | null = node.nodeType === Node.TEXT_NODE ? node.parentElement : (node as HTMLElement)

  while (el && el.getAttribute("data-part-index") === null) {
    const start = el.getAttribute("data-source-start")
    const end = el.getAttribute("data-source-end")
    if (start !== null && end !== null) {
      const startNum = parseInt(start, 10)
      const endNum = parseInt(end, 10)
      if (!Number.isNaN(startNum) && !Number.isNaN(endNum) && endNum >= startNum) {
        return { start: startNum, end: endNum }
      }
    }
    el = el.parentElement
  }
  return null
}

// --- Position map: the single source of truth for DOM↔source mapping ---

interface MappedTextNode {
  node: Text
  domStart: number
  domEnd: number
  sourceStart: number
  sourceEnd: number
}

/**
 * Build a flat array mapping each source-mapped text node to its DOM range
 * (character offsets in the concatenated text of ALL text nodes under partRoot)
 * and its source range (offsets in the original markdown).
 *
 * Text nodes without data-source-* attributes (e.g. whitespace between tags
 * generated by the HTML serializer) are tracked for DOM offset accumulation
 * but excluded from the returned map since they can't be mapped to source.
 */
function buildPositionMap(textNodes: Text[]): { map: MappedTextNode[]; totalDomLength: number } {
  const map: MappedTextNode[] = []
  let domOffset = 0
  for (const node of textNodes) {
    const len = node.textContent?.length ?? 0
    const source = getSourceOffsetsFromNode(node)
    if (source && len > 0) {
      map.push({
        node,
        domStart: domOffset,
        domEnd: domOffset + len,
        sourceStart: source.start,
        sourceEnd: source.end,
      })
    }
    domOffset += len
  }
  return { map, totalDomLength: domOffset }
}

/**
 * Resolve a DOM Range boundary to a character offset in the flat text-node
 * concatenation. Works for both Text and Element containers.
 */
function resolveDomOffset(textNodes: Text[], container: Node, offset: number, side: "start" | "end"): number {
  if (container.nodeType === Node.TEXT_NODE) {
    let acc = 0
    for (const tn of textNodes) {
      if (tn === container) return acc + offset
      acc += tn.textContent?.length ?? 0
    }
    return -1
  }

  // Container is an Element. offset is a child-node index per DOM spec.
  const children = container.childNodes
  if (side === "start") {
    for (let i = offset; i < children.length; i++) {
      const result = domOffsetOfFirstMatch(textNodes, children[i])
      if (result >= 0) return result
    }
    for (let i = offset - 1; i >= 0; i--) {
      const result = domOffsetOfLastMatch(textNodes, children[i])
      if (result >= 0) return result
    }
  } else {
    for (let i = offset - 1; i >= 0; i--) {
      const result = domOffsetOfLastMatch(textNodes, children[i])
      if (result >= 0) return result
    }
    // offset=0 or no match in children before offset: find the last textNode
    // in our list that's contained by this element.
    for (let i = textNodes.length - 1; i >= 0; i--) {
      const tn = textNodes[i]
      if (tn && container.contains(tn)) {
        return domOffsetOf(textNodes, tn, tn.textContent?.length ?? 0)
      }
    }
  }
  return -1
}

function domOffsetOf(textNodes: Text[], target: Text, charOffset: number): number {
  let acc = 0
  for (const tn of textNodes) {
    if (tn === target) return acc + charOffset
    acc += tn.textContent?.length ?? 0
  }
  return -1
}

/**
 * Find the first text node under `root` that exists in our textNodes list,
 * and return its DOM offset (start of that node).
 */
function domOffsetOfFirstMatch(textNodes: Text[], root: Node | null | undefined): number {
  if (!root) return -1
  // Fast path: root itself is a text node
  if (root.nodeType === Node.TEXT_NODE) return domOffsetOf(textNodes, root as Text, 0)
  if (root.nodeType !== Node.ELEMENT_NODE) return -1
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, null)
  let n = walker.nextNode()
  while (n) {
    const result = domOffsetOf(textNodes, n as Text, 0)
    if (result >= 0) return result
    n = walker.nextNode()
  }
  return -1
}

/**
 * Find the last text node under `root` that exists in our textNodes list,
 * and return its DOM offset (end of that node).
 */
function domOffsetOfLastMatch(textNodes: Text[], root: Node | null | undefined): number {
  if (!root) return -1
  if (root.nodeType === Node.TEXT_NODE) return domOffsetOf(textNodes, root as Text, root.textContent?.length ?? 0)
  if (root.nodeType !== Node.ELEMENT_NODE) return -1
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, null)
  let last: Text | null = null
  let n = walker.nextNode()
  while (n) {
    // Only consider nodes in our list (quick identity scan via domOffsetOf is
    // O(n) but textNodes is typically small — tens of nodes per part).
    if (domOffsetOf(textNodes, n as Text, 0) >= 0) last = n as Text
    n = walker.nextNode()
  }
  if (!last) return -1
  return domOffsetOf(textNodes, last, last.textContent?.length ?? 0)
}

/**
 * Convert a DOM character offset to a markdown source offset using the
 * position map. For offsets that fall between mapped nodes (e.g. in
 * whitespace text nodes between structural elements), snaps to the nearest
 * mapped boundary.
 */
function domToSource(domPos: number, map: MappedTextNode[], side: "start" | "end"): number {
  // Exact hit inside a mapped node — interpolate proportionally
  for (const entry of map) {
    if (domPos >= entry.domStart && domPos <= entry.domEnd) {
      const domLen = entry.domEnd - entry.domStart
      const sourceLen = entry.sourceEnd - entry.sourceStart
      if (domLen === 0) return entry.sourceStart
      const ratio = (domPos - entry.domStart) / domLen
      return Math.round(entry.sourceStart + ratio * sourceLen)
    }
  }

  // Falls in a gap (unmapped whitespace between structural elements).
  // Snap to the closest mapped boundary.
  if (side === "start") {
    // Find first mapped node that starts at or after domPos
    for (const entry of map) {
      if (entry.domStart >= domPos) return entry.sourceStart
    }
    // Past everything — use end of last entry
    const last = map[map.length - 1]
    return last ? last.sourceEnd : -1
  }

  // side === "end": find last mapped node that ends at or before domPos
  for (let i = map.length - 1; i >= 0; i--) {
    const entry = map[i]
    if (entry && entry.domEnd <= domPos) return entry.sourceEnd
  }
  const first = map[0]
  return first ? first.sourceStart : -1
}

/**
 * Computes canonical markdown source offsets from a DOM Range.
 *
 * Approach: build a flat position map of all source-mapped text nodes,
 * resolve the Range boundaries to DOM character offsets, then convert
 * those to source offsets via the map.
 */
function calculateTextOffsets(
  textNodes: Text[],
  range: Range,
  fullTextLength: number,
): { textStart: number; textEnd: number } | null {
  const selectedText = range.toString()
  if (!selectedText.trim()) return null

  const { map } = buildPositionMap(textNodes)
  if (map.length === 0) return null

  const domStart = resolveDomOffset(textNodes, range.startContainer, range.startOffset, "start")
  const domEnd = resolveDomOffset(textNodes, range.endContainer, range.endOffset, "end")
  if (domStart < 0 || domEnd < 0 || domEnd <= domStart) return null

  const textStart = domToSource(domStart, map, "start")
  const textEnd = domToSource(domEnd, map, "end")

  if (textStart < 0 || textEnd < 0 || textEnd <= textStart || textEnd > fullTextLength) return null
  return { textStart, textEnd }
}

// --- Selection hook ---

function useTextSelectionHook(
  messages: readonly (GenAIMessage | null)[],
  containerRef: RefObject<HTMLElement | null>,
  onSelect?: (anchor: TextSelectionAnchor, position: { x: number; y: number }) => void,
) {
  const [selection, setSelection] = useState<TextSelectionAnchor | null>(null)

  const clearSelection = useCallback(() => {
    setSelection(null)
    const ws = window.getSelection()
    if (ws?.rangeCount && containerRef.current?.contains(ws.getRangeAt(0).commonAncestorContainer)) {
      ws.removeAllRanges()
    }
  }, [containerRef])

  const messagesRef = useRef(messages)
  messagesRef.current = messages
  const onSelectRef = useRef(onSelect)
  onSelectRef.current = onSelect
  const selectionRef = useRef(selection)
  selectionRef.current = selection

  const processSelection = useCallback(() => {
    const windowSelection = window.getSelection()
    if (!windowSelection || windowSelection.rangeCount === 0) return

    const range = windowSelection.getRangeAt(0)
    const selectedText = range.toString().trim()
    if (!selectedText) {
      if (selectionRef.current) clearSelection()
      return
    }

    if (
      !containerRef.current?.contains(range.commonAncestorContainer) &&
      !containerRef.current?.contains(range.startContainer)
    ) {
      clearSelection()
      return
    }

    const startInfo = findIndices(range.startContainer)
    const endInfo = findIndices(range.endContainer)

    if (!startInfo || !endInfo) {
      if (process.env.NODE_ENV === "development") {
        console.warn("[TextSelection] Could not find message/part indices", {
          startContainer: range.startContainer,
          endContainer: range.endContainer,
          startInfo,
          endInfo,
        })
      }
      clearSelection()
      return
    }

    if (
      startInfo.messageIndex !== endInfo.messageIndex ||
      startInfo.partIndex !== endInfo.partIndex ||
      (startInfo.contentType !== "text" && startInfo.contentType !== "reasoning")
    ) {
      clearSelection()
      return
    }

    const fullText = getPartText(messagesRef.current, startInfo.messageIndex, startInfo.partIndex)
    if (!fullText) {
      if (process.env.NODE_ENV === "development") {
        console.warn("[TextSelection] Could not get part text", { startInfo })
      }
      clearSelection()
      return
    }

    const partRoot = findPartRoot(range.startContainer)
    if (!partRoot) {
      if (process.env.NODE_ENV === "development") {
        console.warn("[TextSelection] Could not find part root", { startContainer: range.startContainer })
      }
      clearSelection()
      return
    }

    const textNodes = collectTextNodes(partRoot)
    const offsets = calculateTextOffsets(textNodes, range, fullText.length)
    if (!offsets) {
      if (process.env.NODE_ENV === "development") {
        console.warn("[TextSelection] Could not calculate offsets", {
          selectedText: range.toString().slice(0, 100),
          textNodesCount: textNodes.length,
          startContainerType: range.startContainer.nodeType === Node.TEXT_NODE ? "text" : "element",
          endContainerType: range.endContainer.nodeType === Node.TEXT_NODE ? "text" : "element",
          fullTextLength: fullText.length,
        })
      }
      return
    }

    const anchor: TextSelectionAnchor = {
      messageIndex: startInfo.messageIndex,
      partIndex: startInfo.partIndex,
      startOffset: offsets.textStart,
      endOffset: offsets.textEnd,
      selectedText,
    }

    setSelection(anchor)

    const rect = range.getBoundingClientRect()
    onSelectRef.current?.(anchor, { x: rect.left, y: rect.bottom })

    window.getSelection()?.removeAllRanges()
  }, [clearSelection, containerRef])

  useMountEffect(() => {
    let rafId: number | null = null
    let timerId: ReturnType<typeof setTimeout> | null = null
    let isSelecting = false

    const cancelPending = () => {
      if (rafId !== null) {
        cancelAnimationFrame(rafId)
        rafId = null
      }
      if (timerId !== null) {
        clearTimeout(timerId)
        timerId = null
      }
    }

    const handleSelectStart = (e: Event) => {
      const target = e.target
      const el = target instanceof Element ? target : (target as Node).parentElement
      if (el && containerRef.current?.contains(el)) {
        cancelPending()
        isSelecting = true
      }
    }

    const handleMouseUp = () => {
      cancelPending()
      if (!isSelecting) return

      const ws = window.getSelection()
      if (ws?.rangeCount && containerRef.current?.contains(ws.getRangeAt(0).commonAncestorContainer)) {
        rafId = requestAnimationFrame(() => {
          rafId = null
          timerId = setTimeout(() => {
            processSelection()
            isSelecting = false
            timerId = null
          }, 0)
        })
      } else {
        isSelecting = false
      }
    }

    const handleClickOutside = (e: MouseEvent) => {
      const el = e.target instanceof Element ? e.target : (e.target as Node).parentElement
      if (!el) return
      if (el.closest("[data-selection-popover]") || el.closest('[role="dialog"]')) return
      const tagName = (e.target as Element)?.tagName?.toLowerCase()
      if (tagName === "textarea" || tagName === "input") return
      if (containerRef.current && !containerRef.current.contains(el)) clearSelection()
    }

    document.addEventListener("selectstart", handleSelectStart)
    document.addEventListener("mouseup", handleMouseUp)
    document.addEventListener("click", handleClickOutside, true)

    return () => {
      cancelPending()
      document.removeEventListener("selectstart", handleSelectStart)
      document.removeEventListener("mouseup", handleMouseUp)
      document.removeEventListener("click", handleClickOutside, true)
    }
  })

  return { selection, clearSelection }
}

export function TextSelectionProvider({
  messages,
  containerRef,
  onSelect,
  highlightRanges = [],
  children,
}: {
  readonly messages: readonly (GenAIMessage | null)[]
  readonly containerRef: RefObject<HTMLElement | null>
  readonly onSelect?: ((anchor: TextSelectionAnchor, position: { x: number; y: number }) => void) | undefined
  readonly highlightRanges?: ReadonlyArray<HighlightRange> | undefined
  readonly children: ReactNode
}) {
  const { selection } = useTextSelectionHook(messages, containerRef, onSelect)

  const rangeIndex = useMemo(() => {
    const map = new Map<string, HighlightRange[]>()

    for (const r of highlightRanges) {
      const key = `${r.messageIndex}:${r.partIndex}`
      let arr = map.get(key)
      if (!arr) {
        arr = []
        map.set(key, arr)
      }
      arr.push(r)
    }

    if (selection) {
      const key = `${selection.messageIndex}:${selection.partIndex}`
      let arr = map.get(key)
      if (!arr) {
        arr = []
        map.set(key, arr)
      }
      const isDuplicate = arr.some(
        (r) => r.startOffset === selection.startOffset && r.endOffset === selection.endOffset,
      )
      if (!isDuplicate) {
        arr.push({
          messageIndex: selection.messageIndex,
          partIndex: selection.partIndex,
          startOffset: selection.startOffset,
          endOffset: selection.endOffset,
          type: "selection",
        })
      }
    }

    return map
  }, [highlightRanges, selection])

  const getHighlightsForBlock = useCallback(
    (messageIndex: number, partIndex: number) => rangeIndex.get(`${messageIndex}:${partIndex}`) ?? [],
    [rangeIndex],
  )

  const value = useMemo<TextSelectionContextValue>(
    () => ({ selection, getHighlightsForBlock }),
    [selection, getHighlightsForBlock],
  )

  return <TextSelectionContext.Provider value={value}>{children}</TextSelectionContext.Provider>
}
