export { generateBaselinePromptText } from "./alignment/baseline-prompt.ts"
export type {
  BaselineEvaluationExampleResult,
  BaselineEvaluationResult,
  CollectedEvaluationAlignmentExamples,
  GeneratedEvaluationDetails,
  GeneratedEvaluationDraft,
  HydratedEvaluationAlignmentExample,
  IncrementalEvaluationRefreshResult,
  LoadedEvaluationAlignmentState,
  PersistEvaluationAlignmentResult,
  WriteEvaluationAlignmentJobStatusInput,
} from "./alignment/types.ts"
export {
  ALIGNMENT_CURATED_DATASET_MAX_ROWS,
  ALIGNMENT_CURATED_DATASET_MIN_ROWS,
  ALIGNMENT_DEFAULT_SEED,
  ALIGNMENT_FULL_REOPTIMIZE_DEBOUNCE_MS,
  ALIGNMENT_MANUAL_REALIGNMENT_RATE_LIMIT_MS,
  ALIGNMENT_MCC_TOLERANCE,
  ALIGNMENT_METRIC_RECOMPUTE_DEBOUNCE_MS,
  ALIGNMENT_TRAIN_SPLIT,
  ALIGNMENT_VALIDATION_SPLIT,
  DEFAULT_EVALUATION_SAMPLING,
  EVALUATION_ALIGNMENT_JOB_KEY_PREFIX,
  EVALUATION_ALIGNMENT_JOB_STATUSES,
  EVALUATION_JOB_STATUS_TTL_SECONDS,
  EVALUATION_NAME_MAX_LENGTH,
  EVALUATION_TURNS,
} from "./constants.ts"
export {
  type ConfusionMatrix,
  confusionMatrixSchema,
  defaultEvaluationTrigger,
  type Evaluation,
  type EvaluationAlignment,
  type EvaluationAlignmentJobError,
  type EvaluationAlignmentJobId,
  type EvaluationAlignmentJobStatus,
  type EvaluationAlignmentJobStatusState,
  type EvaluationTrigger,
  type EvaluationTurn,
  emptyEvaluationAlignment,
  evaluationAlignmentJobErrorSchema,
  evaluationAlignmentJobIdSchema,
  evaluationAlignmentJobStatusSchema,
  evaluationAlignmentJobStatusStateSchema,
  evaluationAlignmentSchema,
  evaluationSchema,
  evaluationTriggerSchema,
  evaluationTurnSchema,
  isActiveEvaluation,
  isPausedEvaluation,
} from "./entities/evaluation.ts"
export {
  EvaluationDeletedError,
  EvaluationExecutionError,
  EvaluationManualRealignmentRateLimitedError,
  EvaluationNotFoundError,
  LiveEvaluationExecutionError,
  LiveEvaluationQueuePublishError,
} from "./errors.ts"
export {
  addConfusionMatrixObservation,
  applyIssueIgnoreToEvaluation,
  applyIssueResolutionToEvaluation,
  archiveEvaluation,
  buildEvaluationAlignmentJobStatus,
  buildLiveEvaluationExecuteScopeDedupeKey,
  buildLiveEvaluationExecuteTraceDedupeKey,
  type ConfusionMatrixObservation,
  calculateAccuracy,
  calculateF1,
  calculateMatthewsCorrelationCoefficient,
  calculateMatthewsCorrelationCoefficientDrop,
  calculatePrecision,
  calculateRecall,
  decideAlignmentRefreshStrategy,
  deriveConfusionMatrix,
  deriveEvaluationAlignmentMetrics,
  type EvaluationAlignmentMetrics,
  emptyConfusionMatrix,
  evaluationAlignmentJobStatusKey,
  getLiveEvaluationEligibility,
  getLiveEvaluationTurnScope,
  hasMatthewsCorrelationCoefficientDropExceededTolerance,
  isArchivedEvaluation,
  isDeletedEvaluation,
  mergeConfusionMatrices,
  parseStoredEvaluationAlignmentJobStatus,
  shouldSampleLiveEvaluation,
  softDeleteEvaluation,
  toLiveEvaluationDebounceMs,
  totalConfusionMatrixObservations,
  truncateEvaluationName,
  unarchiveEvaluation,
} from "./helpers.ts"
export {
  DEFAULT_ALIGNMENT_EXAMPLE_LIMIT,
  type EvaluationAlignmentExample,
  type EvaluationAlignmentExampleLabel,
  EvaluationAlignmentExamplesRepository,
  type EvaluationAlignmentNegativePriority,
  evaluationAlignmentExampleLabelSchema,
  evaluationAlignmentExampleSchema,
  evaluationAlignmentNegativePrioritySchema,
  type ListEvaluationAlignmentExamplesInput,
  type ListNegativeEvaluationAlignmentExamplesInput,
} from "./ports/evaluation-alignment-examples-repository.ts"
export {
  type EvaluationIssue,
  EvaluationIssueRepository,
} from "./ports/evaluation-issue-repository.ts"
export {
  type EvaluationListLifecycle,
  type EvaluationListOptions,
  type EvaluationListPage,
  EvaluationRepository,
  type EvaluationRepositoryShape,
  evaluationListLifecycleSchema,
} from "./ports/evaluation-repository.ts"
export {
  LiveEvaluationQueuePublisher,
  type LiveEvaluationQueuePublisherShape,
  type PublishLiveEvaluationExecuteInput,
} from "./ports/live-evaluation-queue-publisher.ts"
export {
  EVALUATION_CONVERSATION_PLACEHOLDER,
  EVALUATION_SCRIPT_RUNTIME_MODEL,
  EVALUATION_SCRIPT_RUNTIME_SYSTEM_PROMPT,
  type EvaluationConversationMessage,
  type EvaluationExecutionResult,
  type EvaluationExecutionResultPayload,
  type EvaluationIssueContext,
  type EvaluationScriptExecution,
  type EvaluationScriptSchema,
  type ExecuteEvaluationScriptWithAIError,
  estimateEvaluationScriptCostMicrocents,
  evaluationExecutionResultPayloadSchema,
  evaluationExecutionResultSchema,
  evaluationIssueContextSchema,
  evaluationRuntimeZod,
  executeEvaluationScript,
  executeEvaluationScriptWithAI,
  extractPromptFromEvaluationScript,
  formatEvaluationConversationForPrompt,
  toEvaluationConversationMessages,
  toEvaluationExecutionResult,
  validateEvaluationScript,
  wrapPromptAsEvaluationScript,
} from "./runtime/evaluation-execution.ts"
export { collectAlignmentExamplesUseCase } from "./use-cases/alignment/collect-alignment-examples.ts"
export { evaluateBaselineDraftUseCase } from "./use-cases/alignment/evaluate-baseline-draft.ts"
export { evaluateDraftAgainstExamplesUseCase } from "./use-cases/alignment/evaluate-draft-against-examples.ts"
export { evaluateIncrementalDraftUseCase } from "./use-cases/alignment/evaluate-incremental-draft.ts"
export { generateBaselineDraftUseCase } from "./use-cases/alignment/generate-baseline-draft.ts"
export { loadAlignmentStateUseCase } from "./use-cases/alignment/load-alignment-state.ts"
export { persistAlignmentResultUseCase } from "./use-cases/alignment/persist-alignment-result.ts"
export {
  type EnqueueLiveEvaluationsError,
  type EnqueueLiveEvaluationsInput,
  type EnqueueLiveEvaluationsResult,
  type EnqueueLiveEvaluationsSummary,
  enqueueLiveEvaluationsUseCase,
} from "./use-cases/live/enqueue-live-evaluations.ts"
export {
  type ExecuteLiveEvaluationError,
  executeLiveEvaluationUseCase,
  type LiveEvaluationConversationInput,
  type LiveEvaluationExecutionInput,
  type LiveEvaluationExecutionResult,
  type LiveEvaluationIssueContext,
  type LiveEvaluationResultPayload,
  liveEvaluationConversationInputSchema,
  liveEvaluationExecutionInputSchema,
  liveEvaluationExecutionResultSchema,
  liveEvaluationIssueContextSchema,
  liveEvaluationResultPayloadSchema,
} from "./use-cases/live/execute-live-evaluation.ts"
export { evaluateOptimizationCandidate } from "./use-cases/optimization/evaluate-optimization-candidate.ts"
