name: latitude-llm
windows:
  - workspace: cd .
  - apps: pnpm dev --filter='./apps/*'
  - packages:
      layout: main-horizontal
      panes:
        - pnpm dev --filter='./packages/*'
        - cd apps/web && pnpm workers:watch
  - docker: docker compose up db redis mailpit --menu=false
  - studio: cd packages/core && pnpm db:studio
