name: latitude-llm
windows:
  - workspace: cd .
  - apps:
      layout: main-horizontal
      panes:
        - pnpm catchup && pnpm dev --filter='./apps/*'
  - docker: docker compose up db redis weaviate mailpit --menu=false
  - studio: cd packages/core && pnpm db:studio
