services:
  base-dev:
    image: latitude/base-dev
    build:
      context: .
      dockerfile: docker/Dockerfile.base.development
    profiles:
      - dev
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8090:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    profiles:
      - dev

  db:
    image: postgres:15.8
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - ./docker/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./docker/pgdata:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - '6379:6379'

  mailpit:
    image: axllent/mailpit
    ports:
      - 8025:8025
      - 1025:1025

  web:
    build:
      context: .
      dockerfile: apps/web/docker/Dockerfile.development
    env_file:
      - .env
      - .env.development
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`latitude.localhost`)"
      - "traefik.http.services.web.loadbalancer.server.port=8080"
    depends_on:
      - base-dev
      - db
      - redis
      - traefik
    profiles:
      - dev
    volumes:
      - ./apps/web:/app/apps/web:cached
      - ./packages:/app/packages:cached
      - ./tools:/app/tools:cached
      - web_node_modules:/app/apps/web/node_modules
      - core_node_modules:/app/packages/core/node_modules
      - compiler_node_modules:/app/packages/compiler/node_modules
      - webui_node_modules:/app/packages/web-ui/node_modules

  web-prod:
    build:
      platforms:
        - 'linux/amd64'
      context: .
      dockerfile: apps/web/docker/Dockerfile
      args:
        - BUILDING_CONTAINER=true
        - SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN
        - SENTRY_DSN=$SENTRY_DSN
        - SENTRY_ORG=$SENTRY_ORG
        - SENTRY_PROJECT=$SENTRY_PROJECT
        - SUPPORT_APP_ID=$SUPPORT_APP_ID
        - SUPPORT_APP_SECRET_KEY=$SUPPORT_APP_SECRET_KEY
    env_file:
      - .env
      - .env.production
    profiles: [ production ]
    ports:
      - '8080:8080'
    depends_on:
      - db
      - redis

  gateway:
    build:
      context: .
      dockerfile: apps/gateway/docker/Dockerfile.development
    env_file:
      - .env
      - .env.development
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gateway.rule=Host(`gateway.latitude.localhost`)"
      - "traefik.http.services.gateway.loadbalancer.server.port=8080"
    depends_on:
      - base-dev
      - db
      - redis
      - traefik
    profiles:
      - dev
    volumes:
      - ./apps/gateway:/app/apps/gateway:cached
      - ./packages:/app/packages:cached
      - ./tools:/app/tools:cached
      - gateway_node_modules:/app/apps/gateway/node_modules
      - packages_node_modules:/app/packages/node_modules
      - tools_node_modules:/app/tools/node_modules

  gateway-prod:
    build:
      platforms:
        - 'linux/amd64'
      context: .
      dockerfile: apps/gateway/docker/Dockerfile
    env_file:
      - .env
      - .env.production
    profiles: [ production ]
    ports:
      - '8081:8081'
    depends_on:
      - db
      - redis

  workers:
    build:
      context: .
      dockerfile: apps/workers/docker/Dockerfile.development
    env_file:
      - .env
      - .env.development
    depends_on:
      - base-dev
      - db
      - redis
    profiles:
      - dev
    volumes:
      - ./apps/workers:/app/apps/workers:cached
      - ./packages:/app/packages:cached
      - ./tools:/app/tools:cached
      - workers_node_modules:/app/apps/workers/node_modules
      - packages_node_modules:/app/packages/node_modules
      - tools_node_modules:/app/tools/node_modules

  workers-prod:
    build:
      platforms:
        - 'linux/amd64'
      context: .
      dockerfile: apps/workers/docker/Dockerfile
    env_file:
      - .env
      - .env.production
    profiles: [ production ]
    depends_on:
      - db
      - redis

# Define named volumes
volumes:
  web_node_modules:
  core_node_modules:
  compiler_node_modules:
  webui_node_modules:
  gateway_node_modules:
  workers_node_modules:
  packages_node_modules:
  tools_node_modules:
