packages:
  - 'apps/*'
  - 'packages/**'
  - '!packages/**/python'
  - 'tools/*'
  - '!examples/**'
catalog:
  ai: 5.0.44
  '@ai-sdk/anthropic': 2.0.17
  '@ai-sdk/deepseek': 1.0.17
  '@ai-sdk/google': 2.0.14
  '@ai-sdk/mistral': 2.0.14
  '@ai-sdk/openai': 2.0.30
  '@ai-sdk/openai-compatible': 1.0.17
  '@ai-sdk/perplexity': 2.0.9
  '@ai-sdk/xai': 2.0.18
  pg: 8.16.0
  drizzle-orm: 0.44.2
  drizzle-kit: 0.31.1
  dd-trace: 5.69.0
  promptl-ai: 0.10.0
  rosetta-ai: 1.3.1
  zod: 4.1.8
  react: 19.2.4
  react-dom: 19.2.4
  bullmq: 5.66.0
  ioredis: 5.8.2
  '@types/react': 19.2.10
  '@types/react-dom': 19.2.3
  '@types/node': 22.7.5
  '@opentelemetry/api': 1.9.0
  '@opentelemetry/core': 1.30.1
  '@opentelemetry/resources': 1.30.1
  '@opentelemetry/instrumentation': 0.57.2
  '@opentelemetry/sdk-trace-node': 1.30.1
  '@opentelemetry/context-async-hooks': 1.30.1
  '@opentelemetry/exporter-trace-otlp-http': 0.57.2
  '@opentelemetry/otlp-transformer': 0.57.2
  '@opentelemetry/baggage-span-processor': 0.3.1
  '@opentelemetry/semantic-conventions': 1.34.0
  '@datadog/datadog-ci': ^3.0.0
  'react-data-grid': 7.0.0-beta.51
