packages:
  - apps/*
  - packages/**
  - "!packages/telemetry/python/**"
  - infra

catalog:
  '@biomejs/biome': 2.4.6
  '@clickhouse/client': 1.17.0
  '@hono/node-server': 1.19.6
  '@opentelemetry/api': ^1.9.0
  '@paralleldrive/cuid2': 3.3.0
  '@temporalio/client': 1.15.0
  '@temporalio/worker': 1.15.0
  '@temporalio/workflow': 1.15.0
  '@types/node': 22.14.1
  '@types/pg': 8.16.0
  '@types/react': 19.2.14
  '@types/react-dom': 19.2.3
  '@vitejs/plugin-react': 5.1.4
  better-auth: 1.5.6
  bullmq: 5.28.2
  dotenv: 17.3.1
  drizzle-kit: 1.0.0-beta.15-859cf75
  drizzle-orm: 1.0.0-beta.20
  fast-json-stable-stringify: 2.1.0
  effect: 4.0.0-beta.1
  hono: 4.9.12
  ioredis: 5.8.2
  pg: 8.16.0
  react: 19.2.4
  react-dom: 19.2.4
  rosetta-ai: 2.0.0
  protobufjs: 7.5.4
  tsx: 4.21.0
  turbo: 2.5.8
  typescript: 5.8.3
  vite: 8.0.5
  vitest: 4.1.0
  zod: 4.3.6
  voyageai: 0.2.1
  weaviate-client: 3.11.0

ignoredBuiltDependencies:
  - '@prisma/engines'
  - msw
  - prisma
  - protobufjs

onlyBuiltDependencies:
  - '@biomejs/biome'
  - chdb
  - esbuild
