packages:
  - 'apps/*'
  - 'packages/**'
  - '!packages/**/python'
  - 'tools/*'
  - '!examples/**'
catalog:
  pg: 8.16.0
  drizzle-orm: 0.44.2
  drizzle-kit: 0.31.1
  dd-trace: 5.43.0
  promptl-ai: 0.7.5
  zod: 3.25.76
  '@opentelemetry/api': 1.9.0
  '@opentelemetry/core': 1.30.1
  '@opentelemetry/resources': 1.30.1
  '@opentelemetry/instrumentation': 0.57.2
  '@opentelemetry/sdk-trace-node': 1.30.1
  '@opentelemetry/context-async-hooks': 1.30.1
  '@opentelemetry/exporter-trace-otlp-http': 0.57.2
  '@opentelemetry/baggage-span-processor': 0.3.1
  '@opentelemetry/semantic-conventions': 1.34.0
  ai: 5.0.10
