packages:
  - "apps/*"
  - "packages/**"
catalog:
  "@clickhouse/client": 1.17.0
  "@biomejs/biome": 1.9.4
  "@hono/node-server": 1.19.6
  "@types/node": 22.14.1
  "@types/pg": 8.16.0
  bullmq: 5.66.0
  dotenv: 17.3.1
  drizzle-kit: 0.31.9
  drizzle-orm: 0.44.2
  effect: 3.17.4
  hono: 4.9.12
  ioredis: 5.8.2
  pg: 8.16.0
  solid-js: 1.9.10
  tsx: 4.20.6
  turbo: 2.5.8
  typescript: 5.8.3
  vite: 7.1.12
  vite-plugin-solid: 2.11.8
  vitest: 3.2.4
