packages:
  - 'apps/*'
  - 'packages/**'
  - '!packages/**/python'
  - 'tools/*'
  - '!examples/**'
catalog:
  pg: 8.16.0
  drizzle-orm: 0.44.2
  drizzle-kit: 0.31.1
  dd-trace: 5.43.0
  promptl-ai: 0.7.4
  zod: 3.24.2
