packages:
  - "apps/*"
  - "packages/**"
catalog:
  "@clickhouse/client": 1.17.0
  "@biomejs/biome": 1.9.4
  "@hono/node-server": 1.19.6
  "@tanstack/react-router": 1.163.2
  "@types/node": 22.14.1
  "@types/pg": 8.16.0
  "@types/react": 19.2.14
  "@types/react-dom": 19.2.3
  "@vitejs/plugin-react": 5.1.4
  better-auth: 1.2.7
  bullmq: 5.66.0
  dotenv: 17.3.1
  drizzle-kit: 0.31.9
  drizzle-orm: 0.44.2
  effect: 4.0.0-beta.0
  hono: 4.9.12
  ioredis: 5.8.2
  pg: 8.16.0
  react: 19.2.4
  react-dom: 19.2.4
  tsx: 4.20.6
  turbo: 2.5.8
  typescript: 5.8.3
  vite: 7.3.1
  vitest: 3.2.4
