// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as LatitudeApi from "../../../index.js";

export declare namespace MonitorsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class MonitorsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<MonitorsClient.Options>;

    constructor(options: MonitorsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Returns the project's monitors, system monitors first, then by most recent activity.
     *
     * @param {string} projectSlug - Project slug (human-readable identifier)
     * @param {LatitudeApi.MonitorsListRequest} request
     * @param {MonitorsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link LatitudeApi.BadRequestError}
     * @throws {@link LatitudeApi.UnauthorizedError}
     * @throws {@link LatitudeApi.NotFoundError}
     *
     * @example
     *     await client.monitors.list("projectSlug", {
     *         cursor: "cursor",
     *         limit: 1,
     *         search: "search"
     *     })
     */
    public list(
        projectSlug: string,
        request: LatitudeApi.MonitorsListRequest = {},
        requestOptions?: MonitorsClient.RequestOptions,
    ): core.HttpResponsePromise<LatitudeApi.PaginatedMonitors> {
        return core.HttpResponsePromise.fromPromise(this.__list(projectSlug, request, requestOptions));
    }

    private async __list(
        projectSlug: string,
        request: LatitudeApi.MonitorsListRequest = {},
        requestOptions?: MonitorsClient.RequestOptions,
    ): Promise<core.WithRawResponse<LatitudeApi.PaginatedMonitors>> {
        const { cursor, limit, search } = request;
        const _queryParams: Record<string, unknown> = {
            cursor,
            limit,
            search,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.LatitudeApiEnvironment.Production,
                `v1/projects/${core.url.encodePathParam(projectSlug)}/monitors`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as LatitudeApi.PaginatedMonitors, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new LatitudeApi.BadRequestError(
                        _response.error.body as LatitudeApi.Error_,
                        _response.rawResponse,
                    );
                case 401:
                    throw new LatitudeApi.UnauthorizedError(
                        _response.error.body as LatitudeApi.Error_,
                        _response.rawResponse,
                    );
                case 404:
                    throw new LatitudeApi.NotFoundError(
                        _response.error.body as LatitudeApi.Error_,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.LatitudeApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v1/projects/{projectSlug}/monitors",
        );
    }

    /**
     * Creates a monitor with one or more saved-search alerts. The slug is derived from `name`.
     *
     * @param {string} projectSlug - Project slug (human-readable identifier)
     * @param {LatitudeApi.CreateMonitorBody} request
     * @param {MonitorsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link LatitudeApi.BadRequestError}
     * @throws {@link LatitudeApi.UnauthorizedError}
     * @throws {@link LatitudeApi.NotFoundError}
     *
     * @example
     *     await client.monitors.create("projectSlug", {
     *         name: "name",
     *         alerts: [{
     *                 kind: "savedSearch.match",
     *                 source: {
     *                     type: "issue",
     *                     id: "id"
     *                 }
     *             }]
     *     })
     */
    public create(
        projectSlug: string,
        request: LatitudeApi.CreateMonitorBody,
        requestOptions?: MonitorsClient.RequestOptions,
    ): core.HttpResponsePromise<LatitudeApi.Monitor> {
        return core.HttpResponsePromise.fromPromise(this.__create(projectSlug, request, requestOptions));
    }

    private async __create(
        projectSlug: string,
        request: LatitudeApi.CreateMonitorBody,
        requestOptions?: MonitorsClient.RequestOptions,
    ): Promise<core.WithRawResponse<LatitudeApi.Monitor>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.LatitudeApiEnvironment.Production,
                `v1/projects/${core.url.encodePathParam(projectSlug)}/monitors`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as LatitudeApi.Monitor, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new LatitudeApi.BadRequestError(
                        _response.error.body as LatitudeApi.Error_,
                        _response.rawResponse,
                    );
                case 401:
                    throw new LatitudeApi.UnauthorizedError(
                        _response.error.body as LatitudeApi.Error_,
                        _response.rawResponse,
                    );
                case 404:
                    throw new LatitudeApi.NotFoundError(
                        _response.error.body as LatitudeApi.Error_,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.LatitudeApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/projects/{projectSlug}/monitors",
        );
    }

    /**
     * Returns a single monitor by slug.
     *
     * @param {string} projectSlug - Project slug (human-readable identifier)
     * @param {string} monitorSlug - Monitor slug (human-readable identifier within the project).
     * @param {MonitorsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link LatitudeApi.BadRequestError}
     * @throws {@link LatitudeApi.UnauthorizedError}
     * @throws {@link LatitudeApi.NotFoundError}
     *
     * @example
     *     await client.monitors.get("projectSlug", "monitorSlug")
     */
    public get(
        projectSlug: string,
        monitorSlug: string,
        requestOptions?: MonitorsClient.RequestOptions,
    ): core.HttpResponsePromise<LatitudeApi.Monitor> {
        return core.HttpResponsePromise.fromPromise(this.__get(projectSlug, monitorSlug, requestOptions));
    }

    private async __get(
        projectSlug: string,
        monitorSlug: string,
        requestOptions?: MonitorsClient.RequestOptions,
    ): Promise<core.WithRawResponse<LatitudeApi.Monitor>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.LatitudeApiEnvironment.Production,
                `v1/projects/${core.url.encodePathParam(projectSlug)}/monitors/${core.url.encodePathParam(monitorSlug)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as LatitudeApi.Monitor, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new LatitudeApi.BadRequestError(
                        _response.error.body as LatitudeApi.Error_,
                        _response.rawResponse,
                    );
                case 401:
                    throw new LatitudeApi.UnauthorizedError(
                        _response.error.body as LatitudeApi.Error_,
                        _response.rawResponse,
                    );
                case 404:
                    throw new LatitudeApi.NotFoundError(
                        _response.error.body as LatitudeApi.Error_,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.LatitudeApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v1/projects/{projectSlug}/monitors/{monitorSlug}",
        );
    }

    /**
     * Deletes a monitor and its alerts. System monitors cannot be deleted.
     *
     * @param {string} projectSlug - Project slug (human-readable identifier)
     * @param {string} monitorSlug - Monitor slug (human-readable identifier within the project).
     * @param {MonitorsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link LatitudeApi.UnauthorizedError}
     * @throws {@link LatitudeApi.NotFoundError}
     *
     * @example
     *     await client.monitors.delete("projectSlug", "monitorSlug")
     */
    public delete(
        projectSlug: string,
        monitorSlug: string,
        requestOptions?: MonitorsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__delete(projectSlug, monitorSlug, requestOptions));
    }

    private async __delete(
        projectSlug: string,
        monitorSlug: string,
        requestOptions?: MonitorsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.LatitudeApiEnvironment.Production,
                `v1/projects/${core.url.encodePathParam(projectSlug)}/monitors/${core.url.encodePathParam(monitorSlug)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new LatitudeApi.UnauthorizedError(
                        _response.error.body as LatitudeApi.Error_,
                        _response.rawResponse,
                    );
                case 404:
                    throw new LatitudeApi.NotFoundError(
                        _response.error.body as LatitudeApi.Error_,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.LatitudeApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/v1/projects/{projectSlug}/monitors/{monitorSlug}",
        );
    }

    /**
     * Updates a monitor's name and description. System monitors cannot be edited.
     *
     * @param {string} projectSlug - Project slug (human-readable identifier)
     * @param {string} monitorSlug - Monitor slug (human-readable identifier within the project).
     * @param {LatitudeApi.UpdateMonitorBody} request
     * @param {MonitorsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link LatitudeApi.BadRequestError}
     * @throws {@link LatitudeApi.UnauthorizedError}
     * @throws {@link LatitudeApi.ForbiddenError}
     * @throws {@link LatitudeApi.NotFoundError}
     *
     * @example
     *     await client.monitors.update("projectSlug", "monitorSlug")
     */
    public update(
        projectSlug: string,
        monitorSlug: string,
        request: LatitudeApi.UpdateMonitorBody = {},
        requestOptions?: MonitorsClient.RequestOptions,
    ): core.HttpResponsePromise<LatitudeApi.Monitor> {
        return core.HttpResponsePromise.fromPromise(this.__update(projectSlug, monitorSlug, request, requestOptions));
    }

    private async __update(
        projectSlug: string,
        monitorSlug: string,
        request: LatitudeApi.UpdateMonitorBody = {},
        requestOptions?: MonitorsClient.RequestOptions,
    ): Promise<core.WithRawResponse<LatitudeApi.Monitor>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.LatitudeApiEnvironment.Production,
                `v1/projects/${core.url.encodePathParam(projectSlug)}/monitors/${core.url.encodePathParam(monitorSlug)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as LatitudeApi.Monitor, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new LatitudeApi.BadRequestError(
                        _response.error.body as LatitudeApi.Error_,
                        _response.rawResponse,
                    );
                case 401:
                    throw new LatitudeApi.UnauthorizedError(
                        _response.error.body as LatitudeApi.Error_,
                        _response.rawResponse,
                    );
                case 403:
                    throw new LatitudeApi.ForbiddenError(
                        _response.error.body as LatitudeApi.Error_,
                        _response.rawResponse,
                    );
                case 404:
                    throw new LatitudeApi.NotFoundError(
                        _response.error.body as LatitudeApi.Error_,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.LatitudeApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PATCH",
            "/v1/projects/{projectSlug}/monitors/{monitorSlug}",
        );
    }

    /**
     * Returns the monitor's alerts.
     *
     * @param {string} projectSlug - Project slug (human-readable identifier)
     * @param {string} monitorSlug - Monitor slug (human-readable identifier within the project).
     * @param {MonitorsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link LatitudeApi.BadRequestError}
     * @throws {@link LatitudeApi.UnauthorizedError}
     * @throws {@link LatitudeApi.NotFoundError}
     *
     * @example
     *     await client.monitors.listAlerts("projectSlug", "monitorSlug")
     */
    public listAlerts(
        projectSlug: string,
        monitorSlug: string,
        requestOptions?: MonitorsClient.RequestOptions,
    ): core.HttpResponsePromise<LatitudeApi.MonitorAlertList> {
        return core.HttpResponsePromise.fromPromise(this.__listAlerts(projectSlug, monitorSlug, requestOptions));
    }

    private async __listAlerts(
        projectSlug: string,
        monitorSlug: string,
        requestOptions?: MonitorsClient.RequestOptions,
    ): Promise<core.WithRawResponse<LatitudeApi.MonitorAlertList>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.LatitudeApiEnvironment.Production,
                `v1/projects/${core.url.encodePathParam(projectSlug)}/monitors/${core.url.encodePathParam(monitorSlug)}/alerts`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as LatitudeApi.MonitorAlertList, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new LatitudeApi.BadRequestError(
                        _response.error.body as LatitudeApi.Error_,
                        _response.rawResponse,
                    );
                case 401:
                    throw new LatitudeApi.UnauthorizedError(
                        _response.error.body as LatitudeApi.Error_,
                        _response.rawResponse,
                    );
                case 404:
                    throw new LatitudeApi.NotFoundError(
                        _response.error.body as LatitudeApi.Error_,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.LatitudeApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v1/projects/{projectSlug}/monitors/{monitorSlug}/alerts",
        );
    }

    /**
     * Adds a saved-search alert to a monitor and returns the updated monitor. System monitors cannot gain alerts.
     *
     * @param {string} projectSlug - Project slug (human-readable identifier)
     * @param {string} monitorSlug - Monitor slug (human-readable identifier within the project).
     * @param {LatitudeApi.CreateMonitorAlertBody} request
     * @param {MonitorsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link LatitudeApi.BadRequestError}
     * @throws {@link LatitudeApi.UnauthorizedError}
     * @throws {@link LatitudeApi.ForbiddenError}
     * @throws {@link LatitudeApi.NotFoundError}
     *
     * @example
     *     await client.monitors.createAlert("projectSlug", "monitorSlug", {
     *         kind: "savedSearch.match",
     *         source: {
     *             type: "issue",
     *             id: "id"
     *         }
     *     })
     */
    public createAlert(
        projectSlug: string,
        monitorSlug: string,
        request: LatitudeApi.CreateMonitorAlertBody,
        requestOptions?: MonitorsClient.RequestOptions,
    ): core.HttpResponsePromise<LatitudeApi.Monitor> {
        return core.HttpResponsePromise.fromPromise(
            this.__createAlert(projectSlug, monitorSlug, request, requestOptions),
        );
    }

    private async __createAlert(
        projectSlug: string,
        monitorSlug: string,
        request: LatitudeApi.CreateMonitorAlertBody,
        requestOptions?: MonitorsClient.RequestOptions,
    ): Promise<core.WithRawResponse<LatitudeApi.Monitor>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.LatitudeApiEnvironment.Production,
                `v1/projects/${core.url.encodePathParam(projectSlug)}/monitors/${core.url.encodePathParam(monitorSlug)}/alerts`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as LatitudeApi.Monitor, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new LatitudeApi.BadRequestError(
                        _response.error.body as LatitudeApi.Error_,
                        _response.rawResponse,
                    );
                case 401:
                    throw new LatitudeApi.UnauthorizedError(
                        _response.error.body as LatitudeApi.Error_,
                        _response.rawResponse,
                    );
                case 403:
                    throw new LatitudeApi.ForbiddenError(
                        _response.error.body as LatitudeApi.Error_,
                        _response.rawResponse,
                    );
                case 404:
                    throw new LatitudeApi.NotFoundError(
                        _response.error.body as LatitudeApi.Error_,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.LatitudeApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/projects/{projectSlug}/monitors/{monitorSlug}/alerts",
        );
    }

    /**
     * Returns a single monitor alert by id.
     *
     * @param {string} projectSlug - Project slug (human-readable identifier)
     * @param {string} monitorSlug - Monitor slug (human-readable identifier within the project).
     * @param {string} alertId - Monitor-alert identifier.
     * @param {MonitorsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link LatitudeApi.BadRequestError}
     * @throws {@link LatitudeApi.UnauthorizedError}
     * @throws {@link LatitudeApi.NotFoundError}
     *
     * @example
     *     await client.monitors.getAlert("projectSlug", "monitorSlug", "alertId")
     */
    public getAlert(
        projectSlug: string,
        monitorSlug: string,
        alertId: string,
        requestOptions?: MonitorsClient.RequestOptions,
    ): core.HttpResponsePromise<LatitudeApi.MonitorAlert> {
        return core.HttpResponsePromise.fromPromise(this.__getAlert(projectSlug, monitorSlug, alertId, requestOptions));
    }

    private async __getAlert(
        projectSlug: string,
        monitorSlug: string,
        alertId: string,
        requestOptions?: MonitorsClient.RequestOptions,
    ): Promise<core.WithRawResponse<LatitudeApi.MonitorAlert>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.LatitudeApiEnvironment.Production,
                `v1/projects/${core.url.encodePathParam(projectSlug)}/monitors/${core.url.encodePathParam(monitorSlug)}/alerts/${core.url.encodePathParam(alertId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as LatitudeApi.MonitorAlert, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new LatitudeApi.BadRequestError(
                        _response.error.body as LatitudeApi.Error_,
                        _response.rawResponse,
                    );
                case 401:
                    throw new LatitudeApi.UnauthorizedError(
                        _response.error.body as LatitudeApi.Error_,
                        _response.rawResponse,
                    );
                case 404:
                    throw new LatitudeApi.NotFoundError(
                        _response.error.body as LatitudeApi.Error_,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.LatitudeApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v1/projects/{projectSlug}/monitors/{monitorSlug}/alerts/{alertId}",
        );
    }

    /**
     * Removes an alert from a monitor. A monitor must keep at least one alert; system monitors' alerts cannot be removed.
     *
     * @param {string} projectSlug - Project slug (human-readable identifier)
     * @param {string} monitorSlug - Monitor slug (human-readable identifier within the project).
     * @param {string} alertId - Monitor-alert identifier.
     * @param {MonitorsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link LatitudeApi.UnauthorizedError}
     * @throws {@link LatitudeApi.NotFoundError}
     *
     * @example
     *     await client.monitors.deleteAlert("projectSlug", "monitorSlug", "alertId")
     */
    public deleteAlert(
        projectSlug: string,
        monitorSlug: string,
        alertId: string,
        requestOptions?: MonitorsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(
            this.__deleteAlert(projectSlug, monitorSlug, alertId, requestOptions),
        );
    }

    private async __deleteAlert(
        projectSlug: string,
        monitorSlug: string,
        alertId: string,
        requestOptions?: MonitorsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.LatitudeApiEnvironment.Production,
                `v1/projects/${core.url.encodePathParam(projectSlug)}/monitors/${core.url.encodePathParam(monitorSlug)}/alerts/${core.url.encodePathParam(alertId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new LatitudeApi.UnauthorizedError(
                        _response.error.body as LatitudeApi.Error_,
                        _response.rawResponse,
                    );
                case 404:
                    throw new LatitudeApi.NotFoundError(
                        _response.error.body as LatitudeApi.Error_,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.LatitudeApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/v1/projects/{projectSlug}/monitors/{monitorSlug}/alerts/{alertId}",
        );
    }

    /**
     * Updates an alert and returns the updated monitor. On system monitors only the condition may change; on your own monitors any field may.
     *
     * @param {string} projectSlug - Project slug (human-readable identifier)
     * @param {string} monitorSlug - Monitor slug (human-readable identifier within the project).
     * @param {string} alertId - Monitor-alert identifier.
     * @param {LatitudeApi.UpdateMonitorAlertBody} request
     * @param {MonitorsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link LatitudeApi.BadRequestError}
     * @throws {@link LatitudeApi.UnauthorizedError}
     * @throws {@link LatitudeApi.ForbiddenError}
     * @throws {@link LatitudeApi.NotFoundError}
     *
     * @example
     *     await client.monitors.updateAlert("projectSlug", "monitorSlug", "alertId")
     */
    public updateAlert(
        projectSlug: string,
        monitorSlug: string,
        alertId: string,
        request: LatitudeApi.UpdateMonitorAlertBody = {},
        requestOptions?: MonitorsClient.RequestOptions,
    ): core.HttpResponsePromise<LatitudeApi.Monitor> {
        return core.HttpResponsePromise.fromPromise(
            this.__updateAlert(projectSlug, monitorSlug, alertId, request, requestOptions),
        );
    }

    private async __updateAlert(
        projectSlug: string,
        monitorSlug: string,
        alertId: string,
        request: LatitudeApi.UpdateMonitorAlertBody = {},
        requestOptions?: MonitorsClient.RequestOptions,
    ): Promise<core.WithRawResponse<LatitudeApi.Monitor>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.LatitudeApiEnvironment.Production,
                `v1/projects/${core.url.encodePathParam(projectSlug)}/monitors/${core.url.encodePathParam(monitorSlug)}/alerts/${core.url.encodePathParam(alertId)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as LatitudeApi.Monitor, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new LatitudeApi.BadRequestError(
                        _response.error.body as LatitudeApi.Error_,
                        _response.rawResponse,
                    );
                case 401:
                    throw new LatitudeApi.UnauthorizedError(
                        _response.error.body as LatitudeApi.Error_,
                        _response.rawResponse,
                    );
                case 403:
                    throw new LatitudeApi.ForbiddenError(
                        _response.error.body as LatitudeApi.Error_,
                        _response.rawResponse,
                    );
                case 404:
                    throw new LatitudeApi.NotFoundError(
                        _response.error.body as LatitudeApi.Error_,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.LatitudeApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PATCH",
            "/v1/projects/{projectSlug}/monitors/{monitorSlug}/alerts/{alertId}",
        );
    }

    /**
     * Returns the incidents opened by a monitor, most recent first. Each item's `notified` flag shows whether it triggered a notification.
     *
     * @param {string} projectSlug - Project slug (human-readable identifier)
     * @param {string} monitorSlug - Monitor slug (human-readable identifier within the project).
     * @param {LatitudeApi.MonitorsListIncidentsRequest} request
     * @param {MonitorsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link LatitudeApi.BadRequestError}
     * @throws {@link LatitudeApi.UnauthorizedError}
     * @throws {@link LatitudeApi.NotFoundError}
     *
     * @example
     *     await client.monitors.listIncidents("projectSlug", "monitorSlug", {
     *         cursor: "cursor",
     *         limit: 1
     *     })
     */
    public listIncidents(
        projectSlug: string,
        monitorSlug: string,
        request: LatitudeApi.MonitorsListIncidentsRequest = {},
        requestOptions?: MonitorsClient.RequestOptions,
    ): core.HttpResponsePromise<LatitudeApi.PaginatedMonitorIncidents> {
        return core.HttpResponsePromise.fromPromise(
            this.__listIncidents(projectSlug, monitorSlug, request, requestOptions),
        );
    }

    private async __listIncidents(
        projectSlug: string,
        monitorSlug: string,
        request: LatitudeApi.MonitorsListIncidentsRequest = {},
        requestOptions?: MonitorsClient.RequestOptions,
    ): Promise<core.WithRawResponse<LatitudeApi.PaginatedMonitorIncidents>> {
        const { cursor, limit } = request;
        const _queryParams: Record<string, unknown> = {
            cursor,
            limit,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.LatitudeApiEnvironment.Production,
                `v1/projects/${core.url.encodePathParam(projectSlug)}/monitors/${core.url.encodePathParam(monitorSlug)}/incidents`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as LatitudeApi.PaginatedMonitorIncidents,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new LatitudeApi.BadRequestError(
                        _response.error.body as LatitudeApi.Error_,
                        _response.rawResponse,
                    );
                case 401:
                    throw new LatitudeApi.UnauthorizedError(
                        _response.error.body as LatitudeApi.Error_,
                        _response.rawResponse,
                    );
                case 404:
                    throw new LatitudeApi.NotFoundError(
                        _response.error.body as LatitudeApi.Error_,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.LatitudeApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v1/projects/{projectSlug}/monitors/{monitorSlug}/incidents",
        );
    }

    /**
     * Mutes a monitor so its incidents stop sending notifications. Allowed on all monitors.
     *
     * @param {string} projectSlug - Project slug (human-readable identifier)
     * @param {string} monitorSlug - Monitor slug (human-readable identifier within the project).
     * @param {MonitorsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link LatitudeApi.BadRequestError}
     * @throws {@link LatitudeApi.UnauthorizedError}
     * @throws {@link LatitudeApi.NotFoundError}
     *
     * @example
     *     await client.monitors.mute("projectSlug", "monitorSlug")
     */
    public mute(
        projectSlug: string,
        monitorSlug: string,
        requestOptions?: MonitorsClient.RequestOptions,
    ): core.HttpResponsePromise<LatitudeApi.Monitor> {
        return core.HttpResponsePromise.fromPromise(this.__mute(projectSlug, monitorSlug, requestOptions));
    }

    private async __mute(
        projectSlug: string,
        monitorSlug: string,
        requestOptions?: MonitorsClient.RequestOptions,
    ): Promise<core.WithRawResponse<LatitudeApi.Monitor>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.LatitudeApiEnvironment.Production,
                `v1/projects/${core.url.encodePathParam(projectSlug)}/monitors/${core.url.encodePathParam(monitorSlug)}/mute`,
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as LatitudeApi.Monitor, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new LatitudeApi.BadRequestError(
                        _response.error.body as LatitudeApi.Error_,
                        _response.rawResponse,
                    );
                case 401:
                    throw new LatitudeApi.UnauthorizedError(
                        _response.error.body as LatitudeApi.Error_,
                        _response.rawResponse,
                    );
                case 404:
                    throw new LatitudeApi.NotFoundError(
                        _response.error.body as LatitudeApi.Error_,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.LatitudeApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/projects/{projectSlug}/monitors/{monitorSlug}/mute",
        );
    }

    /**
     * Lifts a monitor's mute so its incidents notify again.
     *
     * @param {string} projectSlug - Project slug (human-readable identifier)
     * @param {string} monitorSlug - Monitor slug (human-readable identifier within the project).
     * @param {MonitorsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link LatitudeApi.BadRequestError}
     * @throws {@link LatitudeApi.UnauthorizedError}
     * @throws {@link LatitudeApi.NotFoundError}
     *
     * @example
     *     await client.monitors.unmute("projectSlug", "monitorSlug")
     */
    public unmute(
        projectSlug: string,
        monitorSlug: string,
        requestOptions?: MonitorsClient.RequestOptions,
    ): core.HttpResponsePromise<LatitudeApi.Monitor> {
        return core.HttpResponsePromise.fromPromise(this.__unmute(projectSlug, monitorSlug, requestOptions));
    }

    private async __unmute(
        projectSlug: string,
        monitorSlug: string,
        requestOptions?: MonitorsClient.RequestOptions,
    ): Promise<core.WithRawResponse<LatitudeApi.Monitor>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.LatitudeApiEnvironment.Production,
                `v1/projects/${core.url.encodePathParam(projectSlug)}/monitors/${core.url.encodePathParam(monitorSlug)}/unmute`,
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as LatitudeApi.Monitor, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new LatitudeApi.BadRequestError(
                        _response.error.body as LatitudeApi.Error_,
                        _response.rawResponse,
                    );
                case 401:
                    throw new LatitudeApi.UnauthorizedError(
                        _response.error.body as LatitudeApi.Error_,
                        _response.rawResponse,
                    );
                case 404:
                    throw new LatitudeApi.NotFoundError(
                        _response.error.body as LatitudeApi.Error_,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.LatitudeApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/projects/{projectSlug}/monitors/{monitorSlug}/unmute",
        );
    }
}
