# This file was auto-generated by Fern from our API Definition.

import typing

from .alert_condition_kind import AlertConditionKind
from .alert_condition_window import AlertConditionWindow
from .alert_condition_zero import AlertConditionZero

AlertCondition = typing.Union[AlertConditionZero, AlertConditionWindow, AlertConditionKind]
