# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from .alert_baseline import AlertBaseline


class AlertEscalatingConditionThreshold_Absolute(UniversalBaseModel):
    """
    How the metric is compared when threshold-based.
    """

    mode: typing.Literal["absolute"] = "absolute"
    value: float

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class AlertEscalatingConditionThreshold_Multiplier(UniversalBaseModel):
    """
    How the metric is compared when threshold-based.
    """

    mode: typing.Literal["multiplier"] = "multiplier"
    factor: float
    baseline: AlertBaseline

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class AlertEscalatingConditionThreshold_Expected(UniversalBaseModel):
    """
    How the metric is compared when threshold-based.
    """

    mode: typing.Literal["expected"] = "expected"
    sensitivity: typing.Optional[int] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


AlertEscalatingConditionThreshold = typing_extensions.Annotated[
    typing.Union[
        AlertEscalatingConditionThreshold_Absolute,
        AlertEscalatingConditionThreshold_Multiplier,
        AlertEscalatingConditionThreshold_Expected,
    ],
    pydantic.Field(discriminator="mode"),
]
