# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .alert_baseline_kind import AlertBaselineKind
from .alert_duration import AlertDuration


class AlertBaseline(UniversalBaseModel):
    """
    Fixed-window baseline the current rate is compared against.
    """

    kind: AlertBaselineKind = pydantic.Field()
    """
    How the comparison rate is computed. `average` is the rolling rate over the last `lookback`; `period` is the equal-length window immediately before it (e.g. `lookback` of 1 day compares against yesterday) for daily/weekly seasonality.
    """

    lookback: AlertDuration

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
