# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .analytics_query_traces_order_by_by import AnalyticsQueryTracesOrderByBy
from .analytics_query_traces_order_by_direction import AnalyticsQueryTracesOrderByDirection


class AnalyticsQueryTracesOrderBy(UniversalBaseModel):
    """
    Sort for breakdown results. Defaults to value-desc.
    """

    by: typing.Optional[AnalyticsQueryTracesOrderByBy] = None
    direction: typing.Optional[AnalyticsQueryTracesOrderByDirection] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
