# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .analytics_query_spans_metric_median_field import AnalyticsQuerySpansMetricMedianField


class AnalyticsQuerySpansMetricMedian(UniversalBaseModel):
    field: AnalyticsQuerySpansMetricMedianField

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
