# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .analytics_query_sessions_metric_p_95_field import AnalyticsQuerySessionsMetricP95Field


class AnalyticsQuerySessionsMetricP95(UniversalBaseModel):
    field: AnalyticsQuerySessionsMetricP95Field

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
