# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .create_monitor_body_threshold_condition import CreateMonitorBodyThresholdCondition
from .create_monitor_body_threshold_metric import CreateMonitorBodyThresholdMetric
from .create_monitor_body_threshold_severity import CreateMonitorBodyThresholdSeverity
from .create_monitor_body_threshold_target import CreateMonitorBodyThresholdTarget


class CreateMonitorBodyThreshold(UniversalBaseModel):
    name: str = pydantic.Field()
    """
    Human-readable name. Used to derive the slug.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional free-form description.
    """

    target: CreateMonitorBodyThresholdTarget = pydantic.Field()
    """
    Entity or filter set watched by the monitor.
    """

    severity: CreateMonitorBodyThresholdSeverity = pydantic.Field()
    """
    Severity assigned to incidents opened by this monitor.
    """

    metric: typing.Optional[CreateMonitorBodyThresholdMetric] = pydantic.Field(default=None)
    """
    Metric evaluated by the monitor rule.
    """

    condition: CreateMonitorBodyThresholdCondition = pydantic.Field()
    """
    Threshold condition that opens point incidents.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
