# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .alert_metric_threshold import AlertMetricThreshold
from .create_monitor_body_threshold_condition_direction import CreateMonitorBodyThresholdConditionDirection
from .create_monitor_body_threshold_condition_trigger import CreateMonitorBodyThresholdConditionTrigger
from .monitor_metric import MonitorMetric


class CreateMonitorBodyThresholdCondition(UniversalBaseModel):
    """
    Threshold condition that opens point incidents.
    """

    trigger: CreateMonitorBodyThresholdConditionTrigger = pydantic.Field()
    """
    Opens once the measured value crosses the threshold.
    """

    metric: MonitorMetric
    threshold: AlertMetricThreshold
    direction: typing.Optional[CreateMonitorBodyThresholdConditionDirection] = pydantic.Field(default=None)
    """
    Direction that opens the incident. Defaults to `above` when omitted.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
