# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from .create_monitor_body_threshold_target_metric_avg_field import CreateMonitorBodyThresholdTargetMetricAvgField
from .create_monitor_body_threshold_target_metric_max_field import CreateMonitorBodyThresholdTargetMetricMaxField
from .create_monitor_body_threshold_target_metric_median_field import CreateMonitorBodyThresholdTargetMetricMedianField
from .create_monitor_body_threshold_target_metric_min_field import CreateMonitorBodyThresholdTargetMetricMinField
from .create_monitor_body_threshold_target_metric_sum_field import CreateMonitorBodyThresholdTargetMetricSumField


class CreateMonitorBodyThresholdTargetMetric_Count(UniversalBaseModel):
    """
    Default metric evaluated for this target.
    """

    kind: typing.Literal["count"] = "count"

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class CreateMonitorBodyThresholdTargetMetric_ErrorRate(UniversalBaseModel):
    """
    Default metric evaluated for this target.
    """

    kind: typing.Literal["errorRate"] = "errorRate"

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class CreateMonitorBodyThresholdTargetMetric_CacheHitRate(UniversalBaseModel):
    """
    Default metric evaluated for this target.
    """

    kind: typing.Literal["cacheHitRate"] = "cacheHitRate"

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class CreateMonitorBodyThresholdTargetMetric_Avg(UniversalBaseModel):
    """
    Default metric evaluated for this target.
    """

    kind: typing.Literal["avg"] = "avg"
    field: CreateMonitorBodyThresholdTargetMetricAvgField

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class CreateMonitorBodyThresholdTargetMetric_Sum(UniversalBaseModel):
    """
    Default metric evaluated for this target.
    """

    kind: typing.Literal["sum"] = "sum"
    field: CreateMonitorBodyThresholdTargetMetricSumField

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class CreateMonitorBodyThresholdTargetMetric_Min(UniversalBaseModel):
    """
    Default metric evaluated for this target.
    """

    kind: typing.Literal["min"] = "min"
    field: CreateMonitorBodyThresholdTargetMetricMinField

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class CreateMonitorBodyThresholdTargetMetric_Max(UniversalBaseModel):
    """
    Default metric evaluated for this target.
    """

    kind: typing.Literal["max"] = "max"
    field: CreateMonitorBodyThresholdTargetMetricMaxField

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class CreateMonitorBodyThresholdTargetMetric_Median(UniversalBaseModel):
    """
    Default metric evaluated for this target.
    """

    kind: typing.Literal["median"] = "median"
    field: CreateMonitorBodyThresholdTargetMetricMedianField

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


CreateMonitorBodyThresholdTargetMetric = typing_extensions.Annotated[
    typing.Union[
        CreateMonitorBodyThresholdTargetMetric_Count,
        CreateMonitorBodyThresholdTargetMetric_ErrorRate,
        CreateMonitorBodyThresholdTargetMetric_CacheHitRate,
        CreateMonitorBodyThresholdTargetMetric_Avg,
        CreateMonitorBodyThresholdTargetMetric_Sum,
        CreateMonitorBodyThresholdTargetMetric_Min,
        CreateMonitorBodyThresholdTargetMetric_Max,
        CreateMonitorBodyThresholdTargetMetric_Median,
    ],
    pydantic.Field(discriminator="kind"),
]
