# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from .create_monitor_body_threshold_metric_avg_field import CreateMonitorBodyThresholdMetricAvgField
from .create_monitor_body_threshold_metric_max_field import CreateMonitorBodyThresholdMetricMaxField
from .create_monitor_body_threshold_metric_median_field import CreateMonitorBodyThresholdMetricMedianField
from .create_monitor_body_threshold_metric_min_field import CreateMonitorBodyThresholdMetricMinField
from .create_monitor_body_threshold_metric_sum_field import CreateMonitorBodyThresholdMetricSumField


class CreateMonitorBodyThresholdMetric_Count(UniversalBaseModel):
    """
    Metric evaluated by the monitor rule.
    """

    kind: typing.Literal["count"] = "count"

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class CreateMonitorBodyThresholdMetric_ErrorRate(UniversalBaseModel):
    """
    Metric evaluated by the monitor rule.
    """

    kind: typing.Literal["errorRate"] = "errorRate"

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class CreateMonitorBodyThresholdMetric_CacheHitRate(UniversalBaseModel):
    """
    Metric evaluated by the monitor rule.
    """

    kind: typing.Literal["cacheHitRate"] = "cacheHitRate"

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class CreateMonitorBodyThresholdMetric_Avg(UniversalBaseModel):
    """
    Metric evaluated by the monitor rule.
    """

    kind: typing.Literal["avg"] = "avg"
    field: CreateMonitorBodyThresholdMetricAvgField

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class CreateMonitorBodyThresholdMetric_Sum(UniversalBaseModel):
    """
    Metric evaluated by the monitor rule.
    """

    kind: typing.Literal["sum"] = "sum"
    field: CreateMonitorBodyThresholdMetricSumField

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class CreateMonitorBodyThresholdMetric_Min(UniversalBaseModel):
    """
    Metric evaluated by the monitor rule.
    """

    kind: typing.Literal["min"] = "min"
    field: CreateMonitorBodyThresholdMetricMinField

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class CreateMonitorBodyThresholdMetric_Max(UniversalBaseModel):
    """
    Metric evaluated by the monitor rule.
    """

    kind: typing.Literal["max"] = "max"
    field: CreateMonitorBodyThresholdMetricMaxField

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class CreateMonitorBodyThresholdMetric_Median(UniversalBaseModel):
    """
    Metric evaluated by the monitor rule.
    """

    kind: typing.Literal["median"] = "median"
    field: CreateMonitorBodyThresholdMetricMedianField

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


CreateMonitorBodyThresholdMetric = typing_extensions.Annotated[
    typing.Union[
        CreateMonitorBodyThresholdMetric_Count,
        CreateMonitorBodyThresholdMetric_ErrorRate,
        CreateMonitorBodyThresholdMetric_CacheHitRate,
        CreateMonitorBodyThresholdMetric_Avg,
        CreateMonitorBodyThresholdMetric_Sum,
        CreateMonitorBodyThresholdMetric_Min,
        CreateMonitorBodyThresholdMetric_Max,
        CreateMonitorBodyThresholdMetric_Median,
    ],
    pydantic.Field(discriminator="kind"),
]
