# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .create_monitor_body_escalating_condition_direction import CreateMonitorBodyEscalatingConditionDirection
from .create_monitor_body_escalating_condition_threshold import CreateMonitorBodyEscalatingConditionThreshold
from .create_monitor_body_escalating_condition_trigger import CreateMonitorBodyEscalatingConditionTrigger
from .create_monitor_body_escalating_condition_window import CreateMonitorBodyEscalatingConditionWindow
from .monitor_metric import MonitorMetric


class CreateMonitorBodyEscalatingCondition(UniversalBaseModel):
    """
    Escalating condition that opens sustained incidents.
    """

    trigger: CreateMonitorBodyEscalatingConditionTrigger = pydantic.Field()
    """
    Opens when the monitor target is escalating or sustained.
    """

    metric: MonitorMetric
    threshold: typing.Optional[CreateMonitorBodyEscalatingConditionThreshold] = pydantic.Field(default=None)
    """
    How the metric is compared when threshold-based.
    """

    direction: typing.Optional[CreateMonitorBodyEscalatingConditionDirection] = pydantic.Field(default=None)
    """
    Direction that opens the incident. Defaults to `above` when omitted.
    """

    sensitivity: typing.Optional[int] = pydantic.Field(default=None)
    """
    Detector sensitivity from 1 (noisiest) to 6 (strictest). Defaults to 3 when omitted.
    """

    window: CreateMonitorBodyEscalatingConditionWindow = pydantic.Field()
    """
    Sustained-condition window.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
