# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .create_monitor_alert_body_condition import CreateMonitorAlertBodyCondition
from .create_monitor_alert_body_kind import CreateMonitorAlertBodyKind
from .create_monitor_alert_body_severity import CreateMonitorAlertBodySeverity
from .create_monitor_alert_body_source import CreateMonitorAlertBodySource


class CreateMonitorAlertBody(UniversalBaseModel):
    kind: CreateMonitorAlertBodyKind = pydantic.Field()
    """
    What the alert fires on. `savedSearch.threshold` and `savedSearch.escalating` need a matching `condition`.
    """

    source: CreateMonitorAlertBodySource = pydantic.Field()
    """
    The saved search this alert watches.
    """

    condition: typing.Optional[CreateMonitorAlertBodyCondition] = pydantic.Field(default=None)
    """
    Kind-specific configuration. Required for `savedSearch.threshold` and `savedSearch.escalating`; omit for `savedSearch.match`.
    """

    severity: typing.Optional[CreateMonitorAlertBodySeverity] = pydantic.Field(default=None)
    """
    Severity of incidents this alert opens. Defaults per kind when omitted.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
