# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .alert_escalating_condition import AlertEscalatingCondition
from .alert_threshold_condition import AlertThresholdCondition
from .create_monitor_body_escalating_severity import CreateMonitorBodyEscalatingSeverity
from .create_monitor_body_match_severity import CreateMonitorBodyMatchSeverity
from .create_monitor_body_threshold_severity import CreateMonitorBodyThresholdSeverity
from .monitor_metric import MonitorMetric
from .monitor_target import MonitorTarget


class CreateMonitorBody_Match(UniversalBaseModel):
    trigger: typing.Literal["match"] = "match"
    name: str
    description: typing.Optional[str] = None
    target: MonitorTarget
    severity: CreateMonitorBodyMatchSeverity
    metric: typing.Optional[MonitorMetric] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class CreateMonitorBody_Threshold(UniversalBaseModel):
    trigger: typing.Literal["threshold"] = "threshold"
    name: str
    description: typing.Optional[str] = None
    target: MonitorTarget
    severity: CreateMonitorBodyThresholdSeverity
    metric: typing.Optional[MonitorMetric] = None
    condition: AlertThresholdCondition

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class CreateMonitorBody_Escalating(UniversalBaseModel):
    trigger: typing.Literal["escalating"] = "escalating"
    name: str
    description: typing.Optional[str] = None
    target: MonitorTarget
    severity: CreateMonitorBodyEscalatingSeverity
    metric: typing.Optional[MonitorMetric] = None
    condition: AlertEscalatingCondition

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


CreateMonitorBody = typing.Union[CreateMonitorBody_Match, CreateMonitorBody_Threshold, CreateMonitorBody_Escalating]
