# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .create_monitor_body_match_target_metric_max_field import CreateMonitorBodyMatchTargetMetricMaxField


class CreateMonitorBodyMatchTargetMetricMax(UniversalBaseModel):
    field: CreateMonitorBodyMatchTargetMetricMaxField = pydantic.Field()
    """
    Numeric field to aggregate.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
