# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel


class ExportTracesResponse(UniversalBaseModel):
    status: typing.Literal["queued"] = pydantic.Field(default="queued")
    """
    Always `"queued"`. The CSV is built asynchronously and emailed to `recipient` when ready.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
