# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel


class HealthResponse(UniversalBaseModel):
    service: typing.Literal["api"] = "api"
    status: typing.Literal["ok"] = "ok"

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
