# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata
from .incident_condition import IncidentCondition
from .incident_severity import IncidentSeverity
from .incident_source_type import IncidentSourceType


class Incident(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Stable incident identifier.
    """

    organization_id: typing_extensions.Annotated[str, FieldMetadata(alias="organizationId")] = pydantic.Field()
    """
    Organization that owns this incident.
    """

    project_id: typing_extensions.Annotated[str, FieldMetadata(alias="projectId")] = pydantic.Field()
    """
    Project this incident belongs to.
    """

    source_type: typing_extensions.Annotated[IncidentSourceType, FieldMetadata(alias="sourceType")] = pydantic.Field()
    """
    Kind of entity that triggered the incident: `signal` or `monitor`.
    """

    source_id: typing_extensions.Annotated[str, FieldMetadata(alias="sourceId")] = pydantic.Field()
    """
    Id of the entity that triggered the incident (matches `sourceType`).
    """

    severity: IncidentSeverity = pydantic.Field()
    """
    Severity bucket assigned to the incident: `low`, `medium`, or `high`.
    """

    started_at: typing_extensions.Annotated[str, FieldMetadata(alias="startedAt")] = pydantic.Field()
    """
    ISO-8601 timestamp at which the incident opened.
    """

    ended_at: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="endedAt")] = pydantic.Field(
        default=None
    )
    """
    ISO-8601 timestamp at which the incident closed, or `null` if still open.
    """

    created_at: typing_extensions.Annotated[str, FieldMetadata(alias="createdAt")] = pydantic.Field()
    """
    ISO-8601 timestamp at which the incident row was created.
    """

    condition: typing.Optional[IncidentCondition] = pydantic.Field(default=None)
    """
    The monitor rule configuration when the incident opened, or `null` for signal incidents and match monitors.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
