# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata


class IncidentNotificationsSetting(UniversalBaseModel):
    """
    Per-alert-kind opt-out for incident notifications.
    """

    issue_new: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="issue.new")] = pydantic.Field(
        default=None
    )
    """
    Send a notification when a new signal is discovered. Defaults to `true` when omitted.
    """

    issue_regressed: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="issue.regressed")] = (
        pydantic.Field(default=None)
    )
    """
    Send a notification when a previously-resolved signal regresses. Defaults to `true` when omitted.
    """

    issue_escalating: typing_extensions.Annotated[typing.Optional[bool], FieldMetadata(alias="issue.escalating")] = (
        pydantic.Field(default=None)
    )
    """
    Send a notification when an active signal is escalating in volume or severity. Defaults to `true` when omitted.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
