# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata
from .alert_condition import AlertCondition
from .incident_kind import IncidentKind
from .incident_severity import IncidentSeverity
from .incident_source_type import IncidentSourceType


class Incident(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Stable incident identifier.
    """

    organization_id: typing_extensions.Annotated[str, FieldMetadata(alias="organizationId")] = pydantic.Field()
    """
    Organization that owns this incident.
    """

    project_id: typing_extensions.Annotated[str, FieldMetadata(alias="projectId")] = pydantic.Field()
    """
    Project this incident belongs to.
    """

    source_type: typing_extensions.Annotated[IncidentSourceType, FieldMetadata(alias="sourceType")] = pydantic.Field()
    """
    Kind of entity that triggered the incident. `issue` for issue-lifecycle incidents; `savedSearch` for incidents raised by a monitor watching a search.
    """

    source_id: typing_extensions.Annotated[str, FieldMetadata(alias="sourceId")] = pydantic.Field()
    """
    Id of the entity that triggered the incident (matches `sourceType`).
    """

    kind: IncidentKind = pydantic.Field()
    """
    Reason the incident opened. `issue.new` fires when a new issue is discovered; `issue.regressed` when a resolved issue is detected again; `issue.escalating` when an ongoing issue is being detected more than expected. The `savedSearch.*` kinds are raised by monitors watching a search: `savedSearch.match` on each new matching trace, `savedSearch.threshold` when matching traces are detected above a configured threshold, and `savedSearch.escalating` when they stay above the threshold for a sustained window.
    """

    severity: IncidentSeverity = pydantic.Field()
    """
    Severity bucket assigned to the incident: `low`, `medium`, or `high`.
    """

    started_at: typing_extensions.Annotated[str, FieldMetadata(alias="startedAt")] = pydantic.Field()
    """
    ISO-8601 timestamp at which the incident opened.
    """

    ended_at: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="endedAt")] = pydantic.Field(
        default=None
    )
    """
    ISO-8601 timestamp at which the incident closed, or `null` if still open.
    """

    created_at: typing_extensions.Annotated[str, FieldMetadata(alias="createdAt")] = pydantic.Field()
    """
    ISO-8601 timestamp at which the incident row was created.
    """

    monitor_alert_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="monitorAlertId")] = (
        pydantic.Field(default=None)
    )
    """
    Id of the monitor alert that opened this incident, or `null` when not attributed to a monitor.
    """

    condition: typing.Optional[AlertCondition] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
