# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .memory_record_read import MemoryRecordRead


class MemoryRecordReads(UniversalBaseModel):
    items: typing.List[MemoryRecordRead] = pydantic.Field()
    """
    Retrieval events for the record, newest first, capped.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
