# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata


class MemoryStoreUser(UniversalBaseModel):
    user_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="userId"),
        pydantic.Field(alias="userId", description="End-user identifier that accessed the store."),
    ]
    last_accessed_at: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="lastAccessedAt"),
        pydantic.Field(
            alias="lastAccessedAt", description="ISO-8601 timestamp of the user's most recent access (read or write)."
        ),
    ]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
