# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata


class MonitorIssueResponse(UniversalBaseModel):
    job_id: typing_extensions.Annotated[str, FieldMetadata(alias="jobId")] = pydantic.Field()
    """
    Identifier of the monitor job.
    """

    evaluation_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="evaluationId")] = (
        pydantic.Field(default=None)
    )
    """
    The id of the evaluation being realigned, or `null` when a brand-new evaluation is being generated.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
