# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .incident_notifications_setting import IncidentNotificationsSetting


class NotificationsSetting(UniversalBaseModel):
    """
    Per-group project-level notification toggles. Today only `incidents` exists; future groups (wrapped reports, etc.) slot in alongside.
    """

    incidents: typing.Optional[IncidentNotificationsSetting] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
