# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel


class ProjectUsageResponsePeriod(UniversalBaseModel):
    """
    Billing period the usage figures cover.
    """

    start: str = pydantic.Field()
    """
    ISO-8601 start of the current billing period.
    """

    end: str = pydantic.Field()
    """
    ISO-8601 end of the current billing period, exclusive.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
