# This file was auto-generated by Fern from our API Definition.

import typing

SessionSignalStatesItem = typing.Union[
    typing.Literal["new", "escalating", "ongoing", "resolved", "regressed", "ignored"], typing.Any
]
