# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata
from .session_assessment_dimension_summary_reliability_completion import (
    SessionAssessmentDimensionSummaryReliabilityCompletion,
)
from .session_assessment_dimension_summary_reliability_coverage import (
    SessionAssessmentDimensionSummaryReliabilityCoverage,
)
from .session_assessment_dimension_summary_reliability_evidence_counts import (
    SessionAssessmentDimensionSummaryReliabilityEvidenceCounts,
)
from .session_assessment_dimension_summary_reliability_measurement_counts import (
    SessionAssessmentDimensionSummaryReliabilityMeasurementCounts,
)


class SessionAssessmentDimensionSummaryReliability(UniversalBaseModel):
    evidence_counts: typing_extensions.Annotated[
        SessionAssessmentDimensionSummaryReliabilityEvidenceCounts,
        FieldMetadata(alias="evidenceCounts"),
        pydantic.Field(alias="evidenceCounts", description="Evidence counts grouped by direction."),
    ]
    measurement_counts: typing_extensions.Annotated[
        SessionAssessmentDimensionSummaryReliabilityMeasurementCounts,
        FieldMetadata(alias="measurementCounts"),
        pydantic.Field(alias="measurementCounts", description="Evidence counts grouped by measurement state."),
    ]
    coverage: SessionAssessmentDimensionSummaryReliabilityCoverage = pydantic.Field()
    """
    Reader coverage for this dimension.
    """

    completion: SessionAssessmentDimensionSummaryReliabilityCompletion = pydantic.Field()
    """
    Resolved completion status.
    """

    recovered_incident_count: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="recoveredIncidentCount"),
        pydantic.Field(alias="recoveredIncidentCount", description="Number of recovered operational incidents."),
    ]
    unrecovered_incident_count: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="unrecoveredIncidentCount"),
        pydantic.Field(alias="unrecoveredIncidentCount", description="Number of unrecovered operational incidents."),
    ]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
