# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata


class SessionAssessmentEvidenceDestination_SessionMessage(UniversalBaseModel):
    kind: typing.Literal["sessionMessage"] = "sessionMessage"
    trace_id: typing_extensions.Annotated[str, FieldMetadata(alias="traceId"), pydantic.Field(alias="traceId")]
    message_index: typing_extensions.Annotated[
        int, FieldMetadata(alias="messageIndex"), pydantic.Field(alias="messageIndex")
    ]
    part_index: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="partIndex"), pydantic.Field(alias="partIndex", default=None)
    ]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class SessionAssessmentEvidenceDestination_Span(UniversalBaseModel):
    kind: typing.Literal["span"] = "span"
    trace_id: typing_extensions.Annotated[str, FieldMetadata(alias="traceId"), pydantic.Field(alias="traceId")]
    span_id: typing_extensions.Annotated[str, FieldMetadata(alias="spanId"), pydantic.Field(alias="spanId")]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class SessionAssessmentEvidenceDestination_ToolCall(UniversalBaseModel):
    kind: typing.Literal["toolCall"] = "toolCall"
    trace_id: typing_extensions.Annotated[str, FieldMetadata(alias="traceId"), pydantic.Field(alias="traceId")]
    tool_call_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="toolCallId"), pydantic.Field(alias="toolCallId")
    ]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class SessionAssessmentEvidenceDestination_MemoryEvent(UniversalBaseModel):
    kind: typing.Literal["memoryEvent"] = "memoryEvent"
    memory_event_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="memoryEventId"), pydantic.Field(alias="memoryEventId")
    ]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class SessionAssessmentEvidenceDestination_Score(UniversalBaseModel):
    kind: typing.Literal["score"] = "score"
    score_id: typing_extensions.Annotated[str, FieldMetadata(alias="scoreId"), pydantic.Field(alias="scoreId")]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class SessionAssessmentEvidenceDestination_Signal(UniversalBaseModel):
    kind: typing.Literal["signal"] = "signal"
    signal_id: typing_extensions.Annotated[str, FieldMetadata(alias="signalId"), pydantic.Field(alias="signalId")]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


SessionAssessmentEvidenceDestination = typing_extensions.Annotated[
    typing.Union[
        SessionAssessmentEvidenceDestination_SessionMessage,
        SessionAssessmentEvidenceDestination_Span,
        SessionAssessmentEvidenceDestination_ToolCall,
        SessionAssessmentEvidenceDestination_MemoryEvent,
        SessionAssessmentEvidenceDestination_Score,
        SessionAssessmentEvidenceDestination_Signal,
    ],
    pydantic.Field(discriminator="kind"),
]
