# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata


class SessionAssessmentEvidenceDestinationMemoryEvent(UniversalBaseModel):
    memory_event_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="memoryEventId"),
        pydantic.Field(alias="memoryEventId", description="Identifier of the destination memory event."),
    ]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
