# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata
from .session_assessment_cost_evaluation import SessionAssessmentCostEvaluation
from .session_assessment_dimension_effect_safety_benchmark_use import SessionAssessmentDimensionEffectSafetyBenchmarkUse
from .session_assessment_dimension_effect_safety_direction import SessionAssessmentDimensionEffectSafetyDirection
from .session_assessment_dimension_effect_safety_measurement import SessionAssessmentDimensionEffectSafetyMeasurement
from .session_assessment_dimension_effect_safety_role import SessionAssessmentDimensionEffectSafetyRole
from .session_assessment_evidence_impact import SessionAssessmentEvidenceImpact


class SessionAssessmentDimensionEffectSafety(UniversalBaseModel):
    role: SessionAssessmentDimensionEffectSafetyRole = pydantic.Field()
    """
    Safety evidence channel informed by this item.
    """

    direction: SessionAssessmentDimensionEffectSafetyDirection = pydantic.Field()
    """
    How the evidence affects this dimension.
    """

    measurement: SessionAssessmentDimensionEffectSafetyMeasurement = pydantic.Field()
    """
    Whether the impact was measured, estimated, or left unquantified.
    """

    benchmark_use: typing_extensions.Annotated[
        SessionAssessmentDimensionEffectSafetyBenchmarkUse,
        FieldMetadata(alias="benchmarkUse"),
        pydantic.Field(alias="benchmarkUse", description="How this evidence may be used in benchmark calculations."),
    ]
    impact: typing.Optional[SessionAssessmentEvidenceImpact] = None
    cost_evaluation: typing_extensions.Annotated[
        typing.Optional[SessionAssessmentCostEvaluation],
        FieldMetadata(alias="costEvaluation"),
        pydantic.Field(alias="costEvaluation", default=None),
    ]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
