# This file was auto-generated by Fern from our API Definition.

import typing

SessionAssessmentDimensionEffectSafetyRole = typing.Union[
    typing.Literal["confirmedHarm", "exposure", "successfulDefense"], typing.Any
]
