# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata
from .session_assessment_evidence_impact_completion_status import SessionAssessmentEvidenceImpactCompletionStatus
from .session_assessment_evidence_impact_incident_status import SessionAssessmentEvidenceImpactIncidentStatus
from .session_assessment_evidence_impact_safety_status import SessionAssessmentEvidenceImpactSafetyStatus
from .session_assessment_evidence_impact_task_outcome_verdict import SessionAssessmentEvidenceImpactTaskOutcomeVerdict


class SessionAssessmentEvidenceImpact_TaskOutcome(UniversalBaseModel):
    """
    Native structured impact carried by this evidence.
    """

    kind: typing.Literal["taskOutcome"] = "taskOutcome"
    verdict: SessionAssessmentEvidenceImpactTaskOutcomeVerdict
    probability: typing.Optional[float] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class SessionAssessmentEvidenceImpact_Completion(UniversalBaseModel):
    """
    Native structured impact carried by this evidence.
    """

    kind: typing.Literal["completion"] = "completion"
    status: SessionAssessmentEvidenceImpactCompletionStatus

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class SessionAssessmentEvidenceImpact_Incident(UniversalBaseModel):
    """
    Native structured impact carried by this evidence.
    """

    kind: typing.Literal["incident"] = "incident"
    status: SessionAssessmentEvidenceImpactIncidentStatus
    same_subject_recovered: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="sameSubjectRecovered"),
        pydantic.Field(alias="sameSubjectRecovered", default=None),
    ]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class SessionAssessmentEvidenceImpact_Spend(UniversalBaseModel):
    """
    Native structured impact carried by this evidence.
    """

    kind: typing.Literal["spend"] = "spend"
    observed_microcents: typing_extensions.Annotated[
        float, FieldMetadata(alias="observedMicrocents"), pydantic.Field(alias="observedMicrocents")
    ]
    avoidable_microcents: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="avoidableMicrocents"),
        pydantic.Field(alias="avoidableMicrocents", default=None),
    ]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class SessionAssessmentEvidenceImpact_Duration(UniversalBaseModel):
    """
    Native structured impact carried by this evidence.
    """

    kind: typing.Literal["duration"] = "duration"
    observed_ns: typing_extensions.Annotated[
        float, FieldMetadata(alias="observedNs"), pydantic.Field(alias="observedNs")
    ]
    avoidable_ns: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="avoidableNs"), pydantic.Field(alias="avoidableNs", default=None)
    ]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class SessionAssessmentEvidenceImpact_OutcomeAssociation(UniversalBaseModel):
    """
    Native structured impact carried by this evidence.
    """

    kind: typing.Literal["outcomeAssociation"] = "outcomeAssociation"
    probability_change: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="probabilityChange"),
        pydantic.Field(alias="probabilityChange", default=None),
    ]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class SessionAssessmentEvidenceImpact_Safety(UniversalBaseModel):
    """
    Native structured impact carried by this evidence.
    """

    kind: typing.Literal["safety"] = "safety"
    status: SessionAssessmentEvidenceImpactSafetyStatus
    finding_kind: typing_extensions.Annotated[
        str, FieldMetadata(alias="findingKind"), pydantic.Field(alias="findingKind")
    ]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class SessionAssessmentEvidenceImpact_Observation(UniversalBaseModel):
    """
    Native structured impact carried by this evidence.
    """

    kind: typing.Literal["observation"] = "observation"
    value: typing.Optional[float] = None
    unit: typing.Optional[str] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


SessionAssessmentEvidenceImpact = typing_extensions.Annotated[
    typing.Union[
        SessionAssessmentEvidenceImpact_TaskOutcome,
        SessionAssessmentEvidenceImpact_Completion,
        SessionAssessmentEvidenceImpact_Incident,
        SessionAssessmentEvidenceImpact_Spend,
        SessionAssessmentEvidenceImpact_Duration,
        SessionAssessmentEvidenceImpact_OutcomeAssociation,
        SessionAssessmentEvidenceImpact_Safety,
        SessionAssessmentEvidenceImpact_Observation,
    ],
    pydantic.Field(discriminator="kind"),
]
