# This file was auto-generated by Fern from our API Definition.

import typing

SessionAssessmentDimensionEffectReliabilityRole = typing.Union[
    typing.Literal["completionOutcome", "operationalIncident"], typing.Any
]
