# This file was auto-generated by Fern from our API Definition.

import typing

SessionAssessmentCostMetricEvidenceNativeImpactInterpretation = typing.Union[
    typing.Literal["identificationBound", "confidenceInterval"], typing.Any
]
