# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata


class SessionAssessmentEvidenceDestinationSignal(UniversalBaseModel):
    signal_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="signalId"),
        pydantic.Field(alias="signalId", description="Identifier of the destination signal."),
    ]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
