# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .signal_lifecycle_item import SignalLifecycleItem


class SignalsLifecycleResponse(UniversalBaseModel):
    items: typing.List[SignalLifecycleItem] = pydantic.Field()
    """
    Per-signal result, in the order requested.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
