# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata
from .evaluation import Evaluation
from .signal_detail_source import SignalDetailSource
from .signal_detail_states_item import SignalDetailStatesItem
from .signal_monitoring_state import SignalMonitoringState
from .signal_trend_bucket import SignalTrendBucket


class SignalDetail(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Stable signal identifier.
    """

    organization_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="organizationId"),
        pydantic.Field(alias="organizationId", description="Organization that owns this signal."),
    ]
    project_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="projectId"),
        pydantic.Field(alias="projectId", description="Project this signal belongs to."),
    ]
    slug: str = pydantic.Field()
    """
    URL-safe slug derived from `name`. Unique within the project.
    """

    name: str = pydantic.Field()
    """
    Human-readable name.
    """

    description: str = pydantic.Field()
    """
    Description of the signal.
    """

    source: SignalDetailSource = pydantic.Field()
    """
    Where the signal originated from.
    """

    states: typing.List[SignalDetailStatesItem] = pydantic.Field()
    """
    Active lifecycle states. A signal may carry multiple states at once (e.g. `escalating` + `new`).
    """

    resolved_at: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="resolvedAt"),
        pydantic.Field(
            alias="resolvedAt",
            default=None,
            description="ISO-8601 timestamp at which the signal was resolved, or `null`.",
        ),
    ]
    ignored_at: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="ignoredAt"),
        pydantic.Field(
            alias="ignoredAt",
            default=None,
            description="ISO-8601 timestamp at which the signal was ignored, or `null`.",
        ),
    ]
    regressed_at: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="regressedAt"),
        pydantic.Field(
            alias="regressedAt",
            default=None,
            description="ISO-8601 timestamp at which a new occurrence reopened the resolved signal, or `null`.",
        ),
    ]
    muted_at: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="mutedAt"),
        pydantic.Field(
            alias="mutedAt",
            default=None,
            description="ISO-8601 timestamp at which notifications were muted, or `null`. Muting only silences notifications; incidents still open.",
        ),
    ]
    created_at: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="ISO-8601 timestamp of creation."),
    ]
    updated_at: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="updatedAt"),
        pydantic.Field(alias="updatedAt", description="ISO-8601 timestamp of the last update."),
    ]
    trend: typing.List[SignalTrendBucket] = pydantic.Field()
    """
    Daily occurrence counts over the past 14 days.
    """

    tags: typing.List[str] = pydantic.Field()
    """
    Tags seen on the signal's occurrences.
    """

    first_seen_at: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="firstSeenAt"),
        pydantic.Field(
            alias="firstSeenAt",
            default=None,
            description="ISO-8601 timestamp of the earliest occurrence over the signal's lifetime, or `null` if none yet.",
        ),
    ]
    last_seen_at: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="lastSeenAt"),
        pydantic.Field(
            alias="lastSeenAt",
            default=None,
            description="ISO-8601 timestamp of the latest occurrence over the signal's lifetime, or `null` if none yet.",
        ),
    ]
    occurrences: int = pydantic.Field()
    """
    Lifetime occurrence count.
    """

    affected_sessions_percent: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="affectedSessionsPercent"),
        pydantic.Field(
            alias="affectedSessionsPercent",
            description="Lifetime fraction of project sessions affected by this signal, in `[0, 1]`.",
        ),
    ]
    evaluations: typing.List[Evaluation] = pydantic.Field()
    """
    Active evaluations monitoring the signal. Archived and deleted evaluations are excluded.
    """

    monitoring_state: typing_extensions.Annotated[
        SignalMonitoringState, FieldMetadata(alias="monitoringState"), pydantic.Field(alias="monitoringState")
    ]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
