# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata


class SignalsLifecycleBody(UniversalBaseModel):
    signal_ids: typing_extensions.Annotated[typing.List[str], FieldMetadata(alias="signalIds")] = pydantic.Field()
    """
    Non-empty list of signal ids. Operations are idempotent — already-applied signals are unchanged.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
