# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel


class ToolParameterValueStat(UniversalBaseModel):
    value: str = pydantic.Field()
    """
    A value seen for the key (truncated).
    """

    count: int = pydantic.Field()
    """
    Number of sampled calls with this value.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
