# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata


class ToolsAnalyticsTotals(UniversalBaseModel):
    """
    Project-wide denominators for the range.
    """

    traces: int = pydantic.Field()
    """
    Total traces in the range.
    """

    sessions: int = pydantic.Field()
    """
    Total sessions in the range.
    """

    traces_with_tool_calls: typing_extensions.Annotated[int, FieldMetadata(alias="tracesWithToolCalls")] = (
        pydantic.Field()
    )
    """
    Traces with at least one tool call (any tool).
    """

    sessions_with_tool_calls: typing_extensions.Annotated[int, FieldMetadata(alias="sessionsWithToolCalls")] = (
        pydantic.Field()
    )
    """
    Sessions with at least one tool call (any tool).
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
