# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .trace_analytics_bucket import TraceAnalyticsBucket


class TraceAnalyticsTimeToFirstToken(UniversalBaseModel):
    median: float = pydantic.Field()
    """
    Median time-to-first-token across LLM spans, in seconds.
    """

    buckets: typing.List[TraceAnalyticsBucket] = pydantic.Field()
    """
    Median time-to-first-token per bucket, in seconds.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
