# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel
from .span import Span


class TraceSpans(UniversalBaseModel):
    items: typing.List[Span] = pydantic.Field()
    """
    All spans belonging to the trace, ordered by `startTime` ascending.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
