# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import UniversalBaseModel


class UpdateSignalResponse(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Updated signal id.
    """

    slug: str = pydantic.Field()
    """
    URL-safe identifier (stable across updates).
    """

    changed: bool = pydantic.Field()
    """
    Whether any field actually changed.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
