# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import UniversalBaseModel
from ..core.serialization import FieldMetadata
from .resolved_range import ResolvedRange
from .variant_metric_deltas import VariantMetricDeltas
from .variant_metrics import VariantMetrics


class VariantComparison(UniversalBaseModel):
    variant_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="variantId"),
        pydantic.Field(alias="variantId", description="Id of the variant these metrics belong to."),
    ]
    baseline: bool = pydantic.Field()
    """
    `true` when this is the baseline variant; its deltas are empty.
    """

    approximate: bool = pydantic.Field()
    """
    `true` when the variant's query has a semantic component, making its population a best-effort sample.
    """

    resolved_range: typing_extensions.Annotated[
        ResolvedRange, FieldMetadata(alias="resolvedRange"), pydantic.Field(alias="resolvedRange")
    ]
    metrics: VariantMetrics
    deltas: VariantMetricDeltas
    deviating_population_keys: typing_extensions.Annotated[
        typing.List[str],
        FieldMetadata(alias="deviatingPopulationKeys"),
        pydantic.Field(
            alias="deviatingPopulationKeys",
            description="Population keys (a subset of `sessions.count` / `sessions.users`) that deviate from the baseline by more than 25%.",
        ),
    ]

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
