// This file was auto-generated by Fern from our API Definition.

/** Sort direction. Defaults to `desc` (most recent first). */
export const ListTracesSavedSearchesRequestSortDirection = {
    Asc: "asc",
    Desc: "desc",
} as const;
export type ListTracesSavedSearchesRequestSortDirection =
    (typeof ListTracesSavedSearchesRequestSortDirection)[keyof typeof ListTracesSavedSearchesRequestSortDirection];
