// This file was auto-generated by Fern from our API Definition.

/** Sort direction. Defaults to `desc` (most recent first). */
export const SavedSearchesListTracesRequestSortDirection = {
    Asc: "asc",
    Desc: "desc",
} as const;
export type SavedSearchesListTracesRequestSortDirection =
    (typeof SavedSearchesListTracesRequestSortDirection)[keyof typeof SavedSearchesListTracesRequestSortDirection];
