// This file was auto-generated by Fern from our API Definition.

/** Field to sort by. Defaults to `startTime`. Pass `relevance` to rank by semantic match against the saved search's query (best match first, then most recent). */
export const SavedSearchesListTracesRequestSortBy = {
    Relevance: "relevance",
    StartTime: "startTime",
    EndTime: "endTime",
    DurationNs: "durationNs",
    TokensTotal: "tokensTotal",
    CostTotalMicrocents: "costTotalMicrocents",
} as const;
export type SavedSearchesListTracesRequestSortBy =
    (typeof SavedSearchesListTracesRequestSortBy)[keyof typeof SavedSearchesListTracesRequestSortBy];
