// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface GetAssessmentSessionsRequest {
    /** Opaque cursor returned by a previous assessment page. Omit for the first page. */
    cursor?: string;
}
