// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface GetMemoryChangesSessionsRequest {
    /** Restrict the memory changes to this trace of the session. Omit for the whole session. */
    traceId?: string;
}
