# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.incident import Incident
from ..types.list_incidents_response import ListIncidentsResponse
from .raw_client import AsyncRawIncidentsClient, RawIncidentsClient
from .types.list_incidents_request_severities_item import ListIncidentsRequestSeveritiesItem
from .types.list_incidents_request_source_type import ListIncidentsRequestSourceType


class IncidentsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawIncidentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawIncidentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawIncidentsClient
        """
        return self._raw_client

    def list(
        self,
        project_slug: str,
        *,
        from_iso: typing.Optional[dt.datetime] = None,
        to_iso: typing.Optional[dt.datetime] = None,
        source_type: typing.Optional[ListIncidentsRequestSourceType] = None,
        source_id: typing.Optional[str] = None,
        severities: typing.Optional[
            typing.Union[ListIncidentsRequestSeveritiesItem, typing.Sequence[ListIncidentsRequestSeveritiesItem]]
        ] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListIncidentsResponse:
        """
        Returns incidents in the project, ordered from oldest to newest. The time window defaults to the trailing 7 days.

        Parameters
        ----------
        project_slug : str
            Project slug (human-readable identifier)

        from_iso : typing.Optional[dt.datetime]
            Lower bound (inclusive) of the time window. Returns incidents whose lifetime overlaps `[fromIso, toIso]`. Defaults to 7 days before `toIso`.

        to_iso : typing.Optional[dt.datetime]
            Upper bound (inclusive) of the time window. Defaults to now.

        source_type : typing.Optional[ListIncidentsRequestSourceType]
            Restrict to incidents triggered by this source type: `monitor` or `signal`.

        source_id : typing.Optional[str]
            Restrict to incidents tied to one source entity id.

        severities : typing.Optional[typing.Union[ListIncidentsRequestSeveritiesItem, typing.Sequence[ListIncidentsRequestSeveritiesItem]]]
            Restrict to incidents whose severity matches any value in this list.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListIncidentsResponse
            Matching incidents

        Examples
        --------
        from latitude_sdk import LatitudeClient

        client = LatitudeClient(
            api_key="YOUR_API_KEY",
        )
        client.incidents.list(
            project_slug="projectSlug",
        )
        """
        _response = self._raw_client.list(
            project_slug,
            from_iso=from_iso,
            to_iso=to_iso,
            source_type=source_type,
            source_id=source_id,
            severities=severities,
            request_options=request_options,
        )
        return _response.data

    def resolve(
        self, project_slug: str, incident_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> Incident:
        """
        Resolves (closes) an ongoing incident. An already-closed incident is returned unchanged. If the incident's condition triggers again, a new incident will be opened.

        Parameters
        ----------
        project_slug : str
            Project slug (human-readable identifier)

        incident_id : str
            Incident identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Incident
            Resolved incident

        Examples
        --------
        from latitude_sdk import LatitudeClient

        client = LatitudeClient(
            api_key="YOUR_API_KEY",
        )
        client.incidents.resolve(
            project_slug="projectSlug",
            incident_id="incidentId",
        )
        """
        _response = self._raw_client.resolve(project_slug, incident_id, request_options=request_options)
        return _response.data


class AsyncIncidentsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawIncidentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawIncidentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawIncidentsClient
        """
        return self._raw_client

    async def list(
        self,
        project_slug: str,
        *,
        from_iso: typing.Optional[dt.datetime] = None,
        to_iso: typing.Optional[dt.datetime] = None,
        source_type: typing.Optional[ListIncidentsRequestSourceType] = None,
        source_id: typing.Optional[str] = None,
        severities: typing.Optional[
            typing.Union[ListIncidentsRequestSeveritiesItem, typing.Sequence[ListIncidentsRequestSeveritiesItem]]
        ] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListIncidentsResponse:
        """
        Returns incidents in the project, ordered from oldest to newest. The time window defaults to the trailing 7 days.

        Parameters
        ----------
        project_slug : str
            Project slug (human-readable identifier)

        from_iso : typing.Optional[dt.datetime]
            Lower bound (inclusive) of the time window. Returns incidents whose lifetime overlaps `[fromIso, toIso]`. Defaults to 7 days before `toIso`.

        to_iso : typing.Optional[dt.datetime]
            Upper bound (inclusive) of the time window. Defaults to now.

        source_type : typing.Optional[ListIncidentsRequestSourceType]
            Restrict to incidents triggered by this source type: `monitor` or `signal`.

        source_id : typing.Optional[str]
            Restrict to incidents tied to one source entity id.

        severities : typing.Optional[typing.Union[ListIncidentsRequestSeveritiesItem, typing.Sequence[ListIncidentsRequestSeveritiesItem]]]
            Restrict to incidents whose severity matches any value in this list.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListIncidentsResponse
            Matching incidents

        Examples
        --------
        import asyncio

        from latitude_sdk import AsyncLatitudeClient

        client = AsyncLatitudeClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.incidents.list(
                project_slug="projectSlug",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            project_slug,
            from_iso=from_iso,
            to_iso=to_iso,
            source_type=source_type,
            source_id=source_id,
            severities=severities,
            request_options=request_options,
        )
        return _response.data

    async def resolve(
        self, project_slug: str, incident_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> Incident:
        """
        Resolves (closes) an ongoing incident. An already-closed incident is returned unchanged. If the incident's condition triggers again, a new incident will be opened.

        Parameters
        ----------
        project_slug : str
            Project slug (human-readable identifier)

        incident_id : str
            Incident identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Incident
            Resolved incident

        Examples
        --------
        import asyncio

        from latitude_sdk import AsyncLatitudeClient

        client = AsyncLatitudeClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.incidents.resolve(
                project_slug="projectSlug",
                incident_id="incidentId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.resolve(project_slug, incident_id, request_options=request_options)
        return _response.data
