// This file was auto-generated by Fern from our API Definition.

import type * as LatitudeApi from "../../../../index.js";

/**
 * @example
 *     {
 *         name: "name"
 *     }
 */
export interface CreateSavedSearchBody {
    /** Human-readable name. Used to derive the slug. */
    name: string;
    /** Free-text semantic query. `null` (default) when the search is filter-only. At least one of `query` or `filters` must be set. */
    query?: string;
    filters?: LatitudeApi.FilterSet;
}
