// This file was auto-generated by Fern from our API Definition.

import type * as Latitude from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface UpdateSavedSearchBody {
    /** New human-readable name. Triggers slug regeneration when the change affects the slug form (cosmetic edits like capitalization keep the URL stable). */
    name?: string;
    /** Replace the free-text query. Pass `null` to clear it. */
    query?: string | null;
    /** Replace the structured filter set. */
    filters?: Record<string, Latitude.FilterCondition[]>;
}
