# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.active_member import ActiveMember
from ..types.invited_member import InvitedMember
from ..types.member_list import MemberList
from .raw_client import AsyncRawMembersClient, RawMembersClient
from .types.invite_member_body_role import InviteMemberBodyRole
from .types.update_member_role_body_role import UpdateMemberRoleBodyRole

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class MembersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawMembersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawMembersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawMembersClient
        """
        return self._raw_client

    def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> MemberList:
        """
        Returns every active member of the caller's organization with their role and user details.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MemberList
            List of members

        Examples
        --------
        from latitude import LatitudeApiClient

        client = LatitudeApiClient(
            token="YOUR_TOKEN",
        )
        client.members.list()
        """
        _response = self._raw_client.list(request_options=request_options)
        return _response.data

    def invite(
        self,
        *,
        email: str,
        role: typing.Optional[InviteMemberBodyRole] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> InvitedMember:
        """
        Signals an invitation to join the caller's organization. The invitee receives an accept link by email and becomes a member once they accept. The response is the pending invitation record. Requires OAuth authentication (API-key callers can't act on behalf of a specific user).

        Parameters
        ----------
        email : str
            Email address to invite. The invitee receives an accept link by email.

        role : typing.Optional[InviteMemberBodyRole]
            Role to grant on acceptance. Defaults to `member` when omitted.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InvitedMember
            Invitation created

        Examples
        --------
        from latitude import LatitudeApiClient

        client = LatitudeApiClient(
            token="YOUR_TOKEN",
        )
        client.members.invite(
            email="email",
        )
        """
        _response = self._raw_client.invite(email=email, role=role, request_options=request_options)
        return _response.data

    def get(self, member_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> ActiveMember:
        """
        Returns a single member of the caller's organization, including their role and user details.

        Parameters
        ----------
        member_id : str
            Membership identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ActiveMember
            Member

        Examples
        --------
        from latitude import LatitudeApiClient

        client = LatitudeApiClient(
            token="YOUR_TOKEN",
        )
        client.members.get(
            member_id="memberId",
        )
        """
        _response = self._raw_client.get(member_id, request_options=request_options)
        return _response.data

    def remove(self, member_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Removes a member from the caller's organization. Self-removal and removing the organization owner are rejected — transfer ownership first. Requires OAuth authentication.

        Parameters
        ----------
        member_id : str
            Membership identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from latitude import LatitudeApiClient

        client = LatitudeApiClient(
            token="YOUR_TOKEN",
        )
        client.members.remove(
            member_id="memberId",
        )
        """
        _response = self._raw_client.remove(member_id, request_options=request_options)
        return _response.data

    def update(
        self, member_id: str, *, role: UpdateMemberRoleBodyRole, request_options: typing.Optional[RequestOptions] = None
    ) -> ActiveMember:
        """
        Updates a member of the caller's organization. Today only the role is mutable. The caller must be an admin or owner; owners cannot be demoted via this endpoint. Requires OAuth authentication.

        Parameters
        ----------
        member_id : str
            Membership identifier.

        role : UpdateMemberRoleBodyRole
            New role. Owners cannot be changed via this endpoint — owner-transfer happens on the web.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ActiveMember
            Member with the updated role

        Examples
        --------
        from latitude import LatitudeApiClient

        client = LatitudeApiClient(
            token="YOUR_TOKEN",
        )
        client.members.update(
            member_id="memberId",
            role="admin",
        )
        """
        _response = self._raw_client.update(member_id, role=role, request_options=request_options)
        return _response.data


class AsyncMembersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawMembersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawMembersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawMembersClient
        """
        return self._raw_client

    async def list(self, *, request_options: typing.Optional[RequestOptions] = None) -> MemberList:
        """
        Returns every active member of the caller's organization with their role and user details.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MemberList
            List of members

        Examples
        --------
        import asyncio

        from latitude import AsyncLatitudeApiClient

        client = AsyncLatitudeApiClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.members.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(request_options=request_options)
        return _response.data

    async def invite(
        self,
        *,
        email: str,
        role: typing.Optional[InviteMemberBodyRole] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> InvitedMember:
        """
        Signals an invitation to join the caller's organization. The invitee receives an accept link by email and becomes a member once they accept. The response is the pending invitation record. Requires OAuth authentication (API-key callers can't act on behalf of a specific user).

        Parameters
        ----------
        email : str
            Email address to invite. The invitee receives an accept link by email.

        role : typing.Optional[InviteMemberBodyRole]
            Role to grant on acceptance. Defaults to `member` when omitted.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InvitedMember
            Invitation created

        Examples
        --------
        import asyncio

        from latitude import AsyncLatitudeApiClient

        client = AsyncLatitudeApiClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.members.invite(
                email="email",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.invite(email=email, role=role, request_options=request_options)
        return _response.data

    async def get(self, member_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> ActiveMember:
        """
        Returns a single member of the caller's organization, including their role and user details.

        Parameters
        ----------
        member_id : str
            Membership identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ActiveMember
            Member

        Examples
        --------
        import asyncio

        from latitude import AsyncLatitudeApiClient

        client = AsyncLatitudeApiClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.members.get(
                member_id="memberId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(member_id, request_options=request_options)
        return _response.data

    async def remove(self, member_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Removes a member from the caller's organization. Self-removal and removing the organization owner are rejected — transfer ownership first. Requires OAuth authentication.

        Parameters
        ----------
        member_id : str
            Membership identifier.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from latitude import AsyncLatitudeApiClient

        client = AsyncLatitudeApiClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.members.remove(
                member_id="memberId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.remove(member_id, request_options=request_options)
        return _response.data

    async def update(
        self, member_id: str, *, role: UpdateMemberRoleBodyRole, request_options: typing.Optional[RequestOptions] = None
    ) -> ActiveMember:
        """
        Updates a member of the caller's organization. Today only the role is mutable. The caller must be an admin or owner; owners cannot be demoted via this endpoint. Requires OAuth authentication.

        Parameters
        ----------
        member_id : str
            Membership identifier.

        role : UpdateMemberRoleBodyRole
            New role. Owners cannot be changed via this endpoint — owner-transfer happens on the web.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ActiveMember
            Member with the updated role

        Examples
        --------
        import asyncio

        from latitude import AsyncLatitudeApiClient

        client = AsyncLatitudeApiClient(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.members.update(
                member_id="memberId",
                role="admin",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(member_id, role=role, request_options=request_options)
        return _response.data
