// This file was auto-generated by Fern from our API Definition.

/**
 * Organization the request is scoped to.
 */
export interface AccountOrganization {
    /** Stable organization identifier across the API. */
    id: string;
    /** Human-readable organization name. */
    name: string;
    /** URL-safe slug. Regenerated when the organization is renamed — don't use it as a stable key. */
    slug: string;
}
