// This file was auto-generated by Fern from our API Definition.

import type * as Latitude from "../index.js";

export interface AccountResponse {
    user: Latitude.AccountUser | null;
    organization: Latitude.AccountOrganization;
    /** Caller's role in the organization. `null` for API-key callers (no real user behind the credential). */
    role: AccountResponse.Role | null;
}

export namespace AccountResponse {
    /** Caller's role in the organization. `null` for API-key callers (no real user behind the credential). */
    export const Role = {
        Owner: "owner",
        Admin: "admin",
        Member: "member",
    } as const;
    export type Role = (typeof Role)[keyof typeof Role];
}
