// This file was auto-generated by Fern from our API Definition.

import type * as LatitudeApi from "../index.js";

export interface AlertThresholdCondition {
    metric: LatitudeApi.MonitorMetric;
    threshold: LatitudeApi.AlertMetricThreshold;
    /** Direction that opens the incident. Defaults to `above` when omitted. */
    direction?: AlertThresholdCondition.Direction | undefined;
}

export namespace AlertThresholdCondition {
    /** Direction that opens the incident. Defaults to `above` when omitted. */
    export const Direction = {
        Above: "above",
        Below: "below",
    } as const;
    export type Direction = (typeof Direction)[keyof typeof Direction];
}
