// This file was auto-generated by Fern from our API Definition.

import type * as LatitudeApi from "../index.js";

/**
 * Condition that controls threshold or escalating incidents.
 */
export type AlertCondition = LatitudeApi.AlertCondition.Threshold | LatitudeApi.AlertCondition.Escalating;

export namespace AlertCondition {
    export interface Threshold extends LatitudeApi.AlertThresholdCondition {
        trigger: "threshold";
    }

    export interface Escalating extends LatitudeApi.AlertEscalatingCondition {
        trigger: "escalating";
    }
}
