// This file was auto-generated by Fern from our API Definition.

export interface AnalyticsSeries {
    /** Tidy series: one point per breakdown key and/or time bucket. */
    series: AnalyticsSeries.Series.Item[];
}

export namespace AnalyticsSeries {
    export type Series = Series.Item[];

    export namespace Series {
        export interface Item {
            /** The breakdown value, present when `breakdown` was set. */
            key?: string | undefined;
            /** Human-readable name for `key` when the breakdown value is an opaque id — the signal name for `signalId`, the cluster name for `cluster`. Absent for already-readable breakdowns. */
            label?: string | undefined;
            /** ISO-8601 start of the time bucket, present when `timeBucket` was set. */
            bucketStart?: string | undefined;
            /** The metric value: seconds for `duration`, dollars for `cost`, a 0–1 ratio for `errorRate`/`cacheHitRate`, otherwise a raw count/token total. */
            value: number;
        }
    }
}
