// This file was auto-generated by Fern from our API Definition.

export interface ApiKey {
    id: string;
    organizationId: string;
    name: string;
    /** The API key token. Only included in the creation response — store it securely. */
    token: string;
    tokenHash: string;
    lastUsedAt?: string | undefined;
    deletedAt?: string | undefined;
    createdAt: string;
    updatedAt: string;
}
