// This file was auto-generated by Fern from our API Definition.

export interface ApiKeyListItem {
    id: string;
    organizationId: string;
    name: string;
    lastUsedAt?: string | undefined;
    deletedAt?: string | undefined;
    createdAt: string;
    updatedAt: string;
}
