// This file was auto-generated by Fern from our API Definition.

export interface ApiKeyListItem {
    /** Stable API-key identifier. */
    id: string;
    /** Organization that owns this API key. */
    organizationId: string;
    /** Human-readable name. */
    name: string;
    /** Masked token preview safe to display in lists. Use `GET /api-keys/{apiKeyId}` to retrieve the full token. */
    token: string;
    /** ISO-8601 timestamp of the most recent successful authentication. `null` until first use. */
    lastUsedAt?: string | undefined;
    /** ISO-8601 timestamp at which the key was revoked. `null` while the key is active. */
    deletedAt?: string | undefined;
    /** ISO-8601 timestamp of creation. */
    createdAt: string;
    /** ISO-8601 timestamp of the last metadata update. */
    updatedAt: string;
}
