// This file was auto-generated by Fern from our API Definition.

export interface BootstrapAccountResponse {
    /** Slug of the temporary organization. */
    organizationSlug: string;
    /** Slug of the created project. */
    projectSlug: string;
    /** Organization-scoped API key. */
    apiKey: string;
    /** URL to open in a browser to claim ownership of the organization. */
    claimUrl: string;
    /** Email address the claim link will be sent to, or `null` if none was provided. */
    claimEmail: string | null;
    /** ISO-8601 timestamp when the claim link expires. The organization is deleted if not claimed by then. */
    claimExpiresAt: string;
}
