// This file was auto-generated by Fern from our API Definition.

import type * as Latitude from "../index.js";

/**
 * Metric evaluated by the monitor rule.
 */
export type CreateMonitorBodyEscalatingMetric =
    | Latitude.CreateMonitorBodyEscalatingMetric.Count
    | Latitude.CreateMonitorBodyEscalatingMetric.ErrorRate
    | Latitude.CreateMonitorBodyEscalatingMetric.CacheHitRate
    | Latitude.CreateMonitorBodyEscalatingMetric.Avg
    | Latitude.CreateMonitorBodyEscalatingMetric.Sum
    | Latitude.CreateMonitorBodyEscalatingMetric.Min
    | Latitude.CreateMonitorBodyEscalatingMetric.Max
    | Latitude.CreateMonitorBodyEscalatingMetric.Median;

export namespace CreateMonitorBodyEscalatingMetric {
    export interface Count {
        kind: "count";
    }

    export interface ErrorRate {
        kind: "errorRate";
    }

    export interface CacheHitRate {
        kind: "cacheHitRate";
    }

    export interface Avg {
        kind: "avg";
        /** Numeric field to aggregate. */
        field: CreateMonitorBodyEscalatingMetricAvg.Field;
    }

    export namespace CreateMonitorBodyEscalatingMetricAvg {
        /** Numeric field to aggregate. */
        export const Field = {
            Duration: "duration",
            Cost: "cost",
            Tokens: "tokens",
        } as const;
        export type Field = (typeof Field)[keyof typeof Field];
    }

    export interface Sum {
        kind: "sum";
        /** Numeric field to aggregate. */
        field: CreateMonitorBodyEscalatingMetricSum.Field;
    }

    export namespace CreateMonitorBodyEscalatingMetricSum {
        /** Numeric field to aggregate. */
        export const Field = {
            Duration: "duration",
            Cost: "cost",
            Tokens: "tokens",
        } as const;
        export type Field = (typeof Field)[keyof typeof Field];
    }

    export interface Min {
        kind: "min";
        /** Numeric field to aggregate. */
        field: CreateMonitorBodyEscalatingMetricMin.Field;
    }

    export namespace CreateMonitorBodyEscalatingMetricMin {
        /** Numeric field to aggregate. */
        export const Field = {
            Duration: "duration",
            Cost: "cost",
            Tokens: "tokens",
        } as const;
        export type Field = (typeof Field)[keyof typeof Field];
    }

    export interface Max {
        kind: "max";
        /** Numeric field to aggregate. */
        field: CreateMonitorBodyEscalatingMetricMax.Field;
    }

    export namespace CreateMonitorBodyEscalatingMetricMax {
        /** Numeric field to aggregate. */
        export const Field = {
            Duration: "duration",
            Cost: "cost",
            Tokens: "tokens",
        } as const;
        export type Field = (typeof Field)[keyof typeof Field];
    }

    export interface Median {
        kind: "median";
        /** Numeric field to aggregate. */
        field: CreateMonitorBodyEscalatingMetricMedian.Field;
    }

    export namespace CreateMonitorBodyEscalatingMetricMedian {
        /** Numeric field to aggregate. */
        export const Field = {
            Duration: "duration",
            Cost: "cost",
            Tokens: "tokens",
        } as const;
        export type Field = (typeof Field)[keyof typeof Field];
    }
}
