// This file was auto-generated by Fern from our API Definition.

import type * as Latitude from "../index.js";

/**
 * Default metric evaluated for this target.
 */
export type CreateMonitorBodyMatchTargetMetric =
    | Latitude.CreateMonitorBodyMatchTargetMetric.Count
    | Latitude.CreateMonitorBodyMatchTargetMetric.ErrorRate
    | Latitude.CreateMonitorBodyMatchTargetMetric.CacheHitRate
    | Latitude.CreateMonitorBodyMatchTargetMetric.Avg
    | Latitude.CreateMonitorBodyMatchTargetMetric.Sum
    | Latitude.CreateMonitorBodyMatchTargetMetric.Min
    | Latitude.CreateMonitorBodyMatchTargetMetric.Max
    | Latitude.CreateMonitorBodyMatchTargetMetric.Median;

export namespace CreateMonitorBodyMatchTargetMetric {
    export interface Count {
        kind: "count";
    }

    export interface ErrorRate {
        kind: "errorRate";
    }

    export interface CacheHitRate {
        kind: "cacheHitRate";
    }

    export interface Avg {
        kind: "avg";
        /** Numeric field to aggregate. */
        field: CreateMonitorBodyMatchTargetMetricAvg.Field;
    }

    export namespace CreateMonitorBodyMatchTargetMetricAvg {
        /** Numeric field to aggregate. */
        export const Field = {
            Duration: "duration",
            Cost: "cost",
            Tokens: "tokens",
        } as const;
        export type Field = (typeof Field)[keyof typeof Field];
    }

    export interface Sum {
        kind: "sum";
        /** Numeric field to aggregate. */
        field: CreateMonitorBodyMatchTargetMetricSum.Field;
    }

    export namespace CreateMonitorBodyMatchTargetMetricSum {
        /** Numeric field to aggregate. */
        export const Field = {
            Duration: "duration",
            Cost: "cost",
            Tokens: "tokens",
        } as const;
        export type Field = (typeof Field)[keyof typeof Field];
    }

    export interface Min {
        kind: "min";
        /** Numeric field to aggregate. */
        field: CreateMonitorBodyMatchTargetMetricMin.Field;
    }

    export namespace CreateMonitorBodyMatchTargetMetricMin {
        /** Numeric field to aggregate. */
        export const Field = {
            Duration: "duration",
            Cost: "cost",
            Tokens: "tokens",
        } as const;
        export type Field = (typeof Field)[keyof typeof Field];
    }

    export interface Max {
        kind: "max";
        /** Numeric field to aggregate. */
        field: CreateMonitorBodyMatchTargetMetricMax.Field;
    }

    export namespace CreateMonitorBodyMatchTargetMetricMax {
        /** Numeric field to aggregate. */
        export const Field = {
            Duration: "duration",
            Cost: "cost",
            Tokens: "tokens",
        } as const;
        export type Field = (typeof Field)[keyof typeof Field];
    }

    export interface Median {
        kind: "median";
        /** Numeric field to aggregate. */
        field: CreateMonitorBodyMatchTargetMetricMedian.Field;
    }

    export namespace CreateMonitorBodyMatchTargetMetricMedian {
        /** Numeric field to aggregate. */
        export const Field = {
            Duration: "duration",
            Cost: "cost",
            Tokens: "tokens",
        } as const;
        export type Field = (typeof Field)[keyof typeof Field];
    }
}
