// This file was auto-generated by Fern from our API Definition.

import type * as LatitudeApi from "../index.js";

export interface CreateCustomScoreBody {
    simulationId?: string | undefined;
    value: number;
    passed: boolean;
    feedback: string;
    error?: string | undefined;
    duration?: number | undefined;
    tokens?: number | undefined;
    cost?: number | undefined;
    trace?: LatitudeApi.TraceRef | undefined;
    sourceId: string;
    metadata?: Record<string, unknown> | undefined;
    _evaluation?: boolean | undefined;
}
