// This file was auto-generated by Fern from our API Definition.

import type * as LatitudeApi from "../index.js";

export type CreateScoreBody = LatitudeApi.CreateCustomScoreBody | LatitudeApi.CreateEvaluationScoreBody;
