// This file was auto-generated by Fern from our API Definition.

export interface DatasetRow {
    /** Stable row identifier. */
    rowId: string;
    /** Dataset this row belongs to. */
    datasetId: string;
    /** Free-form cell value. Either a plain string or an arbitrary JSON object. */
    input: DatasetRow.Input;
    /** Free-form cell value. Either a plain string or an arbitrary JSON object. */
    output: DatasetRow.Output;
    /** The correct answer for this row. Curators fill this in by hand; it is not derived from `output`. */
    expectedOutput: DatasetRow.ExpectedOutput;
    /** Free-form cell value. Either a plain string or an arbitrary JSON object. */
    metadata: DatasetRow.Metadata;
    /** ISO-8601 timestamp at which the row was inserted. */
    createdAt: string;
    /** Dataset version this row belongs to. */
    version: number;
}

export namespace DatasetRow {
    /**
     * Free-form cell value. Either a plain string or an arbitrary JSON object.
     */
    export type Input = string | Record<string, unknown>;
    /**
     * Free-form cell value. Either a plain string or an arbitrary JSON object.
     */
    export type Output = string | Record<string, unknown>;
    /**
     * The correct answer for this row. Curators fill this in by hand; it is not derived from `output`.
     */
    export type ExpectedOutput = string | Record<string, unknown>;
    /**
     * Free-form cell value. Either a plain string or an arbitrary JSON object.
     */
    export type Metadata = string | Record<string, unknown>;
}
