// This file was auto-generated by Fern from our API Definition.

export interface EvaluationScoreResponse {
    id: string;
    organizationId: string;
    projectId: string;
    sessionId?: string | undefined;
    traceId?: string | undefined;
    spanId?: string | undefined;
    simulationId?: string | undefined;
    issueId?: string | undefined;
    value: number;
    passed: boolean;
    feedback: string;
    error?: string | undefined;
    errored: boolean;
    duration: number;
    tokens: number;
    cost: number;
    draftedAt?: string | undefined;
    annotatorId?: string | undefined;
    createdAt: string;
    updatedAt: string;
    sourceId: string;
    metadata: EvaluationScoreResponse.Metadata;
}

export namespace EvaluationScoreResponse {
    export interface Metadata {
        evaluationHash: string;
    }
}
