// This file was auto-generated by Fern from our API Definition.

import type * as Latitude from "../index.js";

export interface ExperimentSignalsMetrics {
    /** Distinct signals raised on the variant's sessions — count; lower is better. */
    distinct: ExperimentSignalsMetrics.Distinct;
    /** Total signal occurrences — count; lower is better. */
    occurrences: ExperimentSignalsMetrics.Occurrences;
    /** Fraction of sessions with at least one signal — fraction (0–1); lower is better. */
    affected_sessions_rate: ExperimentSignalsMetrics.AffectedSessionsRate;
    /** Fraction of traces with at least one signal — fraction (0–1); lower is better. */
    affected_traces_rate: ExperimentSignalsMetrics.AffectedTracesRate;
    /** Fraction of users with at least one signal — fraction (0–1); lower is better. */
    affected_users: ExperimentSignalsMetrics.AffectedUsers;
    /** Total model cost of sessions carrying a signal — USD; lower is better. */
    cost_impact: ExperimentSignalsMetrics.CostImpact;
    /** Top signals by occurrence count. */
    top: Latitude.ExperimentTopListItem[];
}

export namespace ExperimentSignalsMetrics {
    /**
     * Distinct signals raised on the variant's sessions — count; lower is better.
     */
    export interface Distinct {
        /** Value in the metric's unit; `null` when empty or not computable. */
        value: number | null;
        delta: Latitude.MetricDelta | null;
    }

    /**
     * Total signal occurrences — count; lower is better.
     */
    export interface Occurrences {
        /** Value in the metric's unit; `null` when empty or not computable. */
        value: number | null;
        delta: Latitude.MetricDelta | null;
    }

    /**
     * Fraction of sessions with at least one signal — fraction (0–1); lower is better.
     */
    export interface AffectedSessionsRate {
        /** Value in the metric's unit; `null` when empty or not computable. */
        value: number | null;
        delta: Latitude.MetricDelta | null;
    }

    /**
     * Fraction of traces with at least one signal — fraction (0–1); lower is better.
     */
    export interface AffectedTracesRate {
        /** Value in the metric's unit; `null` when empty or not computable. */
        value: number | null;
        delta: Latitude.MetricDelta | null;
    }

    /**
     * Fraction of users with at least one signal — fraction (0–1); lower is better.
     */
    export interface AffectedUsers {
        /** Value in the metric's unit; `null` when empty or not computable. */
        value: number | null;
        delta: Latitude.MetricDelta | null;
    }

    /**
     * Total model cost of sessions carrying a signal — USD; lower is better.
     */
    export interface CostImpact {
        /** Value in the metric's unit; `null` when empty or not computable. */
        value: number | null;
        delta: Latitude.MetricDelta | null;
    }
}
