// This file was auto-generated by Fern from our API Definition.

import type * as Latitude from "../index.js";

export interface ExperimentListItem {
    /** Stable experiment identifier. */
    id: string;
    /** Organization that owns this experiment. */
    organizationId: string;
    /** Project this experiment belongs to. */
    projectId: string;
    /** URL-safe slug derived from `name`. Unique within the project. */
    slug: string;
    /** Human-readable name. */
    name: string;
    /** Free-form description. Empty string when not set. */
    description: string;
    /** Ordered variants. Exactly one carries the baseline flag when the list is non-empty. */
    variants: Latitude.ExperimentVariant[];
    /** ISO-8601 timestamp of creation. */
    createdAt: string;
    /** ISO-8601 timestamp of the last update. */
    updatedAt: string;
    /** Number of variants in the experiment. */
    variantCount: number;
    /** Distinct sessions across the union of every variant's population (a session in several variants counts once). */
    sessionsDistinct: number;
    /** Distinct users across the union of every variant's population (a user in several variants counts once). */
    usersDistinct: number;
}
