// This file was auto-generated by Fern from our API Definition.

/**
 * What the import was asked to bring in, snapshotted when it was created.
 */
export interface ImportConfig {
    /** Id of the project on the platform the import reads from. */
    sourceProjectId: string;
    /** Name of the platform project, as shown in Latitude. */
    sourceProjectName: string;
    /** Platform region the import runs against. */
    sourceRegion: string;
    /** ISO-8601 start of the imported time range (inclusive). */
    rangeFrom: string;
    /** ISO-8601 end of the imported time range (exclusive). */
    rangeTo: string;
    /** Most traces this import will bring in, newest first. */
    maxTraces: number;
    /** LangSmith only: run metadata key that groups traces into sessions. `null` elsewhere. */
    sessionMetadataKey: string | null;
}
