// This file was auto-generated by Fern from our API Definition.

export interface IssueTrendBucket {
    /** UTC day bucket (`YYYY-MM-DD`). */
    bucket: string;
    /** Number of occurrences within the bucket. */
    count: number;
}
