// This file was auto-generated by Fern from our API Definition.

export interface LangfuseImportCredentials {
    /** Langfuse Cloud region the account lives in. */
    region: LangfuseImportCredentials.Region;
    /** Langfuse project public key (`pk-lf-…`). */
    publicKey: string;
    /** Langfuse project secret key (`sk-lf-…`). */
    secretKey: string;
}

export namespace LangfuseImportCredentials {
    /** Langfuse Cloud region the account lives in. */
    export const Region = {
        Eu: "eu",
        Us: "us",
        Jp: "jp",
        HipaaUs: "hipaa-us",
    } as const;
    export type Region = (typeof Region)[keyof typeof Region];
}
