// This file was auto-generated by Fern from our API Definition.

import type * as Latitude from "../index.js";

export interface ListImportsResponse {
    /** The project's imports, newest first. */
    imports: Latitude.Import[];
}
