// This file was auto-generated by Fern from our API Definition.

export interface MemoryStoreUser {
    /** End-user identifier that accessed the store. */
    userId: string;
    /** ISO-8601 timestamp of the user's most recent access (read or write). */
    lastAccessedAt: string;
}
