// This file was auto-generated by Fern from our API Definition.

import type * as Latitude from "../index.js";

/**
 * Rule configuration used when the monitor is evaluated.
 */
export interface MonitorConfig {
    /** Filters applied by the monitor rule. */
    filterSet?: Record<string, Latitude.FilterCondition[]> | undefined;
    /** Semantic query applied by inline monitor targets. */
    query?: (string | null) | undefined;
    /** Metric evaluated by threshold and escalating monitor rules. */
    metric?: Latitude.MonitorConfigMetric | undefined;
    condition?: Latitude.AlertCondition | undefined;
}
