// This file was auto-generated by Fern from our API Definition.

import type * as LatitudeApi from "../index.js";

export interface Monitor {
    /** Stable monitor identifier. */
    id: string;
    /** Organization that owns this monitor. */
    organizationId: string;
    /** Project this monitor belongs to. */
    projectId: string;
    /** URL-safe slug derived from `name`, unique within the project among active monitors. */
    slug: string;
    /** Human-readable name. */
    name: string;
    /** Free-form description. Empty string when unset. */
    description: string;
    /** `true` for the three auto-provisioned system monitors (issue discovered / regressed / escalating), which cannot be deleted or restructured — only muted, and their alerts' condition values tuned. `false` for monitors you create. */
    system: boolean;
    /** The monitor's active firing rules. Always at least one. */
    alerts: LatitudeApi.MonitorAlert[];
    /** ISO-8601 timestamp at which the monitor was muted, or `null` when active. A muted monitor still records incidents but sends no notifications. */
    mutedAt?: string | undefined;
    /** ISO-8601 timestamp at which the monitor was deleted, or `null` while active. */
    deletedAt?: string | undefined;
    /** ISO-8601 timestamp of creation. */
    createdAt: string;
    /** ISO-8601 timestamp of the last update. */
    updatedAt: string;
}
