// This file was auto-generated by Fern from our API Definition.

import type * as Latitude from "../index.js";

export interface MonitorList {
    /** Matching monitors. */
    items: Latitude.Monitor[];
}
