// This file was auto-generated by Fern from our API Definition.

import type * as LatitudeApi from "../index.js";

/**
 * Additional filters applied when evaluating the monitor.
 */
export type MonitorFilterSet = Record<string, LatitudeApi.FilterCondition[]>;
