// This file was auto-generated by Fern from our API Definition.

import type * as LatitudeApi from "../index.js";

/**
 * Filters that select the target rows. Use `{}` for all users; use `operation = execute_tool` for all tools.
 */
export type MonitorFilterSet = Record<string, LatitudeApi.FilterCondition[]> | undefined;
