// This file was auto-generated by Fern from our API Definition.

/**
 * The absolute window the metrics were computed over.
 */
export interface ResolvedRange {
    /** ISO-8601 start of the resolved window. */
    fromIso: string;
    /** ISO-8601 end of the resolved window. */
    toIso: string;
}
