// This file was auto-generated by Fern from our API Definition.

import type * as Latitude from "../index.js";

export interface SessionAssessmentCostFamilySummary {
    /** Cost family this evidence belongs to: spend, context, tools, memory, or recovery. */
    family: SessionAssessmentCostFamilySummary.Family;
    /** Aggregate measurement state across this family's metrics. This is not a health label. */
    measurementState: SessionAssessmentCostFamilySummary.MeasurementState;
    /** Evidence items carrying this family. */
    observedItemCount: number;
    /** Aggregate session-safe readings for this family's metrics. */
    metrics: Latitude.SessionAssessmentCostMetricEvidence[];
    /** Family impact in its own unit, when aggregated. */
    nativeImpact?: SessionAssessmentCostFamilySummary.NativeImpact | undefined;
}

export namespace SessionAssessmentCostFamilySummary {
    /** Cost family this evidence belongs to: spend, context, tools, memory, or recovery. */
    export const Family = {
        Spend: "spend",
        Context: "context",
        Tools: "tools",
        Memory: "memory",
        Recovery: "recovery",
    } as const;
    export type Family = (typeof Family)[keyof typeof Family];
    /** Aggregate measurement state across this family's metrics. This is not a health label. */
    export const MeasurementState = {
        Measured: "measured",
        Partial: "partial",
        Unmeasured: "unmeasured",
        NotApplicable: "notApplicable",
    } as const;
    export type MeasurementState = (typeof MeasurementState)[keyof typeof MeasurementState];

    /**
     * Family impact in its own unit, when aggregated.
     */
    export interface NativeImpact {
        /** Unit both the point estimate and its bounds are expressed in. */
        unit: string;
        /** Point estimate in `unit`. */
        point: number;
        /** Lower bound in `unit`, when the estimate is bounded. */
        lower?: number | undefined;
        /** Upper bound in `unit`, when the estimate is bounded. */
        upper?: number | undefined;
        /** What the bounds mean. `identificationBound` is the range the evidence cannot narrow further; `confidenceInterval` is sampling uncertainty. Present whenever a bound is. */
        interpretation?: NativeImpact.Interpretation | undefined;
    }

    export namespace NativeImpact {
        /** What the bounds mean. `identificationBound` is the range the evidence cannot narrow further; `confidenceInterval` is sampling uncertainty. Present whenever a bound is. */
        export const Interpretation = {
            IdentificationBound: "identificationBound",
            ConfidenceInterval: "confidenceInterval",
        } as const;
        export type Interpretation = (typeof Interpretation)[keyof typeof Interpretation];
    }
}
