// This file was auto-generated by Fern from our API Definition.

import type * as Latitude from "../index.js";

export interface SessionAnalyticsSpans {
    /** Total number of spans. */
    total: number;
    /** Number of spans per bucket. */
    buckets: Latitude.SessionAnalyticsBucket[];
}
