// This file was auto-generated by Fern from our API Definition.

import type * as Latitude from "../index.js";

export type SessionAssessmentDimensionSummary =
    | Latitude.SessionAssessmentDimensionSummary.Outcome
    | Latitude.SessionAssessmentDimensionSummary.Reliability
    | Latitude.SessionAssessmentDimensionSummary.Cost
    | Latitude.SessionAssessmentDimensionSummary.Speed
    | Latitude.SessionAssessmentDimensionSummary.Safety;

export namespace SessionAssessmentDimensionSummary {
    export interface Outcome {
        scoreDimension: "outcome";
        /** Evidence counts grouped by direction. */
        evidenceCounts: SessionAssessmentDimensionSummaryOutcome.EvidenceCounts;
        /** Evidence counts grouped by measurement state. */
        measurementCounts: SessionAssessmentDimensionSummaryOutcome.MeasurementCounts;
        /** Reader coverage for this dimension. */
        coverage: SessionAssessmentDimensionSummaryOutcome.Coverage;
        /** Resolved task outcome when available. */
        taskOutcome?: SessionAssessmentDimensionSummaryOutcome.TaskOutcome | undefined;
    }

    export namespace SessionAssessmentDimensionSummaryOutcome {
        /**
         * Evidence counts grouped by direction.
         */
        export interface EvidenceCounts {
            /** Number of positive evidence effects. */
            positive: number;
            /** Number of negative evidence effects. */
            negative: number;
            /** Number of contextual evidence effects. */
            context: number;
        }

        /**
         * Evidence counts grouped by measurement state.
         */
        export interface MeasurementCounts {
            /** Number of directly observed effects. */
            observed: number;
            /** Number of estimated effects. */
            estimated: number;
            /** Number of effects without a numeric measurement. */
            notMeasured: number;
        }

        /** Reader coverage for this dimension. */
        export const Coverage = {
            Complete: "complete",
            Partial: "partial",
            NotExamined: "notExamined",
        } as const;
        export type Coverage = (typeof Coverage)[keyof typeof Coverage];

        /**
         * Resolved task outcome when available.
         */
        export interface TaskOutcome {
            /** Observed task verdict when available. */
            verdict?: TaskOutcome.Verdict | undefined;
            /** Estimated success probability when available. */
            probability?: number | undefined;
        }

        export namespace TaskOutcome {
            /** Observed task verdict when available. */
            export const Verdict = {
                Success: "success",
                Failure: "failure",
            } as const;
            export type Verdict = (typeof Verdict)[keyof typeof Verdict];
        }
    }

    export interface Reliability {
        scoreDimension: "reliability";
        /** Evidence counts grouped by direction. */
        evidenceCounts: SessionAssessmentDimensionSummaryReliability.EvidenceCounts;
        /** Evidence counts grouped by measurement state. */
        measurementCounts: SessionAssessmentDimensionSummaryReliability.MeasurementCounts;
        /** Reader coverage for this dimension. */
        coverage: SessionAssessmentDimensionSummaryReliability.Coverage;
        /** Resolved completion status. */
        completion: SessionAssessmentDimensionSummaryReliability.Completion;
        /** Number of recovered operational incidents. */
        recoveredIncidentCount: number;
        /** Number of unrecovered operational incidents. */
        unrecoveredIncidentCount: number;
    }

    export namespace SessionAssessmentDimensionSummaryReliability {
        /**
         * Evidence counts grouped by direction.
         */
        export interface EvidenceCounts {
            /** Number of positive evidence effects. */
            positive: number;
            /** Number of negative evidence effects. */
            negative: number;
            /** Number of contextual evidence effects. */
            context: number;
        }

        /**
         * Evidence counts grouped by measurement state.
         */
        export interface MeasurementCounts {
            /** Number of directly observed effects. */
            observed: number;
            /** Number of estimated effects. */
            estimated: number;
            /** Number of effects without a numeric measurement. */
            notMeasured: number;
        }

        /** Reader coverage for this dimension. */
        export const Coverage = {
            Complete: "complete",
            Partial: "partial",
            NotExamined: "notExamined",
        } as const;
        export type Coverage = (typeof Coverage)[keyof typeof Coverage];
        /** Resolved completion status. */
        export const Completion = {
            Usable: "usable",
            TerminalFailure: "terminalFailure",
            Undetermined: "undetermined",
        } as const;
        export type Completion = (typeof Completion)[keyof typeof Completion];
    }

    export interface Cost {
        scoreDimension: "cost";
        /** Evidence counts grouped by direction. */
        evidenceCounts: SessionAssessmentDimensionSummaryCost.EvidenceCounts;
        /** Evidence counts grouped by measurement state. */
        measurementCounts: SessionAssessmentDimensionSummaryCost.MeasurementCounts;
        /** Reader coverage for this dimension. */
        coverage: SessionAssessmentDimensionSummaryCost.Coverage;
        /** Total observed session spend in microcents. */
        observedMicrocents?: number | undefined;
        /** Directly measured avoidable spend. */
        measuredAvoidableMicrocents?: number | undefined;
        /** Estimated avoidable spend. */
        estimatedAvoidableMicrocents?: number | undefined;
        /** All five Cost families, always present, with raw metric readings and their measurement state. */
        families: Latitude.SessionAssessmentCostFamilySummary[];
    }

    export namespace SessionAssessmentDimensionSummaryCost {
        /**
         * Evidence counts grouped by direction.
         */
        export interface EvidenceCounts {
            /** Number of positive evidence effects. */
            positive: number;
            /** Number of negative evidence effects. */
            negative: number;
            /** Number of contextual evidence effects. */
            context: number;
        }

        /**
         * Evidence counts grouped by measurement state.
         */
        export interface MeasurementCounts {
            /** Number of directly observed effects. */
            observed: number;
            /** Number of estimated effects. */
            estimated: number;
            /** Number of effects without a numeric measurement. */
            notMeasured: number;
        }

        /** Reader coverage for this dimension. */
        export const Coverage = {
            Complete: "complete",
            Partial: "partial",
            NotExamined: "notExamined",
        } as const;
        export type Coverage = (typeof Coverage)[keyof typeof Coverage];
    }

    export interface Speed {
        scoreDimension: "speed";
        /** Evidence counts grouped by direction. */
        evidenceCounts: SessionAssessmentDimensionSummarySpeed.EvidenceCounts;
        /** Evidence counts grouped by measurement state. */
        measurementCounts: SessionAssessmentDimensionSummarySpeed.MeasurementCounts;
        /** Reader coverage for this dimension. */
        coverage: SessionAssessmentDimensionSummarySpeed.Coverage;
        /** Observed critical-path duration in nanoseconds. */
        observedCriticalPathNs?: number | undefined;
        /** Directly measured avoidable duration. */
        measuredAvoidableNs?: number | undefined;
        /** Estimated avoidable duration. */
        estimatedAvoidableNs?: number | undefined;
    }

    export namespace SessionAssessmentDimensionSummarySpeed {
        /**
         * Evidence counts grouped by direction.
         */
        export interface EvidenceCounts {
            /** Number of positive evidence effects. */
            positive: number;
            /** Number of negative evidence effects. */
            negative: number;
            /** Number of contextual evidence effects. */
            context: number;
        }

        /**
         * Evidence counts grouped by measurement state.
         */
        export interface MeasurementCounts {
            /** Number of directly observed effects. */
            observed: number;
            /** Number of estimated effects. */
            estimated: number;
            /** Number of effects without a numeric measurement. */
            notMeasured: number;
        }

        /** Reader coverage for this dimension. */
        export const Coverage = {
            Complete: "complete",
            Partial: "partial",
            NotExamined: "notExamined",
        } as const;
        export type Coverage = (typeof Coverage)[keyof typeof Coverage];
    }

    export interface Safety {
        scoreDimension: "safety";
        /** Evidence counts grouped by direction. */
        evidenceCounts: SessionAssessmentDimensionSummarySafety.EvidenceCounts;
        /** Evidence counts grouped by measurement state. */
        measurementCounts: SessionAssessmentDimensionSummarySafety.MeasurementCounts;
        /** Reader coverage for this dimension. */
        coverage: SessionAssessmentDimensionSummarySafety.Coverage;
        /** Number of safety exposures. */
        exposureCount: number;
        /** Number of successful safety defenses. */
        successfulDefenseCount: number;
        /** Number of confirmed harmful outcomes. */
        confirmedHarmCount: number;
    }

    export namespace SessionAssessmentDimensionSummarySafety {
        /**
         * Evidence counts grouped by direction.
         */
        export interface EvidenceCounts {
            /** Number of positive evidence effects. */
            positive: number;
            /** Number of negative evidence effects. */
            negative: number;
            /** Number of contextual evidence effects. */
            context: number;
        }

        /**
         * Evidence counts grouped by measurement state.
         */
        export interface MeasurementCounts {
            /** Number of directly observed effects. */
            observed: number;
            /** Number of estimated effects. */
            estimated: number;
            /** Number of effects without a numeric measurement. */
            notMeasured: number;
        }

        /** Reader coverage for this dimension. */
        export const Coverage = {
            Complete: "complete",
            Partial: "partial",
            NotExamined: "notExamined",
        } as const;
        export type Coverage = (typeof Coverage)[keyof typeof Coverage];
    }
}
