// This file was auto-generated by Fern from our API Definition.

import type * as Latitude from "../index.js";

export interface SessionAnalyticsTokens {
    /** Total tokens across all LLM spans. */
    total: number;
    /** Tokens per bucket across all LLM spans. */
    buckets: Latitude.SessionAnalyticsBucket[];
}
