// This file was auto-generated by Fern from our API Definition.

/**
 * The verdict submitted for this signal, or `null` when none has been submitted yet.
 */
export interface SignalFeedback {
    /** Normalized score for the signal's usefulness, in `[0, 1]`. */
    value: number;
    /** `true` when the signal is a real problem; `false` when it is a false positive. */
    passed: boolean;
    /** Reason given for the verdict. Empty when none was provided. */
    feedback: string;
}
