// This file was auto-generated by Fern from our API Definition.

import type * as LatitudeApi from "../index.js";

export interface SignalAnalyticsResponse {
    ongoing: LatitudeApi.SignalAnalyticsOngoing;
    "new": LatitudeApi.SignalAnalyticsNew;
    escalating: LatitudeApi.SignalAnalyticsEscalating;
    regressed: LatitudeApi.SignalAnalyticsRegressed;
    resolved: LatitudeApi.SignalAnalyticsResolved;
    occurrences: LatitudeApi.SignalAnalyticsOccurrences;
}
