// This file was auto-generated by Fern from our API Definition.

export interface TraceAnalyticsBucket {
    /** ISO-8601 UTC timestamp of the bucket's start. */
    bucket: string;
    /** Metric value for this bucket. */
    value: number;
}
