// This file was auto-generated by Fern from our API Definition.

export interface UpdateSignalResponse {
    /** Updated signal id. */
    id: string;
    /** URL-safe identifier (stable across updates). */
    slug: string;
    /** Whether any field actually changed. */
    changed: boolean;
}
