// This file was auto-generated by Fern from our API Definition.

export interface UserProfileResponse {
    /** The end-user's identifier, as reported on their traces' `user_id`. */
    userId: string;
    /** Latest non-empty email seen on the user's traces. Empty when never reported. */
    userEmail: string;
    /** ISO-8601 timestamp of the user's first trace ever. */
    firstSeenAt: string;
    /** ISO-8601 timestamp of the user's most recent trace ever. */
    lastSeenAt: string;
    /** Lifetime traces attributed to the user. */
    traceCount: number;
    /** Distinct sessions in which the user produced at least one trace. */
    sessionCount: number;
    /** Of `sessionCount`, sessions with at least one errored trace. */
    errorSessionCount: number;
    /** Total tokens across the user's traces. */
    tokensTotal: number;
    /** Input (prompt) tokens across the user's traces. */
    tokensInput: number;
    /** Output (completion) tokens across the user's traces. */
    tokensOutput: number;
    /** Total cost across the user's traces, in microcents. */
    costTotalMicrocents: number;
    /** Mean per-trace duration, in nanoseconds. */
    avgDurationNs: number;
    /** Distinct UTC days with at least one trace. */
    activeDays: number;
}
