'use server'

import { z } from 'zod'
import {
  ChainStepResponse,
  CLOUD_MESSAGES,
  LogSources,
} from '@latitude-data/core/browser'
import { BadRequestError } from '@latitude-data/core/lib/errors'
import { env } from '@latitude-data/env'
import { createSdk } from '$/app/(private)/_lib/createSdk'
import { getCurrentUserOrError } from '$/services/auth/getCurrentUser'
import { authProcedure } from '$/actions/procedures'
import { createDatasetFromJson } from '@latitude-data/core/services/datasetsV2/createFromJson'

export const generateDatasetAction = authProcedure
  .createServerAction()
  .input(
    z.object({
      parameters: z.string(),
      description: z.string(),
      rowCount: z.number(),
      name: z.string(),
    }),
  )
  .handler(async ({ input }) => {
    if (!env.LATITUDE_CLOUD) {
      throw new BadRequestError(CLOUD_MESSAGES.autogenerateDatasets)
    }
    if (!env.COPILOT_PROJECT_ID) {
      throw new BadRequestError('COPILOT_PROJECT_ID is not set')
    }
    if (!env.COPILOT_DATASET_GENERATOR_PROMPT_PATH) {
      throw new BadRequestError(
        'COPILOT_DATASET_GENERATOR_PROMPT_PATH is not set',
      )
    }
    if (!env.COPILOT_WORKSPACE_API_KEY) {
      throw new BadRequestError('COPILOT_WORKSPACE_API_KEY is not set')
    }

    const { user, workspace } = await getCurrentUserOrError()
    const sdk = await createSdk({
      workspace,
      apiKey: env.COPILOT_WORKSPACE_API_KEY,
      projectId: env.COPILOT_PROJECT_ID,
      __internal: { source: LogSources.Playground },
    }).then((r) => r.unwrap())

    const sdkResponse = await sdk.prompts.run(
      env.COPILOT_DATASET_GENERATOR_PROMPT_PATH,
      {
        stream: false,
        parameters: {
          row_count: input.rowCount,
          parameters: input.parameters,
          user_message: input.description,
        },
      },
    )
    const sdkResult = sdkResponse

    if (!sdkResult) {
      throw new BadRequestError(
        'Something went wrong generating the Dataset preview',
      )
    }

    const response = sdkResult.response as ChainStepResponse<'object'>
    const name = input.name
    const result = await createDatasetFromJson({
      author: user,
      workspace,
      data: {
        name,
        rows: response.object.rows,
      },
    })

    if (result.error) {
      throw result.error
    }

    return result.value
  })
