// This file was auto-generated by Fern from our API Definition.

import type * as Latitude from "../../../../index.js";

/**
 * @example
 *     {
 *         credentials: {
 *             kind: "langfuse",
 *             region: "eu",
 *             publicKey: "publicKey",
 *             secretKey: "secretKey"
 *         }
 *     }
 */
export interface RetryImportBody {
    /** Platform credentials, required again because they are not stored after an import ends. Must use the same region as the original import. */
    credentials: Latitude.RetryImportBodyCredentials;
}
