{{- if and .Values.api.enabled .Values.api.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "latitude.fullname" . }}-api
  labels:
    {{- include "latitude.componentLabels" (merge (dict "componentName" "api") .) | nindent 4 }}
  {{- with .Values.api.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.api.ingress.className }}
  ingressClassName: {{ .Values.api.ingress.className }}
  {{- end }}
  {{- if .Values.api.ingress.tls }}
  tls:
    {{- toYaml .Values.api.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.api.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "latitude.fullname" $ }}-api
                port:
                  name: http
          {{- end }}
    {{- end }}
{{- end }}
