apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "latitude.fullname" . }}-env
  labels:
    {{- include "latitude.labels" . | nindent 4 }}
  {{- if .Values.migrations.enabled }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
  {{- end }}
data:
  {{- /* Compute defaults based on ingress if not explicitly set */ -}}
  {{- $webHost := (index .Values.ingress.hosts "web") | default "" -}}
  {{- $scheme := ternary "https" "http" .Values.ingress.tls.enabled -}}
  {{- $defaultAppURL := printf "%s://%s" $scheme $webHost -}}
  {{- $wsHost := (index .Values.ingress.hosts "websockets") | default (printf "%s-websockets" (include "latitude.fullname" .)) -}}
  {{- $defaultWsURL := printf "%s://%s" $scheme $wsHost -}}

  {{- range $k, $v := .Values.env }}
  {{- if not (empty $v) }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- end }}

  {{- if or (not (hasKey .Values.env "APP_URL")) (empty (get .Values.env "APP_URL")) }}
  APP_URL: {{ $defaultAppURL | quote }}
  {{- end }}

  {{- if or (not (hasKey .Values.env "WEBSOCKETS_SERVER")) (empty (get .Values.env "WEBSOCKETS_SERVER")) }}
  WEBSOCKETS_SERVER: {{ $defaultWsURL | quote }}
  {{- end }}

  {{- if or (not (hasKey .Values.env "GOOGLE_REDIRECT_URI")) (empty (get .Values.env "GOOGLE_REDIRECT_URI")) }}
  GOOGLE_REDIRECT_URI: {{ printf "%s/api/auth/google/callback" (default $defaultAppURL .Values.env.APP_URL) | quote }}
  {{- end }}
