apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "latitude.fullname" . }}-workers
  labels:
    {{- include "latitude.labels" . | nindent 4 }}
    app.kubernetes.io/component: workers
spec:
  replicas: {{ .Values.workers.replicaCount }}
  selector:
    matchLabels:
      {{- include "latitude.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: workers
  template:
    metadata:
      labels:
        {{- include "latitude.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: workers
    spec:
      {{- if .Values.global.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.global.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
        - name: workers
          image: {{ .Values.global.image.registry }}/workers:{{ .Values.global.image.tag }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "latitude.fullname" . }}-env
            - secretRef:
                name: {{ include "latitude.fullname" . }}-env-secrets
          {{- if .Values.global.sharedStorage.enabled }}
          volumeMounts:
            - name: shared
              mountPath: /app/storage/files
            - name: shared
              mountPath: /app/apps/web/public/files
          {{- end }}
          resources:
            {{- toYaml .Values.workers.resources | nindent 12 }}
      {{- if .Values.global.sharedStorage.enabled }}
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: {{ include "latitude.fullname" . }}-shared
      {{- end }}
