{{- if .Values.ingest.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "latitude.fullname" . }}-ingest
  labels:
    {{- include "latitude.componentLabels" (merge (dict "componentName" "ingest") .) | nindent 4 }}
spec:
  {{- if not .Values.ingest.autoscaling.enabled }}
  replicas: {{ .Values.ingest.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "latitude.selectorLabels" (merge (dict "componentName" "ingest") .) | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.ingest.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "latitude.selectorLabels" (merge (dict "componentName" "ingest") .) | nindent 8 }}
        {{- with .Values.ingest.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "latitude.serviceAccountName" . }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: ingest
          image: {{ include "latitude.image" (dict "component" .Values.ingest "global" .Values.global "chart" .Chart) }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.ingest.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "latitude.configmapName" . }}
            - secretRef:
                name: {{ include "latitude.secretName" . }}
          {{- with .Values.ingest.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.ingest.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.ingest.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.ingest.resources | nindent 12 }}
      {{- with .Values.ingest.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ingest.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ingest.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
