{{- if and .Values.ingest.enabled .Values.ingest.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "latitude.fullname" . }}-ingest
  labels:
    {{- include "latitude.componentLabels" (merge (dict "componentName" "ingest") .) | nindent 4 }}
  {{- with .Values.ingest.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingest.ingress.className }}
  ingressClassName: {{ .Values.ingest.ingress.className }}
  {{- end }}
  {{- if .Values.ingest.ingress.tls }}
  tls:
    {{- toYaml .Values.ingest.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ingest.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "latitude.fullname" $ }}-ingest
                port:
                  name: http
          {{- end }}
    {{- end }}
{{- end }}
