{{- if and .Values.ingest.enabled .Values.ingest.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "latitude.fullname" . }}-ingest
  labels:
    {{- include "latitude.componentLabels" (merge (dict "componentName" "ingest") .) | nindent 4 }}
spec:
  minAvailable: {{ .Values.ingest.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "latitude.selectorLabels" (merge (dict "componentName" "ingest") .) | nindent 6 }}
{{- end }}
