{{- if and .Values.ingress.enabled .Values.ingress.hosts.gateway }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "latitude.fullname" . }}-gateway
  labels:
    {{- include "latitude.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.hosts.gateway }}
      {{- if .Values.ingress.tls.secretName }}
      secretName: {{ .Values.ingress.tls.secretName }}
      {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.hosts.gateway }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "latitude.fullname" . }}-gateway
                port:
                  number: {{ .Values.service.gateway.port }}
{{- end }}
