apiVersion: v1
kind: Secret
metadata:
  name: {{ include "latitude.fullname" . }}-env-secrets
  labels:
    {{- include "latitude.labels" . | nindent 4 }}
  {{- if .Values.migrations.enabled }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
  {{- end }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secretEnv }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
