{{- if .Values.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "latitude.fullname" . }}-web
  labels:
    {{- include "latitude.componentLabels" (merge (dict "componentName" "web") .) | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "latitude.selectorLabels" (merge (dict "componentName" "web") .) | nindent 4 }}
{{- end }}
