import { cuidSchema, ScoreId } from "@domain/shared"
import { sessionIdSchema, spanIdSchema, traceIdSchema } from "@domain/spans"
import { z } from "zod"
import {
  ANNOTATION_SCORE_PARTIAL_SOURCE_IDS,
  SCORE_PUBLICATION_DEBOUNCE,
  SCORE_SOURCE_ID_MAX_LENGTH,
  SCORE_SOURCES,
} from "./constants.ts"

const scoreSourceIdSchema = z.string().min(1).max(SCORE_SOURCE_ID_MAX_LENGTH)
export const scoreIdSchema = cuidSchema.transform(ScoreId)

export const scoreSourceSchema = z.enum(SCORE_SOURCES)
export type ScoreSource = z.infer<typeof scoreSourceSchema>

export const annotationScorePartialSourceIdSchema = z.enum(ANNOTATION_SCORE_PARTIAL_SOURCE_IDS)
export type AnnotationScorePartialSourceId = z.infer<typeof annotationScorePartialSourceIdSchema>

export const annotationScoreSourceIdSchema = z.union([annotationScorePartialSourceIdSchema, cuidSchema])
export type AnnotationScoreSourceId = z.infer<typeof annotationScoreSourceIdSchema>

export const scoreValueSchema = z.number().min(0).max(1)

export const baseScoreMetadataSchema = z.object({
  // common metadata shared by all score sources
})
export type BaseScoreMetadata = z.infer<typeof baseScoreMetadataSchema>

export const evaluationScoreMetadataSchema = baseScoreMetadataSchema.extend({
  evaluationHash: z.string(), // hash of the script so we know whether this score was generated by the current version
})
export type EvaluationScoreMetadata = z.infer<typeof evaluationScoreMetadataSchema>

export const annotationScoreMetadataSchema = baseScoreMetadataSchema
  .extend({
    rawFeedback: z.string(), // original feedback text before enrichment; human-authored for human drafts/final annotations, model-authored for system-created drafts
    messageIndex: z.number().int().nonnegative(), // message index used to anchor the annotation in the conversation UI
    partIndex: z.number().int().nonnegative().optional(), // optional GenAI `parts[]` index inside the target message
    startOffset: z.number().int().nonnegative().optional(), // optional start offset for substring annotations within a textual part
    endOffset: z.number().int().nonnegative().optional(), // optional end offset for substring annotations within a textual part
  })
  .superRefine((metadata, ctx) => {
    const { endOffset, startOffset } = metadata
    const hasStartOffset = startOffset !== undefined
    const hasEndOffset = endOffset !== undefined

    if (hasStartOffset !== hasEndOffset) {
      ctx.addIssue({
        code: "custom",
        message: "startOffset and endOffset must be provided together",
        path: hasStartOffset ? ["endOffset"] : ["startOffset"],
      })
    }

    if (startOffset !== undefined && endOffset !== undefined && startOffset > endOffset) {
      ctx.addIssue({
        code: "custom",
        message: "endOffset must be greater than or equal to startOffset",
        path: ["endOffset"],
      })
    }
  })
export type AnnotationScoreMetadata = z.infer<typeof annotationScoreMetadataSchema>

export const customScoreMetadataSchema = z.record(z.string(), z.unknown()) // whatever the user wants to store in custom score metadata
export type CustomScoreMetadata = z.infer<typeof customScoreMetadataSchema>

export const scoreMetadataSchemas = {
  evaluation: evaluationScoreMetadataSchema,
  annotation: annotationScoreMetadataSchema,
  custom: customScoreMetadataSchema,
} as const

const baseScoreSchema = z.object({
  id: scoreIdSchema, // CUID score identifier
  organizationId: cuidSchema, // owning organization
  projectId: cuidSchema, // owning project
  sessionId: sessionIdSchema.nullable(), // optional session id inherited from instrumentation
  traceId: traceIdSchema.nullable(), // optional trace id inherited from instrumentation
  spanId: spanIdSchema.nullable(), // optional span id inherited from instrumentation
  simulationId: cuidSchema.nullable(), // optional simulation CUID link
  issueId: cuidSchema.nullable(), // optional issue CUID assignment
  value: scoreValueSchema, // normalized [0, 1] score value
  passed: z.boolean(), // true if passed, false if failed or errored
  feedback: z.string(), // clusterable feedback text used by issues
  error: z.string().min(1).nullable(), // canonical error text when the score generation truly errored
  errored: z.boolean(), // maintained in application/domain code on create or update
  duration: z.number().int().nonnegative(), // duration of score generation in nanoseconds
  tokens: z.number().int().nonnegative(), // total LLM token usage for this score generation
  cost: z.number().int().nonnegative(), // total LLM cost in microcents
  draftedAt: z.date().nullable(), // set while the score is still editable or awaiting human confirmation
  createdAt: z.date(), // score creation time
  updatedAt: z.date(), // score update time
})

function validateScoreLifecycle(
  score: {
    readonly error: string | null
    readonly errored: boolean
    readonly passed: boolean
  },
  ctx: z.core.$RefinementCtx<unknown>,
) {
  const hasError = score.error !== null

  if (score.errored !== hasError) {
    ctx.addIssue({
      code: "custom",
      message: "errored must match whether error is present",
      path: ["errored"],
      input: score.errored,
    })
  }

  if (score.passed && hasError) {
    ctx.addIssue({
      code: "custom",
      message: "passed scores cannot include an error",
      path: ["passed"],
      input: score.passed,
    })
  }
}

export const evaluationScoreSchema = baseScoreSchema.extend({
  source: z.literal("evaluation"), // "evaluation" | "annotation" | "custom"
  sourceId: cuidSchema, // evaluation cuid, annotation queue cuid or sentinel `"UI"` / `"API"` values, or custom source tag
  metadata: evaluationScoreMetadataSchema,
})
export type EvaluationScore = z.infer<typeof evaluationScoreSchema>

export const annotationScoreSchema = baseScoreSchema.extend({
  source: z.literal("annotation"), // "evaluation" | "annotation" | "custom"
  sourceId: annotationScoreSourceIdSchema, // evaluation cuid, annotation queue cuid or sentinel `"UI"` / `"API"` values, or custom source tag
  metadata: annotationScoreMetadataSchema,
})
export type AnnotationScore = z.infer<typeof annotationScoreSchema>

export const customScoreSchema = baseScoreSchema.extend({
  source: z.literal("custom"), // "evaluation" | "annotation" | "custom"
  sourceId: scoreSourceIdSchema, // evaluation cuid, annotation queue cuid or sentinel `"UI"` / `"API"` values, or custom source tag
  metadata: customScoreMetadataSchema,
})
export type CustomScore = z.infer<typeof customScoreSchema>

export const scoreSchema = z
  .discriminatedUnion("source", [evaluationScoreSchema, annotationScoreSchema, customScoreSchema])
  .superRefine(validateScoreLifecycle)
export type Score = z.infer<typeof scoreSchema>

export type ScoreMetadata = Score["metadata"]

/** @knipignore - TODO: unignore once used */
export { SCORE_PUBLICATION_DEBOUNCE }
