// This file was auto-generated by Fern from our API Definition.

export const IncidentsListRequestKindsItem = {
    IssueNew: "issue.new",
    IssueRegressed: "issue.regressed",
    IssueEscalating: "issue.escalating",
    SavedSearchMatch: "savedSearch.match",
    SavedSearchThreshold: "savedSearch.threshold",
    SavedSearchEscalating: "savedSearch.escalating",
    EventMatched: "event.matched",
    MetricThreshold: "metric.threshold",
    MetricEscalating: "metric.escalating",
} as const;
export type IncidentsListRequestKindsItem =
    (typeof IncidentsListRequestKindsItem)[keyof typeof IncidentsListRequestKindsItem];
