import { insertJsonEachRow } from "../../sql.ts"
import type { Seeder } from "../types.ts"

const WORKSPACE_ID = 1
const API_KEY_ID = 1

// Fixed timestamps for idempotent seeding
const BASE_TIME = "2026-03-05 10:00:00.000000"

const spans = [
  {
    workspace_id: WORKSPACE_ID,
    trace_id: "aabbccdd11223344aabbccdd11223344",
    span_id: "aabbccdd11223344",
    parent_id: null,
    api_key_id: API_KEY_ID,
    name: "gpt-4o completion",
    kind: "llm",
    status: "ok",
    message: null,
    duration_ms: 1240,
    started_at: BASE_TIME,
    ended_at: "2026-03-05 10:00:01.240000",
    source: "openai",
    model: "gpt-4o",
    cost: 520,
    tokens_prompt: 210,
    tokens_cached: null,
    tokens_reasoning: null,
    tokens_completion: 85,
    input: JSON.stringify([{ role: "user", content: "Summarize this document." }]),
    output: JSON.stringify([{ role: "assistant", content: "This document covers..." }]),
    attributes: "{}",
  },
  {
    workspace_id: WORKSPACE_ID,
    trace_id: "aabbccdd11223344aabbccdd11223344",
    span_id: "1122334455667788",
    parent_id: "aabbccdd11223344",
    api_key_id: API_KEY_ID,
    name: "document-chain",
    kind: "chain",
    status: "ok",
    message: null,
    duration_ms: 1350,
    started_at: "2026-03-05 09:59:59.800000",
    ended_at: "2026-03-05 10:00:01.150000",
    source: null,
    model: null,
    cost: null,
    tokens_prompt: null,
    tokens_cached: null,
    tokens_reasoning: null,
    tokens_completion: null,
    input: null,
    output: null,
    attributes: "{}",
  },
  {
    workspace_id: WORKSPACE_ID,
    trace_id: "deadbeefcafe0000deadbeefcafe0000",
    span_id: "cafebabe00000001",
    parent_id: null,
    api_key_id: API_KEY_ID,
    name: "web-search",
    kind: "tool",
    status: "ok",
    message: null,
    duration_ms: 430,
    started_at: "2026-03-05 10:01:00.000000",
    ended_at: "2026-03-05 10:01:00.430000",
    source: null,
    model: null,
    cost: null,
    tokens_prompt: null,
    tokens_cached: null,
    tokens_reasoning: null,
    tokens_completion: null,
    input: JSON.stringify({ query: "latest AI news" }),
    output: JSON.stringify({ results: ["Result 1", "Result 2"] }),
    attributes: "{}",
  },
  {
    workspace_id: WORKSPACE_ID,
    trace_id: "deadbeefcafe0000deadbeefcafe0000",
    span_id: "cafebabe00000002",
    parent_id: "cafebabe00000001",
    api_key_id: API_KEY_ID,
    name: "claude-sonnet-4-6 completion",
    kind: "llm",
    status: "ok",
    message: null,
    duration_ms: 2100,
    started_at: "2026-03-05 10:01:00.500000",
    ended_at: "2026-03-05 10:01:02.600000",
    source: "anthropic",
    model: "claude-sonnet-4-6",
    cost: 980,
    tokens_prompt: 450,
    tokens_cached: 200,
    tokens_reasoning: null,
    tokens_completion: 130,
    input: JSON.stringify([{ role: "user", content: "What are the latest AI developments?" }]),
    output: JSON.stringify([{ role: "assistant", content: "Recent AI developments include..." }]),
    attributes: "{}",
  },
  {
    workspace_id: WORKSPACE_ID,
    trace_id: "f00df00df00df00df00df00df00df00d",
    span_id: "f00df00df00df00d",
    parent_id: null,
    api_key_id: API_KEY_ID,
    name: "gpt-4o-mini completion",
    kind: "llm",
    status: "error",
    message: "Rate limit exceeded",
    duration_ms: 150,
    started_at: "2026-03-05 10:02:00.000000",
    ended_at: "2026-03-05 10:02:00.150000",
    source: "openai",
    model: "gpt-4o-mini",
    cost: null,
    tokens_prompt: null,
    tokens_cached: null,
    tokens_reasoning: null,
    tokens_completion: null,
    input: JSON.stringify([{ role: "user", content: "Hello!" }]),
    output: null,
    attributes: "{}",
  },
]

const seedSpans: Seeder = {
  name: "spans",
  run: (ctx) => insertJsonEachRow(ctx.client, "spans", spans),
}

export const spanSeeders: Seeder[] = [seedSpans]
