import { insertJsonEachRow } from "../../sql.ts"
import type { Seeder } from "../types.ts"

const ORG_ID = "seed-org-1"
const PROJECT_ID = "seed-project-1"
const API_KEY_ID = "seed-api-key-1"

const BASE_TIME = "2026-03-05 10:00:00.000000000"

const spans = [
  {
    organization_id: ORG_ID,
    project_id: PROJECT_ID,
    session_id: "session-001",
    trace_id: "aabbccdd11223344aabbccdd11223344",
    span_id: "aabbccdd11223344",
    parent_span_id: "",
    api_key_id: API_KEY_ID,
    start_time: BASE_TIME,
    end_time: "2026-03-05 10:00:01.240000000",
    name: "gpt-4o completion",
    service_name: "my-app",
    kind: 1,
    status_code: 1,
    status_message: "",
    operation: "chat",
    provider: "openai",
    model: "gpt-4o",
    response_model: "gpt-4o-2024-08-06",
    tokens_input: 210,
    tokens_output: 85,
    tokens_cache_read: 0,
    tokens_cache_create: 0,
    tokens_reasoning: 0,
    cost_input_microcents: 52500,
    cost_output_microcents: 42500,
    cost_total_microcents: 95000,
    cost_is_estimated: 1,
    response_id: "chatcmpl-abc123",
    finish_reasons: ["stop"],
    input_messages: JSON.stringify([{ role: "user", content: "Summarize this document." }]),
    output_messages: JSON.stringify([{ role: "assistant", content: "This document covers..." }]),
    system_instructions: "",
    tool_definitions: "",
    attr_string: {},
    attr_int: {},
    attr_float: { "gen_ai.request.temperature": 0.7 },
    attr_bool: {},
    resource_string: { "service.name": "my-app" },
    scope_name: "openai-instrumentation",
    scope_version: "1.0.0",
  },
  {
    organization_id: ORG_ID,
    project_id: PROJECT_ID,
    session_id: "session-001",
    trace_id: "aabbccdd11223344aabbccdd11223344",
    span_id: "1122334455667788",
    parent_span_id: "aabbccdd11223344",
    api_key_id: API_KEY_ID,
    start_time: "2026-03-05 09:59:59.800000000",
    end_time: "2026-03-05 10:00:01.150000000",
    name: "document-chain",
    service_name: "my-app",
    kind: 1,
    status_code: 1,
    status_message: "",
    operation: "",
    provider: "",
    model: "",
    response_model: "",
    tokens_input: 0,
    tokens_output: 0,
    tokens_cache_read: 0,
    tokens_cache_create: 0,
    tokens_reasoning: 0,
    cost_input_microcents: 0,
    cost_output_microcents: 0,
    cost_total_microcents: 0,
    cost_is_estimated: 0,
    response_id: "",
    finish_reasons: [],
    input_messages: "",
    output_messages: "",
    system_instructions: "",
    tool_definitions: "",
    attr_string: {},
    attr_int: {},
    attr_float: {},
    attr_bool: {},
    resource_string: { "service.name": "my-app" },
    scope_name: "",
    scope_version: "",
  },
  {
    organization_id: ORG_ID,
    project_id: PROJECT_ID,
    session_id: "",
    trace_id: "deadbeefcafe0000deadbeefcafe0000",
    span_id: "cafebabe00000001",
    parent_span_id: "",
    api_key_id: API_KEY_ID,
    start_time: "2026-03-05 10:01:00.000000000",
    end_time: "2026-03-05 10:01:00.430000000",
    name: "web-search",
    service_name: "my-app",
    kind: 1,
    status_code: 1,
    status_message: "",
    operation: "",
    provider: "",
    model: "",
    response_model: "",
    tokens_input: 0,
    tokens_output: 0,
    tokens_cache_read: 0,
    tokens_cache_create: 0,
    tokens_reasoning: 0,
    cost_input_microcents: 0,
    cost_output_microcents: 0,
    cost_total_microcents: 0,
    cost_is_estimated: 0,
    response_id: "",
    finish_reasons: [],
    input_messages: JSON.stringify({ query: "latest AI news" }),
    output_messages: JSON.stringify({ results: ["Result 1", "Result 2"] }),
    system_instructions: "",
    tool_definitions: "",
    attr_string: {},
    attr_int: {},
    attr_float: {},
    attr_bool: {},
    resource_string: { "service.name": "my-app" },
    scope_name: "",
    scope_version: "",
  },
  {
    organization_id: ORG_ID,
    project_id: PROJECT_ID,
    session_id: "",
    trace_id: "deadbeefcafe0000deadbeefcafe0000",
    span_id: "cafebabe00000002",
    parent_span_id: "cafebabe00000001",
    api_key_id: API_KEY_ID,
    start_time: "2026-03-05 10:01:00.500000000",
    end_time: "2026-03-05 10:01:02.600000000",
    name: "claude-sonnet-4-6 completion",
    service_name: "my-app",
    kind: 1,
    status_code: 1,
    status_message: "",
    operation: "chat",
    provider: "anthropic",
    model: "claude-sonnet-4-6",
    response_model: "claude-sonnet-4-6",
    tokens_input: 450,
    tokens_output: 130,
    tokens_cache_read: 200,
    tokens_cache_create: 0,
    tokens_reasoning: 0,
    cost_input_microcents: 135000,
    cost_output_microcents: 195000,
    cost_total_microcents: 330000,
    cost_is_estimated: 1,
    response_id: "msg_abc456",
    finish_reasons: ["end_turn"],
    input_messages: JSON.stringify([{ role: "user", content: "What are the latest AI developments?" }]),
    output_messages: JSON.stringify([{ role: "assistant", content: "Recent AI developments include..." }]),
    system_instructions: "",
    tool_definitions: "",
    attr_string: {},
    attr_int: {},
    attr_float: { "gen_ai.request.temperature": 0.5 },
    attr_bool: {},
    resource_string: { "service.name": "my-app" },
    scope_name: "anthropic-instrumentation",
    scope_version: "1.0.0",
  },
  {
    organization_id: ORG_ID,
    project_id: PROJECT_ID,
    session_id: "",
    trace_id: "f00df00df00df00df00df00df00df00d",
    span_id: "f00df00df00df00d",
    parent_span_id: "",
    api_key_id: API_KEY_ID,
    start_time: "2026-03-05 10:02:00.000000000",
    end_time: "2026-03-05 10:02:00.150000000",
    name: "gpt-4o-mini completion",
    service_name: "my-app",
    kind: 1,
    status_code: 2,
    status_message: "Rate limit exceeded",
    error_type: "RateLimitError",
    operation: "chat",
    provider: "openai",
    model: "gpt-4o-mini",
    response_model: "",
    tokens_input: 0,
    tokens_output: 0,
    tokens_cache_read: 0,
    tokens_cache_create: 0,
    tokens_reasoning: 0,
    cost_input_microcents: 0,
    cost_output_microcents: 0,
    cost_total_microcents: 0,
    cost_is_estimated: 0,
    response_id: "",
    finish_reasons: [],
    input_messages: JSON.stringify([{ role: "user", content: "Hello!" }]),
    output_messages: "",
    system_instructions: "",
    tool_definitions: "",
    attr_string: {},
    attr_int: {},
    attr_float: {},
    attr_bool: {},
    resource_string: { "service.name": "my-app" },
    scope_name: "openai-instrumentation",
    scope_version: "1.0.0",
  },
]

const seedSpans: Seeder = {
  name: "spans",
  run: (ctx) => insertJsonEachRow(ctx.client, "spans", spans),
}

export const spanSeeders: Seeder[] = [seedSpans]
