// This file was auto-generated by Fern from our API Definition.

import type * as Latitude from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ActivityUsersRequest {
    /** Lower bound (inclusive) of the time range. Defaults to 30 days before `toIso`. */
    fromIso?: string;
    /** Upper bound (inclusive) of the time range. Defaults to now. */
    toIso?: string;
    /** When `true`, scope every aggregate to errored traces only. */
    errorsOnly?: Latitude.ActivityUsersRequestErrorsOnly;
}
