// This file was auto-generated by Fern from our API Definition.

import type * as LatitudeApi from "../../../../index.js";

/**
 * @example
 *     {
 *         fromIso: "2024-01-15T09:30:00Z",
 *         toIso: "2024-01-15T09:30:00Z",
 *         limit: 1,
 *         offset: 1,
 *         sortBy: "lastSeen",
 *         sortDirection: "asc",
 *         searchQuery: "searchQuery"
 *     }
 */
export interface UsersListRequest {
    /** Lower bound (inclusive) of the time range. Defaults to 30 days before `toIso`. */
    fromIso?: string;
    /** Upper bound (inclusive) of the time range. Defaults to now. */
    toIso?: string;
    /** Page size. Max 100. */
    limit?: number;
    /** Zero-based offset of the first user to return. */
    offset?: number;
    /** Field to sort by. Defaults to most recently seen. */
    sortBy?: LatitudeApi.UsersListRequestSortBy;
    /** Sort direction. Defaults to descending. */
    sortDirection?: LatitudeApi.UsersListRequestSortDirection;
    /** Case-insensitive substring match on the user's id or email. */
    searchQuery?: string;
}
