// This file was auto-generated by Fern from our API Definition.

import type * as LatitudeApi from "../../../../index.js";

/**
 * @example
 *     {
 *         fromIso: "2024-01-15T09:30:00Z",
 *         toIso: "2024-01-15T09:30:00Z",
 *         errorsOnly: "true"
 *     }
 */
export interface UsersActivityRequest {
    /** Lower bound (inclusive) of the time range. Defaults to 30 days before `toIso`. */
    fromIso?: string;
    /** Upper bound (inclusive) of the time range. Defaults to now. */
    toIso?: string;
    /** When `true`, scope every aggregate to errored traces only. */
    errorsOnly?: LatitudeApi.UsersActivityRequestErrorsOnly;
}
