// This file was auto-generated by Fern from our API Definition.

/** When `true`, scope every aggregate to failed calls only. */
export const GetToolsRequestErrorsOnly = {
    True: "true",
    False: "false",
} as const;
export type GetToolsRequestErrorsOnly = (typeof GetToolsRequestErrorsOnly)[keyof typeof GetToolsRequestErrorsOnly];
