// This file was auto-generated by Fern from our API Definition.

/** When `true`, scope every aggregate to failed calls only. */
export const ToolsCoOccurrenceRequestErrorsOnly = {
    True: "true",
    False: "false",
} as const;
export type ToolsCoOccurrenceRequestErrorsOnly =
    (typeof ToolsCoOccurrenceRequestErrorsOnly)[keyof typeof ToolsCoOccurrenceRequestErrorsOnly];
