// This file was auto-generated by Fern from our API Definition.

/** When `true`, scope every aggregate to errored traces only. */
export const UsersActivityRequestErrorsOnly = {
    True: "true",
    False: "false",
} as const;
export type UsersActivityRequestErrorsOnly =
    (typeof UsersActivityRequestErrorsOnly)[keyof typeof UsersActivityRequestErrorsOnly];
