// This file was auto-generated by Fern from our API Definition.

import type * as Latitude from "../../../index.js";

/**
 * Default metric evaluated for this target.
 */
export type UpdateMonitorBodyTargetMetric =
    | Latitude.UpdateMonitorBodyTargetMetric.Count
    | Latitude.UpdateMonitorBodyTargetMetric.ErrorRate
    | Latitude.UpdateMonitorBodyTargetMetric.CacheHitRate
    | Latitude.UpdateMonitorBodyTargetMetric.Avg
    | Latitude.UpdateMonitorBodyTargetMetric.Sum
    | Latitude.UpdateMonitorBodyTargetMetric.Min
    | Latitude.UpdateMonitorBodyTargetMetric.Max
    | Latitude.UpdateMonitorBodyTargetMetric.Median;

export namespace UpdateMonitorBodyTargetMetric {
    export interface Count {
        kind: "count";
    }

    export interface ErrorRate {
        kind: "errorRate";
    }

    export interface CacheHitRate {
        kind: "cacheHitRate";
    }

    export interface Avg {
        kind: "avg";
        /** Numeric field to aggregate. */
        field: UpdateMonitorBodyTargetMetricAvg.Field;
    }

    export namespace UpdateMonitorBodyTargetMetricAvg {
        /** Numeric field to aggregate. */
        export const Field = {
            Duration: "duration",
            Cost: "cost",
            Tokens: "tokens",
        } as const;
        export type Field = (typeof Field)[keyof typeof Field];
    }

    export interface Sum {
        kind: "sum";
        /** Numeric field to aggregate. */
        field: UpdateMonitorBodyTargetMetricSum.Field;
    }

    export namespace UpdateMonitorBodyTargetMetricSum {
        /** Numeric field to aggregate. */
        export const Field = {
            Duration: "duration",
            Cost: "cost",
            Tokens: "tokens",
        } as const;
        export type Field = (typeof Field)[keyof typeof Field];
    }

    export interface Min {
        kind: "min";
        /** Numeric field to aggregate. */
        field: UpdateMonitorBodyTargetMetricMin.Field;
    }

    export namespace UpdateMonitorBodyTargetMetricMin {
        /** Numeric field to aggregate. */
        export const Field = {
            Duration: "duration",
            Cost: "cost",
            Tokens: "tokens",
        } as const;
        export type Field = (typeof Field)[keyof typeof Field];
    }

    export interface Max {
        kind: "max";
        /** Numeric field to aggregate. */
        field: UpdateMonitorBodyTargetMetricMax.Field;
    }

    export namespace UpdateMonitorBodyTargetMetricMax {
        /** Numeric field to aggregate. */
        export const Field = {
            Duration: "duration",
            Cost: "cost",
            Tokens: "tokens",
        } as const;
        export type Field = (typeof Field)[keyof typeof Field];
    }

    export interface Median {
        kind: "median";
        /** Numeric field to aggregate. */
        field: UpdateMonitorBodyTargetMetricMedian.Field;
    }

    export namespace UpdateMonitorBodyTargetMetricMedian {
        /** Numeric field to aggregate. */
        export const Field = {
            Duration: "duration",
            Cost: "cost",
            Tokens: "tokens",
        } as const;
        export type Field = (typeof Field)[keyof typeof Field];
    }
}
