// This file was auto-generated by Fern from our API Definition.

import type * as Latitude from "../../../index.js";

/**
 * Replacement condition for threshold or escalating monitors.
 */
export type UpdateMonitorBodyCondition =
    | Latitude.UpdateMonitorBodyCondition.Threshold
    | Latitude.UpdateMonitorBodyCondition.Escalating;

export namespace UpdateMonitorBodyCondition {
    export interface Threshold extends Latitude.AlertThresholdCondition {
        trigger: "threshold";
    }

    export interface Escalating extends Latitude.AlertEscalatingCondition {
        trigger: "escalating";
    }
}
