# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.create_score_body import CreateScoreBody
from ..types.score_response import ScoreResponse
from .raw_client import AsyncRawScoresClient, RawScoresClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ScoresClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawScoresClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawScoresClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawScoresClient
        """
        return self._raw_client

    def create(
        self, project_slug: str, *, request: CreateScoreBody, request_options: typing.Optional[RequestOptions] = None
    ) -> ScoreResponse:
        """
        Creates a score against a target trace. The trace is resolved by explicit id (`trace.by = "id"`) or by a filter set (`trace.by = "filters"`, exactly one match required). Annotations use the separate `/annotations` endpoint.

        Parameters
        ----------
        project_slug : str
            Project slug (human-readable identifier)

        request : CreateScoreBody

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ScoreResponse
            Score created

        Examples
        --------
        from latitude_sdk import CreateCustomScoreBody, LatitudeClient, TraceRef_Id

        client = LatitudeClient(
            api_key="YOUR_API_KEY",
        )
        client.scores.create(
            project_slug="projectSlug",
            request=CreateCustomScoreBody(
                value=1.1,
                passed=True,
                feedback="feedback",
                trace=TraceRef_Id(
                    id="id",
                ),
                source_id="sourceId",
            ),
        )
        """
        _response = self._raw_client.create(project_slug, request=request, request_options=request_options)
        return _response.data


class AsyncScoresClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawScoresClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawScoresClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawScoresClient
        """
        return self._raw_client

    async def create(
        self, project_slug: str, *, request: CreateScoreBody, request_options: typing.Optional[RequestOptions] = None
    ) -> ScoreResponse:
        """
        Creates a score against a target trace. The trace is resolved by explicit id (`trace.by = "id"`) or by a filter set (`trace.by = "filters"`, exactly one match required). Annotations use the separate `/annotations` endpoint.

        Parameters
        ----------
        project_slug : str
            Project slug (human-readable identifier)

        request : CreateScoreBody

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ScoreResponse
            Score created

        Examples
        --------
        import asyncio

        from latitude_sdk import AsyncLatitudeClient, CreateCustomScoreBody, TraceRef_Id

        client = AsyncLatitudeClient(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.scores.create(
                project_slug="projectSlug",
                request=CreateCustomScoreBody(
                    value=1.1,
                    passed=True,
                    feedback="feedback",
                    trace=TraceRef_Id(
                        id="id",
                    ),
                    source_id="sourceId",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(project_slug, request=request, request_options=request_options)
        return _response.data
