// This file was auto-generated by Fern from our API Definition.

/** `"active"` for unmuted signals; `"archived"` for muted signals. Omit to include both. */
export const ListSignalsRequestLifecycleGroup = {
    Active: "active",
    Archived: "archived",
} as const;
export type ListSignalsRequestLifecycleGroup =
    (typeof ListSignalsRequestLifecycleGroup)[keyof typeof ListSignalsRequestLifecycleGroup];
