// This file was auto-generated by Fern from our API Definition.

/** Sort direction. Defaults to `desc`. */
export const SignalsListRequestSortDirection = {
    Asc: "asc",
    Desc: "desc",
} as const;
export type SignalsListRequestSortDirection =
    (typeof SignalsListRequestSortDirection)[keyof typeof SignalsListRequestSortDirection];
