// This file was auto-generated by Fern from our API Definition.

/** Sort field. `lastSeen` orders by most recent occurrence; `occurrences` by total count in the time window; `state` by lifecycle priority. */
export const SignalsListRequestSortBy = {
    LastSeen: "lastSeen",
    Occurrences: "occurrences",
    State: "state",
} as const;
export type SignalsListRequestSortBy = (typeof SignalsListRequestSortBy)[keyof typeof SignalsListRequestSortBy];
