// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListTracesSignalsRequest {
    /** Opaque cursor returned in a previous response's `nextCursor`. Omit on the first page. */
    cursor?: string;
    /** Page size. Defaults to 50; max 200. */
    limit?: number;
}
