// This file was auto-generated by Fern from our API Definition.

import type * as LatitudeApi from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface UpdateSignalBody {
    /** New name. Omitted leaves it unchanged. */
    name?: string;
    /** New description. Omitted leaves it unchanged. */
    description?: string;
    /** New evaluation pre-gate. Explicit `null` clears it; omitted leaves it unchanged. */
    filters?: Record<string, LatitudeApi.FilterCondition[]>;
}
