import {
  SEED_ANNOTATION_QUEUE_ID,
  SEED_EVALUATION_ID,
  SEED_ISSUE_ID,
  SEED_ORG_ID,
  SEED_PROJECT_ID,
  SEED_SCORE_API_REVIEWED_ID,
  SEED_SCORE_DRAFT_ID,
  SEED_SCORE_ERRORED_ID,
  SEED_SCORE_ISSUE_LINKED_ID,
  SEED_SCORE_PASSED_ID,
  SEED_SCORE_PENDING_ID,
  SEED_SCORE_SIMULATION_LINKED_ID,
  SEED_SIMULATION_ID,
} from "@domain/shared"
import { Effect } from "effect"
import { scores } from "../../schema/scores.ts"
import { type SeedContext, SeedError, type Seeder } from "../types.ts"

const scoreRows = [
  {
    id: SEED_SCORE_PASSED_ID,
    organizationId: SEED_ORG_ID,
    projectId: SEED_PROJECT_ID,
    sessionId: "seed-score-session-1",
    traceId: "11111111111111111111111111111111",
    spanId: "aaaaaaaaaaaaaaaa",
    source: "evaluation" as const,
    sourceId: SEED_EVALUATION_ID,
    simulationId: null,
    issueId: null,
    value: 0.98,
    passed: true,
    feedback: "The agent followed the instructions and provided a complete answer.",
    metadata: { evaluationHash: "seed-eval-v1" },
    error: null,
    errored: false,
    duration: 850_000_000,
    tokens: 1_820,
    cost: 245_000,
    draftedAt: null,
    createdAt: new Date("2026-03-20T10:00:00.000Z"),
    updatedAt: new Date("2026-03-20T10:00:00.000Z"),
  },
  {
    id: SEED_SCORE_ERRORED_ID,
    organizationId: SEED_ORG_ID,
    projectId: SEED_PROJECT_ID,
    sessionId: "seed-score-session-1",
    traceId: "22222222222222222222222222222222",
    spanId: "bbbbbbbbbbbbbbbb",
    source: "evaluation" as const,
    sourceId: SEED_EVALUATION_ID,
    simulationId: null,
    issueId: null,
    value: 0,
    passed: false,
    feedback: "Score generation errored before a verdict was produced.",
    metadata: { evaluationHash: "seed-eval-v1" },
    error: "Evaluator request timed out while scoring the trace.",
    errored: true,
    duration: 120_000_000,
    tokens: 0,
    cost: 0,
    draftedAt: null,
    createdAt: new Date("2026-03-20T11:00:00.000Z"),
    updatedAt: new Date("2026-03-20T11:00:00.000Z"),
  },
  {
    id: SEED_SCORE_DRAFT_ID,
    organizationId: SEED_ORG_ID,
    projectId: SEED_PROJECT_ID,
    sessionId: "seed-score-session-2",
    traceId: "33333333333333333333333333333333",
    spanId: "cccccccccccccccc",
    source: "annotation" as const,
    sourceId: "UI",
    simulationId: null,
    issueId: null,
    value: 0.4,
    passed: false,
    feedback: "The response needs human review before final publication.",
    metadata: {
      rawFeedback: "Review this answer for a possible policy violation.",
      messageIndex: 1,
      partIndex: 0,
      startOffset: 12,
      endOffset: 38,
    },
    error: null,
    errored: false,
    duration: 0,
    tokens: 0,
    cost: 0,
    draftedAt: new Date("2026-03-21T09:05:00.000Z"),
    createdAt: new Date("2026-03-21T09:00:00.000Z"),
    updatedAt: new Date("2026-03-21T09:05:00.000Z"),
  },
  {
    id: SEED_SCORE_API_REVIEWED_ID,
    organizationId: SEED_ORG_ID,
    projectId: SEED_PROJECT_ID,
    sessionId: "seed-score-session-4",
    traceId: "66666666666666666666666666666666",
    spanId: null,
    source: "annotation" as const,
    sourceId: "API",
    simulationId: null,
    issueId: null,
    value: 0.91,
    passed: true,
    feedback: "The conversation stayed grounded and answered the request correctly.",
    metadata: {
      rawFeedback: "This entire conversation is correct and does not need changes.",
    },
    error: null,
    errored: false,
    duration: 0,
    tokens: 0,
    cost: 0,
    draftedAt: null,
    createdAt: new Date("2026-03-22T12:45:00.000Z"),
    updatedAt: new Date("2026-03-22T12:45:00.000Z"),
  },
  {
    id: SEED_SCORE_PENDING_ID,
    organizationId: SEED_ORG_ID,
    projectId: SEED_PROJECT_ID,
    sessionId: null,
    traceId: "44444444444444444444444444444444",
    spanId: null,
    source: "custom" as const,
    sourceId: "seed-import",
    simulationId: null,
    issueId: null,
    value: 0.18,
    passed: false,
    feedback: "The output leaked a secret token in the final answer.",
    metadata: { reviewer: "qa", importName: "seed-import" },
    error: null,
    errored: false,
    duration: 0,
    tokens: 0,
    cost: 0,
    draftedAt: null,
    createdAt: new Date("2026-03-22T08:30:00.000Z"),
    updatedAt: new Date("2026-03-22T08:30:00.000Z"),
  },
  {
    id: SEED_SCORE_ISSUE_LINKED_ID,
    organizationId: SEED_ORG_ID,
    projectId: SEED_PROJECT_ID,
    sessionId: "seed-score-session-3",
    traceId: "55555555555555555555555555555555",
    spanId: "dddddddddddddddd",
    source: "annotation" as const,
    sourceId: SEED_ANNOTATION_QUEUE_ID,
    simulationId: null,
    issueId: SEED_ISSUE_ID,
    value: 0.12,
    passed: false,
    feedback: "The agent exposed a private secret in the final answer.",
    metadata: {
      rawFeedback: "This answer leaks sensitive information.",
      messageIndex: 2,
    },
    error: null,
    errored: false,
    duration: 15_000_000,
    tokens: 0,
    cost: 0,
    draftedAt: null,
    createdAt: new Date("2026-03-23T14:15:00.000Z"),
    updatedAt: new Date("2026-03-23T14:15:00.000Z"),
  },
  {
    id: SEED_SCORE_SIMULATION_LINKED_ID,
    organizationId: SEED_ORG_ID,
    projectId: SEED_PROJECT_ID,
    sessionId: "seed-sim-session-1",
    traceId: "77777777777777777777777777777777",
    spanId: "eeeeeeeeeeeeeeee",
    source: "evaluation" as const,
    sourceId: SEED_EVALUATION_ID,
    simulationId: SEED_SIMULATION_ID,
    issueId: null,
    value: 0.95,
    passed: true,
    feedback: "The agent correctly resolved the support ticket within the expected parameters.",
    metadata: { evaluationHash: "seed-eval-v1" },
    error: null,
    errored: false,
    duration: 920_000_000,
    tokens: 2_140,
    cost: 312_000,
    draftedAt: null,
    createdAt: new Date("2026-03-25T14:02:00.000Z"),
    updatedAt: new Date("2026-03-25T14:02:00.000Z"),
  },
] as const

const seedScores: Seeder = {
  name: "scores/canonical-lifecycle-samples",
  run: (ctx: SeedContext) =>
    Effect.tryPromise({
      try: async () => {
        for (const row of scoreRows) {
          const { id, ...set } = row
          await ctx.db.insert(scores).values(row).onConflictDoUpdate({
            target: scores.id,
            set,
          })
        }

        console.log(`  -> scores: ${scoreRows.length} canonical lifecycle samples`)
      },
      catch: (error) => new SeedError({ reason: "Failed to seed scores", cause: error }),
    }).pipe(Effect.asVoid),
}

export const scoreSeeders: readonly Seeder[] = [seedScores]
