// This file was auto-generated by Fern from our API Definition.

import type * as LatitudeApi from "../../../../index.js";

/**
 * @example
 *     {
 *         fromIso: "2024-01-15T09:30:00Z",
 *         toIso: "2024-01-15T09:30:00Z",
 *         sourceId: "sourceId"
 *     }
 */
export interface IncidentsListRequest {
    /** Lower bound (inclusive) of the time window. Returns incidents whose lifetime overlaps `[fromIso, toIso]`. Defaults to 7 days before `toIso`. */
    fromIso?: string;
    /** Upper bound (inclusive) of the time window. Defaults to now. */
    toIso?: string;
    /** Restrict to incidents whose source type matches any value in this list. */
    sourceTypes?: LatitudeApi.IncidentsListRequestSourceTypesItem | LatitudeApi.IncidentsListRequestSourceTypesItem[];
    /** Restrict to incidents tied to a single source entity (e.g. one issue id). */
    sourceId?: string;
    /** Restrict to incidents whose kind matches any value in this list. */
    kinds?: LatitudeApi.IncidentsListRequestKindsItem | LatitudeApi.IncidentsListRequestKindsItem[];
    /** Restrict to incidents whose severity matches any value in this list. */
    severities?: LatitudeApi.IncidentsListRequestSeveritiesItem | LatitudeApi.IncidentsListRequestSeveritiesItem[];
}
