import { COLLAPSED_BOX_HEIGHT } from '@latitude-data/web-ui/molecules/CollapsibleBox'

const PLAYGROUND_GAP_PADDING = 24

export const EVALUATION_PLAYGROUND_COLLAPSED_SIZE = COLLAPSED_BOX_HEIGHT + 12
export const EVALUATION_PLAYGROUND_GAP_PADDING = PLAYGROUND_GAP_PADDING
