# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import UniversalBaseModel
from .update_monitor_body_metric_max_field import UpdateMonitorBodyMetricMaxField


class UpdateMonitorBodyMetricMax(UniversalBaseModel):
    field: UpdateMonitorBodyMetricMaxField = pydantic.Field()
    """
    Numeric field to aggregate.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
