# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import UniversalBaseModel
from ...types.alert_escalating_condition_direction import AlertEscalatingConditionDirection
from ...types.alert_escalating_condition_threshold import AlertEscalatingConditionThreshold
from ...types.alert_escalating_condition_window import AlertEscalatingConditionWindow
from ...types.alert_metric_threshold import AlertMetricThreshold
from ...types.alert_threshold_condition_direction import AlertThresholdConditionDirection
from ...types.monitor_metric import MonitorMetric


class UpdateMonitorBodyCondition_Threshold(UniversalBaseModel):
    """
    Replacement condition for threshold or escalating monitors.
    """

    trigger: typing.Literal["threshold"] = "threshold"
    metric: MonitorMetric
    threshold: AlertMetricThreshold
    direction: typing.Optional[AlertThresholdConditionDirection] = None

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


class UpdateMonitorBodyCondition_Escalating(UniversalBaseModel):
    """
    Replacement condition for threshold or escalating monitors.
    """

    trigger: typing.Literal["escalating"] = "escalating"
    metric: MonitorMetric
    threshold: typing.Optional[AlertEscalatingConditionThreshold] = None
    direction: typing.Optional[AlertEscalatingConditionDirection] = None
    sensitivity: typing.Optional[int] = None
    window: AlertEscalatingConditionWindow

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)


UpdateMonitorBodyCondition = typing_extensions.Annotated[
    typing.Union[UpdateMonitorBodyCondition_Threshold, UpdateMonitorBodyCondition_Escalating],
    pydantic.Field(discriminator="trigger"),
]
