# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import UniversalBaseModel
from ...types.alert_metric_threshold import AlertMetricThreshold
from ...types.monitor_metric import MonitorMetric
from .update_monitor_alert_body_condition_kind_direction import UpdateMonitorAlertBodyConditionKindDirection
from .update_monitor_alert_body_condition_kind_window import UpdateMonitorAlertBodyConditionKindWindow


class UpdateMonitorAlertBodyConditionKind(UniversalBaseModel):
    kind: typing.Literal["metric.escalating"] = pydantic.Field(default="metric.escalating")
    """
    Sustained metric alert: opens when the target metric stays across threshold for the whole `window`.
    """

    metric: MonitorMetric
    threshold: AlertMetricThreshold
    direction: typing.Optional[UpdateMonitorAlertBodyConditionKindDirection] = pydantic.Field(default=None)
    """
    Direction that opens the incident. Defaults to `above` when omitted.
    """

    window: UpdateMonitorAlertBodyConditionKindWindow = pydantic.Field()
    """
    Sustained-condition window.
    """

    model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
