// This file was auto-generated by Fern from our API Definition.

/** Field to sort by. Defaults to `startTime`. */
export const ListTracesSessionsRequestSortBy = {
    StartTime: "startTime",
    EndTime: "endTime",
    DurationNs: "durationNs",
    TokensTotal: "tokensTotal",
    CostTotalMicrocents: "costTotalMicrocents",
} as const;
export type ListTracesSessionsRequestSortBy =
    (typeof ListTracesSessionsRequestSortBy)[keyof typeof ListTracesSessionsRequestSortBy];
