import { WeeklyEmailMailProps } from './types'

// Profile 1: Workspace with full activity (logs, issues, and annotations)
export const fullActivityProfile: WeeklyEmailMailProps = {
  currentWorkspace: { id: 1, name: 'Acme Corp Production' },
  logs: {
    usedInProduction: true,
    logsCount: 15420,
    tokensSpent: 2847392,
    tokensCost: 45.67,
    topProjects: [
      {
        projectId: 1,
        projectName: 'Customer Support Bot',
        logsCount: 8234,
        tokensSpent: 1523847,
        tokensCost: 24.38,
      },
      {
        projectId: 2,
        projectName: 'Content Generator',
        logsCount: 4521,
        tokensSpent: 892341,
        tokensCost: 14.28,
      },
      {
        projectId: 3,
        projectName: 'Data Analyzer',
        logsCount: 2665,
        tokensSpent: 431204,
        tokensCost: 7.01,
      },
    ],
  },
  issues: {
    hasIssues: true,
    issuesCount: 12,
    newIssuesCount: 5,
    escalatedIssuesCount: 2,
    resolvedIssuesCount: 8,
    ignoredIssuesCount: 1,
    regressedIssuesCount: 1,
    topProjects: [
      {
        projectId: 1,
        projectName: 'Customer Support Bot',
        issuesCount: 7,
        newIssuesCount: 3,
        escalatedIssuesCount: 2,
        resolvedIssuesCount: 5,
        ignoredIssuesCount: 0,
        regressedIssuesCount: 1,
      },
      {
        projectId: 2,
        projectName: 'Content Generator',
        issuesCount: 5,
        newIssuesCount: 2,
        escalatedIssuesCount: 0,
        resolvedIssuesCount: 3,
        ignoredIssuesCount: 1,
        regressedIssuesCount: 0,
      },
    ],
    newIssuesList: [
      {
        id: 101,
        title: 'Incorrect JSON formatting in API responses',
        projectId: 1,
        commitUuid: 'abc123def456',
      },
      {
        id: 102,
        title: 'Timeout errors when processing large datasets',
        projectId: 1,
        commitUuid: 'abc123def456',
      },
      {
        id: 103,
        title: 'Memory leak in content generation pipeline',
        projectId: 2,
        commitUuid: 'xyz789uvw012',
      },
      {
        id: 104,
        title: 'Rate limiting not working correctly',
        projectId: 1,
        commitUuid: 'abc123def456',
      },
      {
        id: 105,
        title: 'Database connection pool exhaustion',
        projectId: 2,
        commitUuid: 'xyz789uvw012',
      },
    ],
  },
  annotations: {
    hasAnnotations: true,
    annotationsCount: 247,
    passedCount: 198,
    failedCount: 49,
    passedPercentage: 80.16,
    failedPercentage: 19.84,
    firstProjectId: 1,
    topProjects: [
      {
        projectId: 1,
        projectName: 'Customer Support Bot',
        annotationsCount: 156,
        passedCount: 132,
        failedCount: 24,
        passedPercentage: 84.62,
        failedPercentage: 15.38,
      },
      {
        projectId: 2,
        projectName: 'Content Generator',
        annotationsCount: 91,
        passedCount: 66,
        failedCount: 25,
        passedPercentage: 72.53,
        failedPercentage: 27.47,
      },
    ],
  },
}

// Profile 2: Workspace with only logs activity
export const logsOnlyProfile: WeeklyEmailMailProps = {
  currentWorkspace: { id: 2, name: 'Acme Corp Production' },
  logs: {
    usedInProduction: true,
    logsCount: 3421,
    tokensSpent: 542183,
    tokensCost: 8.67,
    topProjects: [
      {
        projectId: 10,
        projectName: 'Main Application',
        logsCount: 2134,
        tokensSpent: 338492,
        tokensCost: 5.42,
      },
      {
        projectId: 11,
        projectName: 'API Gateway',
        logsCount: 1287,
        tokensSpent: 203691,
        tokensCost: 3.25,
      },
    ],
  },
  issues: {
    hasIssues: false,
    issuesCount: 0,
    newIssuesCount: 0,
    escalatedIssuesCount: 0,
    resolvedIssuesCount: 0,
    ignoredIssuesCount: 0,
    regressedIssuesCount: 0,
    topProjects: [],
    newIssuesList: [],
  },
  annotations: {
    hasAnnotations: false,
    annotationsCount: 0,
    passedCount: 0,
    failedCount: 0,
    passedPercentage: 0,
    failedPercentage: 0,
    topProjects: [],
    firstProjectId: 1,
  },
}

// Profile 3: Workspace with some activity (logs and issues, no annotations)
export const someActivityProfile: WeeklyEmailMailProps = {
  currentWorkspace: { id: 3, name: 'Acme Corp Production' },
  logs: {
    usedInProduction: true,
    logsCount: 7823,
    tokensSpent: 1234567,
    tokensCost: 19.75,
    topProjects: [
      {
        projectId: 20,
        projectName: 'E-commerce Assistant',
        logsCount: 4521,
        tokensSpent: 723456,
        tokensCost: 11.57,
      },
      {
        projectId: 21,
        projectName: 'Recommendation Engine',
        logsCount: 3302,
        tokensSpent: 511111,
        tokensCost: 8.18,
      },
    ],
  },
  issues: {
    hasIssues: true,
    issuesCount: 4,
    newIssuesCount: 2,
    escalatedIssuesCount: 0,
    resolvedIssuesCount: 3,
    ignoredIssuesCount: 0,
    regressedIssuesCount: 0,
    topProjects: [
      {
        projectId: 20,
        projectName: 'E-commerce Assistant',
        issuesCount: 3,
        newIssuesCount: 2,
        escalatedIssuesCount: 0,
        resolvedIssuesCount: 2,
        ignoredIssuesCount: 0,
        regressedIssuesCount: 0,
      },
      {
        projectId: 21,
        projectName: 'Recommendation Engine',
        issuesCount: 1,
        newIssuesCount: 0,
        escalatedIssuesCount: 0,
        resolvedIssuesCount: 1,
        ignoredIssuesCount: 0,
        regressedIssuesCount: 0,
      },
    ],
    newIssuesList: [
      {
        id: 201,
        title: 'Product recommendation accuracy degraded',
        projectId: 20,
        commitUuid: 'ecom456abc789',
      },
      {
        id: 202,
        title: 'Cart abandonment prediction failing',
        projectId: 20,
        commitUuid: 'ecom456abc789',
      },
    ],
  },
  annotations: {
    hasAnnotations: false,
    annotationsCount: 0,
    passedCount: 0,
    failedCount: 0,
    passedPercentage: 0,
    failedPercentage: 0,
    topProjects: [],
    firstProjectId: 1,
  },
}

// Profile 4: Workspace with zero activity
export const zeroActivityProfile: WeeklyEmailMailProps = {
  currentWorkspace: { id: 4, name: 'Acme Corp Production' },
  logs: {
    usedInProduction: false,
    logsCount: 0,
    tokensSpent: 0,
    tokensCost: 0,
    topProjects: [],
  },
  issues: {
    hasIssues: false,
    issuesCount: 0,
    newIssuesCount: 0,
    escalatedIssuesCount: 0,
    resolvedIssuesCount: 0,
    ignoredIssuesCount: 0,
    regressedIssuesCount: 0,
    topProjects: [],
    newIssuesList: [],
  },
  annotations: {
    hasAnnotations: false,
    annotationsCount: 0,
    passedCount: 0,
    failedCount: 0,
    passedPercentage: 0,
    failedPercentage: 0,
    topProjects: [],
    firstProjectId: 1,
  },
}

// Profile 5: Workspace with issues but no new issues (resolved/regressed only)
export const issuesWithoutNewProfile: WeeklyEmailMailProps = {
  currentWorkspace: { id: 5, name: 'Acme Corp Production' },
  logs: {
    usedInProduction: true,
    logsCount: 5234,
    tokensSpent: 892341,
    tokensCost: 14.28,
    topProjects: [
      {
        projectId: 40,
        projectName: 'Stable Production App',
        logsCount: 3421,
        tokensSpent: 583421,
        tokensCost: 9.33,
      },
      {
        projectId: 41,
        projectName: 'Monitoring Service',
        logsCount: 1813,
        tokensSpent: 308920,
        tokensCost: 4.95,
      },
    ],
  },
  issues: {
    hasIssues: true,
    issuesCount: 8,
    newIssuesCount: 0, // No new issues
    escalatedIssuesCount: 4, // No escalated issues
    resolvedIssuesCount: 6,
    ignoredIssuesCount: 2,
    regressedIssuesCount: 1, // Has regressed issues
    topProjects: [
      {
        projectId: 40,
        projectName: 'Stable Production App',
        issuesCount: 5,
        newIssuesCount: 0,
        escalatedIssuesCount: 0,
        resolvedIssuesCount: 4,
        ignoredIssuesCount: 1,
        regressedIssuesCount: 1,
      },
      {
        projectId: 41,
        projectName: 'Monitoring Service',
        issuesCount: 3,
        newIssuesCount: 0,
        escalatedIssuesCount: 0,
        resolvedIssuesCount: 2,
        ignoredIssuesCount: 1,
        regressedIssuesCount: 0,
      },
    ],
    newIssuesList: [], // Empty list
  },
  annotations: {
    hasAnnotations: true,
    annotationsCount: 423,
    passedCount: 389,
    failedCount: 34,
    passedPercentage: 91.96,
    failedPercentage: 8.04,
    firstProjectId: 1,
    topProjects: [
      {
        projectId: 40,
        projectName: 'Stable Production App',
        annotationsCount: 312,
        passedCount: 289,
        failedCount: 23,
        passedPercentage: 92.63,
        failedPercentage: 7.37,
      },
      {
        projectId: 41,
        projectName: 'Monitoring Service',
        annotationsCount: 111,
        passedCount: 100,
        failedCount: 11,
        passedPercentage: 90.09,
        failedPercentage: 9.91,
      },
    ],
  },
}

// Profile 6: Workspace with high volume activity
export const highVolumeProfile: WeeklyEmailMailProps = {
  currentWorkspace: { id: 5, name: 'Acme Corp Production' },
  logs: {
    usedInProduction: true,
    logsCount: 1245678,
    tokensSpent: 45678912,
    tokensCost: 731.26,
    topProjects: [
      {
        projectId: 30,
        projectName: 'Global Chat Platform',
        logsCount: 523456,
        tokensSpent: 19234567,
        tokensCost: 307.75,
      },
      {
        projectId: 31,
        projectName: 'AI Assistant API',
        logsCount: 412345,
        tokensSpent: 15678901,
        tokensCost: 250.86,
      },
      {
        projectId: 32,
        projectName: 'Document Processor',
        logsCount: 198765,
        tokensSpent: 7234567,
        tokensCost: 115.75,
      },
      {
        projectId: 33,
        projectName: 'Translation Service',
        logsCount: 111112,
        tokensSpent: 3530877,
        tokensCost: 56.49,
      },
    ],
  },
  issues: {
    hasIssues: true,
    issuesCount: 28,
    newIssuesCount: 12,
    escalatedIssuesCount: 5,
    resolvedIssuesCount: 18,
    ignoredIssuesCount: 3,
    regressedIssuesCount: 2,
    topProjects: [
      {
        projectId: 30,
        projectName: 'Global Chat Platform',
        issuesCount: 15,
        newIssuesCount: 7,
        escalatedIssuesCount: 3,
        resolvedIssuesCount: 10,
        ignoredIssuesCount: 2,
        regressedIssuesCount: 1,
      },
      {
        projectId: 31,
        projectName: 'AI Assistant API',
        issuesCount: 13,
        newIssuesCount: 5,
        escalatedIssuesCount: 2,
        resolvedIssuesCount: 8,
        ignoredIssuesCount: 1,
        regressedIssuesCount: 1,
      },
    ],
    newIssuesList: [
      {
        id: 301,
        title: 'High latency in chat message processing',
        projectId: 30,
        commitUuid: 'global789xyz123',
      },
      {
        id: 302,
        title: 'WebSocket connection drops under load',
        projectId: 30,
        commitUuid: 'global789xyz123',
      },
      {
        id: 303,
        title: 'Context window overflow in long conversations',
        projectId: 31,
        commitUuid: 'ai456def789',
      },
      {
        id: 304,
        title: 'Rate limiting bypass vulnerability',
        projectId: 31,
        commitUuid: 'ai456def789',
      },
      {
        id: 305,
        title: 'Translation accuracy degradation for Asian languages',
        projectId: 33,
        commitUuid: 'trans123abc456',
      },
      {
        id: 306,
        title: 'Document parsing fails for PDFs over 10MB',
        projectId: 32,
        commitUuid: 'doc789xyz012',
      },
      {
        id: 307,
        title: 'Memory leak in streaming response handler',
        projectId: 30,
        commitUuid: 'global789xyz123',
      },
      {
        id: 308,
        title: 'Authentication token refresh race condition',
        projectId: 31,
        commitUuid: 'ai456def789',
      },
      {
        id: 309,
        title: 'Cache invalidation not working correctly',
        projectId: 30,
        commitUuid: 'global789xyz123',
      },
      {
        id: 310,
        title: 'Database query timeout on analytics dashboard',
        projectId: 32,
        commitUuid: 'doc789xyz012',
      },
    ],
  },
  annotations: {
    hasAnnotations: true,
    annotationsCount: 1834,
    passedCount: 1523,
    failedCount: 311,
    passedPercentage: 83.04,
    failedPercentage: 16.96,
    firstProjectId: 30,
    topProjects: [
      {
        projectId: 30,
        projectName: 'Global Chat Platform',
        annotationsCount: 892,
        passedCount: 756,
        failedCount: 136,
        passedPercentage: 84.75,
        failedPercentage: 15.25,
      },
      {
        projectId: 31,
        projectName: 'AI Assistant API',
        annotationsCount: 623,
        passedCount: 512,
        failedCount: 111,
        passedPercentage: 82.18,
        failedPercentage: 17.82,
      },
      {
        projectId: 32,
        projectName: 'Document Processor',
        annotationsCount: 319,
        passedCount: 255,
        failedCount: 64,
        passedPercentage: 79.94,
        failedPercentage: 20.06,
      },
    ],
  },
}
