name: Publish TypeScript SDK

on:
  workflow_call:
  workflow_dispatch:

jobs:
  publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Publish
        uses: ./.github/actions/publish-npm-package
        with:
          package_path: packages/sdk/typescript
          npm_package: "@latitude-data/sdk"
          pnpm_filter: "@latitude-data/sdk"
          tag_prefix: typescript-sdk
          release_name: TypeScript SDK
          npm_token: ${{ secrets.NPM_TOKEN }}
