name: Publish TypeScript Telemetry

on:
  workflow_call:
  workflow_dispatch:

jobs:
  publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Publish
        uses: ./.github/actions/publish-npm-package
        with:
          package_path: packages/telemetry/typescript
          npm_package: "@latitude-data/telemetry"
          pnpm_filter: "@latitude-data/telemetry"
          tag_prefix: typescript-telemetry
          release_name: TypeScript Telemetry
