// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         storeId: "storeId",
 *         recordId: "recordId",
 *         spanId: "spanId"
 *     }
 */
export interface GetRecordChangeMemoryRequest {
    /** Store identifier (`gen_ai.memory.store.id`). Pass an empty string to address the unattributed ("") store. */
    storeId: string;
    /** Record identifier (`gen_ai.memory.record.id`). Pass an empty string to address the unnamed record. */
    recordId: string;
    /** Span that authored the change (the `after` side). */
    spanId: string;
}
