export const MINIMUM_NEGATIVE_ANNOTATIONS_FOR_THIS_ISSUE = 5
export const MINIMUM_POSITIVE_OR_OTHER_NEGATIVE_ANNOTATIONS_FOR_OTHER_ISSUES = 5
export const MINIMUM_MONTLY_ANNOTATIONS = 10
export const OPTIMAL_MONTLY_ANNOTATIONS = 100
